<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 RM1 Data Wrangling | MSc Conversion in Psychological Studies/Science</title>
  <meta name="description" content="This is the materials for the one-year MSc Conversion in Psychological Studies/Science." />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 RM1 Data Wrangling | MSc Conversion in Psychological Studies/Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the materials for the one-year MSc Conversion in Psychological Studies/Science." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 RM1 Data Wrangling | MSc Conversion in Psychological Studies/Science" />
  
  <meta name="twitter:description" content="This is the materials for the one-year MSc Conversion in Psychological Studies/Science." />
  



<meta name="date" content="2019-07-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="rm1-intro-to-r.html">
<link rel="next" href="rm1-data-wrangling-chi-square.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include\psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSc Conversion in Psychological Studies/Science (face-to-face)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#notes-for-instructors"><i class="fa fa-check"></i><b>0.1</b> Notes for instructors</a><ul>
<li class="chapter" data-level="0.1.1" data-path="index.html"><a href="index.html#overview-of-msc-conversion-course"><i class="fa fa-check"></i><b>0.1.1</b> Overview of MSc Conversion course</a></li>
<li class="chapter" data-level="0.1.2" data-path="index.html"><a href="index.html#course-structure"><i class="fa fa-check"></i><b>0.1.2</b> Course structure</a></li>
<li class="chapter" data-level="0.1.3" data-path="index.html"><a href="index.html#teaching-open-and-reproducible-science"><i class="fa fa-check"></i><b>0.1.3</b> Teaching open and reproducible science</a></li>
<li class="chapter" data-level="0.1.4" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>0.1.4</b> Assessment</a></li>
<li class="chapter" data-level="0.1.5" data-path="index.html"><a href="index.html#contact-details"><i class="fa fa-check"></i><b>0.1.5</b> Contact details</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#student-overview"><i class="fa fa-check"></i><b>0.2</b> Student overview</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i><b>0.3</b> How to use this book</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#data-files"><i class="fa fa-check"></i><b>0.4</b> Data files</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#intended-learning-outcomes"><i class="fa fa-check"></i><b>0.5</b> Intended Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ref3.html"><a href="ref3.html"><i class="fa fa-check"></i><b>1</b> Programming Basics</a><ul>
<li class="chapter" data-level="1.1" data-path="ref3.html"><a href="ref3.html#notes-for-instructors-1"><i class="fa fa-check"></i><b>1.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="1.2" data-path="ref3.html"><a href="ref3.html#introduction"><i class="fa fa-check"></i><b>1.2</b> Introduction</a></li>
<li class="chapter" data-level="1.3" data-path="ref3.html"><a href="ref3.html#r-and-r-studio"><i class="fa fa-check"></i><b>1.3</b> R and R Studio</a><ul>
<li class="chapter" data-level="1.3.1" data-path="ref3.html"><a href="ref3.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>1.3.1</b> Getting to know R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="ref3.html"><a href="ref3.html#functions-and-arguments"><i class="fa fa-check"></i><b>1.4</b> Functions and arguments</a><ul>
<li class="chapter" data-level="1.4.1" data-path="ref3.html"><a href="ref3.html#argument-names"><i class="fa fa-check"></i><b>1.4.1</b> Argument names</a></li>
<li class="chapter" data-level="1.4.2" data-path="ref3.html"><a href="ref3.html#tab-auto-complete"><i class="fa fa-check"></i><b>1.4.2</b> Tab auto-complete</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="ref3.html"><a href="ref3.html#packages"><i class="fa fa-check"></i><b>1.5</b> Base R and packages</a><ul>
<li class="chapter" data-level="1.5.1" data-path="ref3.html"><a href="ref3.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>1.5.1</b> Installing and loading packages</a></li>
<li class="chapter" data-level="1.5.2" data-path="ref3.html"><a href="ref3.html#package-updates"><i class="fa fa-check"></i><b>1.5.2</b> Package updates</a></li>
<li class="chapter" data-level="1.5.3" data-path="ref3.html"><a href="ref3.html#conflicts"><i class="fa fa-check"></i><b>1.5.3</b> Package conflicts</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="ref3.html"><a href="ref3.html#objects"><i class="fa fa-check"></i><b>1.6</b> Objects</a></li>
<li class="chapter" data-level="1.7" data-path="ref3.html"><a href="ref3.html#looking-after-the-environment"><i class="fa fa-check"></i><b>1.7</b> Looking after the environment</a></li>
<li class="chapter" data-level="1.8" data-path="ref3.html"><a href="ref3.html#r-sessions"><i class="fa fa-check"></i><b>1.8</b> R sessions</a></li>
<li class="chapter" data-level="1.9" data-path="ref3.html"><a href="ref3.html#help-and-additional-resources"><i class="fa fa-check"></i><b>1.9</b> Help and additional resources</a></li>
<li class="chapter" data-level="1.10" data-path="ref3.html"><a href="ref3.html#debugging-tips"><i class="fa fa-check"></i><b>1.10</b> Debugging tips</a></li>
<li class="chapter" data-level="1.11" data-path="ref3.html"><a href="ref3.html#test-yourself"><i class="fa fa-check"></i><b>1.11</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html"><i class="fa fa-check"></i><b>2</b> RM1 Intro to R</a><ul>
<li class="chapter" data-level="2.1" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#notes-for-instructors-2"><i class="fa fa-check"></i><b>2.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="2.2" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#ref2"><i class="fa fa-check"></i><b>2.2</b> Pre-class activities</a><ul>
<li class="chapter" data-level="2.2.1" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-1-programming-basics"><i class="fa fa-check"></i><b>2.2.1</b> Activity 1: Programming basics</a></li>
<li class="chapter" data-level="2.2.2" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-2-create-the-working-directory"><i class="fa fa-check"></i><b>2.2.2</b> Activity 2: Create the working directory</a></li>
<li class="chapter" data-level="2.2.3" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-3-set-the-working-directory"><i class="fa fa-check"></i><b>2.2.3</b> Activity 3: Set the working directory</a></li>
<li class="chapter" data-level="2.2.4" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#r-markdown-for-r-book-work-and-portfolio-assignments"><i class="fa fa-check"></i><b>2.2.4</b> R Markdown for R book work and portfolio assignments</a></li>
<li class="chapter" data-level="2.2.5" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-4-open-and-save-a-new-r-markdown-document"><i class="fa fa-check"></i><b>2.2.5</b> Activity 4: Open and save a new R Markdown document</a></li>
<li class="chapter" data-level="2.2.6" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-5-create-a-new-code-chunk"><i class="fa fa-check"></i><b>2.2.6</b> Activity 5: Create a new code chunk</a></li>
<li class="chapter" data-level="2.2.7" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-6-write-some-code"><i class="fa fa-check"></i><b>2.2.7</b> Activity 6: Write some code</a></li>
<li class="chapter" data-level="2.2.8" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#running-code"><i class="fa fa-check"></i><b>2.2.8</b> Running code</a></li>
<li class="chapter" data-level="2.2.9" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-7-run-your-code"><i class="fa fa-check"></i><b>2.2.9</b> Activity 7: Run your code</a></li>
<li class="chapter" data-level="2.2.10" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-8-inline-code"><i class="fa fa-check"></i><b>2.2.10</b> Activity 8: Inline code</a></li>
<li class="chapter" data-level="2.2.11" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-9-knitting-your-file"><i class="fa fa-check"></i><b>2.2.11</b> Activity 9: Knitting your file</a></li>
<li class="chapter" data-level="2.2.12" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#finished"><i class="fa fa-check"></i><b>2.2.12</b> Finished</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#lab1-inclass"><i class="fa fa-check"></i><b>2.3</b> In-class activities</a><ul>
<li class="chapter" data-level="2.3.1" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#getting-data-ready-to-work-with"><i class="fa fa-check"></i><b>2.3.1</b> Getting data ready to work with</a></li>
<li class="chapter" data-level="2.3.2" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-1-set-up"><i class="fa fa-check"></i><b>2.3.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="2.3.3" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-2-load-in-the-package"><i class="fa fa-check"></i><b>2.3.3</b> Activity 2: Load in the package</a></li>
<li class="chapter" data-level="2.3.4" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#open-data"><i class="fa fa-check"></i><b>2.3.4</b> Open data</a></li>
<li class="chapter" data-level="2.3.5" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-3-read-in-data"><i class="fa fa-check"></i><b>2.3.5</b> Activity 3: Read in data</a></li>
<li class="chapter" data-level="2.3.6" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-4-check-yo-data"><i class="fa fa-check"></i><b>2.3.6</b> Activity 4: Check yo’ data</a></li>
<li class="chapter" data-level="2.3.7" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-5-join-the-files-together"><i class="fa fa-check"></i><b>2.3.7</b> Activity 5: Join the files together</a></li>
<li class="chapter" data-level="2.3.8" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#ref1"><i class="fa fa-check"></i><b>2.3.8</b> Activity 6: Pull out variables of interest</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#debugging-tips-1"><i class="fa fa-check"></i><b>2.4</b> Debugging tips</a></li>
<li class="chapter" data-level="2.5" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#test-yourself-1"><i class="fa fa-check"></i><b>2.5</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html"><i class="fa fa-check"></i><b>3</b> RM1 Data Wrangling</a><ul>
<li class="chapter" data-level="3.1" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#notes-for-instructors-3"><i class="fa fa-check"></i><b>3.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="3.2" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#pre-class-activities"><i class="fa fa-check"></i><b>3.2</b> Pre-class activities</a><ul>
<li class="chapter" data-level="3.2.1" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#data-wrangling-and-the-tidyverse"><i class="fa fa-check"></i><b>3.2.1</b> Data wrangling and the tidyverse</a></li>
<li class="chapter" data-level="3.2.2" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#the-babynames-database"><i class="fa fa-check"></i><b>3.2.2</b> The <code>babynames</code> database</a></li>
<li class="chapter" data-level="3.2.3" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-1-set-up-1"><i class="fa fa-check"></i><b>3.2.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="3.2.4" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-2-look-at-the-data"><i class="fa fa-check"></i><b>3.2.4</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="3.2.5" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-3-your-first-plot"><i class="fa fa-check"></i><b>3.2.5</b> Activity 3: Your first plot</a></li>
<li class="chapter" data-level="3.2.6" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-4-selecting-variables-of-interest"><i class="fa fa-check"></i><b>3.2.6</b> Activity 4: Selecting variables of interest</a></li>
<li class="chapter" data-level="3.2.7" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-5-arranging-the-data"><i class="fa fa-check"></i><b>3.2.7</b> Activity 5: Arranging the data</a></li>
<li class="chapter" data-level="3.2.8" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-6-using-filter-to-select-observations"><i class="fa fa-check"></i><b>3.2.8</b> Activity 6: Using filter to select observations</a></li>
<li class="chapter" data-level="3.2.9" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-7-creating-new-variables"><i class="fa fa-check"></i><b>3.2.9</b> Activity 7: Creating new variables</a></li>
<li class="chapter" data-level="3.2.10" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-8-grouping-and-summarising"><i class="fa fa-check"></i><b>3.2.10</b> Activity 8: Grouping and summarising</a></li>
<li class="chapter" data-level="3.2.11" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-9-pipes"><i class="fa fa-check"></i><b>3.2.11</b> Activity 9: Pipes</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#in-class-activities"><i class="fa fa-check"></i><b>3.3</b> In-class activities</a><ul>
<li class="chapter" data-level="3.3.1" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#data-wrangling-a-key-skill"><i class="fa fa-check"></i><b>3.3.1</b> Data-wrangling: A key skill</a></li>
<li class="chapter" data-level="3.3.2" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#learning-to-wrangle-is-there-a-chastity-belt-on-perception"><i class="fa fa-check"></i><b>3.3.2</b> Learning to wrangle: Is there a chastity belt on perception</a></li>
<li class="chapter" data-level="3.3.3" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-1-set-up-2"><i class="fa fa-check"></i><b>3.3.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="3.3.4" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-2-look-at-your-data"><i class="fa fa-check"></i><b>3.3.4</b> Activity 2: Look at your data</a></li>
<li class="chapter" data-level="3.3.5" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-3-select"><i class="fa fa-check"></i><b>3.3.5</b> Activity 3: <strong><code>select()</code></strong></a></li>
<li class="chapter" data-level="3.3.6" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-4-reorder-the-variables"><i class="fa fa-check"></i><b>3.3.6</b> Activity 4: Reorder the variables</a></li>
<li class="chapter" data-level="3.3.7" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-5-arrange-f"><i class="fa fa-check"></i><b>3.3.7</b> Activity 5: <strong><code>arrange()</code></strong> F</a></li>
<li class="chapter" data-level="3.3.8" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-6-filter"><i class="fa fa-check"></i><b>3.3.8</b> Activity 6: <code>filter()</code></a></li>
<li class="chapter" data-level="3.3.9" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-7-mutate"><i class="fa fa-check"></i><b>3.3.9</b> Activity 7: <code>mutate()</code></a></li>
<li class="chapter" data-level="3.3.10" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-8-group_by"><i class="fa fa-check"></i><b>3.3.10</b> Activity 8: <code>group_by()</code></a></li>
<li class="chapter" data-level="3.3.11" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-9-summarising-data"><i class="fa fa-check"></i><b>3.3.11</b> Activity 9: Summarising data</a></li>
<li class="chapter" data-level="3.3.12" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#two-other-useful-functions"><i class="fa fa-check"></i><b>3.3.12</b> Two other useful functions</a></li>
<li class="chapter" data-level="3.3.13" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#pipes"><i class="fa fa-check"></i><b>3.3.13</b> Pipes (<strong><code>%&gt;%</code></strong>)</a></li>
<li class="chapter" data-level="3.3.14" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-solutions"><i class="fa fa-check"></i><b>3.3.14</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#debugging-tips-2"><i class="fa fa-check"></i><b>3.4</b> Debugging tips</a></li>
<li class="chapter" data-level="3.5" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#test-yourself-2"><i class="fa fa-check"></i><b>3.5</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html"><i class="fa fa-check"></i><b>4</b> RM1 Data Wrangling &amp; Chi-Square</a><ul>
<li class="chapter" data-level="4.1" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#notes-for-instructors-4"><i class="fa fa-check"></i><b>4.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="4.2" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#pre-lab-activities"><i class="fa fa-check"></i><b>4.2</b> Pre-lab activities</a><ul>
<li class="chapter" data-level="4.2.1" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#data-wrangling-recap"><i class="fa fa-check"></i><b>4.2.1</b> Data wrangling recap</a></li>
<li class="chapter" data-level="4.2.2" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#tidy-data"><i class="fa fa-check"></i><b>4.2.2</b> Tidy data</a></li>
<li class="chapter" data-level="4.2.3" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#analysing-the-autism-spectrum-quotient-aq"><i class="fa fa-check"></i><b>4.2.3</b> Analysing the Autism Spectrum Quotient (AQ)</a></li>
<li class="chapter" data-level="4.2.4" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-1-set-up-3"><i class="fa fa-check"></i><b>4.2.4</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="4.2.5" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-2-load-in-the-data"><i class="fa fa-check"></i><b>4.2.5</b> Activity 2: Load in the data</a></li>
<li class="chapter" data-level="4.2.6" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-3-look-at-your-data"><i class="fa fa-check"></i><b>4.2.6</b> Activity 3: Look at your data</a></li>
<li class="chapter" data-level="4.2.7" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#gather"><i class="fa fa-check"></i><b>4.2.7</b> Activity 4: Gathering data</a></li>
<li class="chapter" data-level="4.2.8" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#join"><i class="fa fa-check"></i><b>4.2.8</b> Activity 5: Combining data</a></li>
<li class="chapter" data-level="4.2.9" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-6-combining-more-data"><i class="fa fa-check"></i><b>4.2.9</b> Activity 6: Combining more data</a></li>
<li class="chapter" data-level="4.2.10" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-7-calculating-the-aq-scores."><i class="fa fa-check"></i><b>4.2.10</b> Activity 7: Calculating the AQ scores.</a></li>
<li class="chapter" data-level="4.2.11" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-8-one-last-thing-on-pipes"><i class="fa fa-check"></i><b>4.2.11</b> Activity 8: One last thing on pipes</a></li>
<li class="chapter" data-level="4.2.12" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-solutions-1"><i class="fa fa-check"></i><b>4.2.12</b> Activity solutions</a></li>
<li class="chapter" data-level="4.2.13" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#test-yourself-3"><i class="fa fa-check"></i><b>4.2.13</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#in-class-activities-1"><i class="fa fa-check"></i><b>4.3</b> In-class activities</a><ul>
<li class="chapter" data-level="4.3.1" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#data-analysis"><i class="fa fa-check"></i><b>4.3.1</b> Data analysis</a></li>
<li class="chapter" data-level="4.3.2" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#reminders-through-association"><i class="fa fa-check"></i><b>4.3.2</b> Reminders through association</a></li>
<li class="chapter" data-level="4.3.3" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-1-set-up-4"><i class="fa fa-check"></i><b>4.3.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="4.3.4" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-2-look-at-the-data-1"><i class="fa fa-check"></i><b>4.3.4</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="4.3.5" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-3-wrangle-and-recode-the-data"><i class="fa fa-check"></i><b>4.3.5</b> Activity 3: Wrangle and recode the data</a></li>
<li class="chapter" data-level="4.3.6" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-4-descriptive-statistics"><i class="fa fa-check"></i><b>4.3.6</b> Activity 4: Descriptive statistics</a></li>
<li class="chapter" data-level="4.3.7" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#ggplot2"><i class="fa fa-check"></i><b>4.3.7</b> <code>ggplot2()</code></a></li>
<li class="chapter" data-level="4.3.8" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#bar"><i class="fa fa-check"></i><b>4.3.8</b> Activity 5: Bar plot</a></li>
<li class="chapter" data-level="4.3.9" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-6-make-the-plot-pretty"><i class="fa fa-check"></i><b>4.3.9</b> Activity 6: Make the plot pretty</a></li>
<li class="chapter" data-level="4.3.10" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-7-chi-square"><i class="fa fa-check"></i><b>4.3.10</b> Activity 7: Chi-square</a></li>
<li class="chapter" data-level="4.3.11" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-8-additional-analysis-information"><i class="fa fa-check"></i><b>4.3.11</b> Activity 8: Additional analysis information</a></li>
<li class="chapter" data-level="4.3.12" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#assumption-checks"><i class="fa fa-check"></i><b>4.3.12</b> Assumption checks</a></li>
<li class="chapter" data-level="4.3.13" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-9-check-the-expected-frequencies"><i class="fa fa-check"></i><b>4.3.13</b> Activity 9: Check the expected frequencies</a></li>
<li class="chapter" data-level="4.3.14" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#cramer"><i class="fa fa-check"></i><b>4.3.14</b> Activity 10: Effect size</a></li>
<li class="chapter" data-level="4.3.15" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-11-write-up"><i class="fa fa-check"></i><b>4.3.15</b> Activity 11: Write-up</a></li>
<li class="chapter" data-level="4.3.16" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-solutions-2"><i class="fa fa-check"></i><b>4.3.16</b> Activity solutions</a></li>
<li class="chapter" data-level="4.3.17" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#test-yourself-4"><i class="fa fa-check"></i><b>4.3.17</b> Test yourself</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html"><i class="fa fa-check"></i><b>5</b> RM2 R Markdown &amp; Correlations</a><ul>
<li class="chapter" data-level="5.1" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#pre-class-activities-1"><i class="fa fa-check"></i><b>5.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="5.1.1" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-1-revise"><i class="fa fa-check"></i><b>5.1.1</b> Activity 1: Revise</a></li>
<li class="chapter" data-level="5.1.2" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#r-markdown"><i class="fa fa-check"></i><b>5.1.2</b> R Markdown</a></li>
<li class="chapter" data-level="5.1.3" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#advantages-of-using-r-markdown"><i class="fa fa-check"></i><b>5.1.3</b> Advantages of using R Markdown</a></li>
<li class="chapter" data-level="5.1.4" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-2-create-a-new-markdown-document"><i class="fa fa-check"></i><b>5.1.4</b> Activity 2: Create a new Markdown document</a></li>
<li class="chapter" data-level="5.1.5" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-3-setting-up-the-new-markdown-document"><i class="fa fa-check"></i><b>5.1.5</b> Activity 3: Setting up the new Markdown document</a></li>
<li class="chapter" data-level="5.1.6" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-4-new-code-chunks"><i class="fa fa-check"></i><b>5.1.6</b> Activity 4: New code chunks</a></li>
<li class="chapter" data-level="5.1.7" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-5-knit-your-code"><i class="fa fa-check"></i><b>5.1.7</b> Activity 5: Knit your code</a></li>
<li class="chapter" data-level="5.1.8" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-6-adding-rules-to-code-chunks"><i class="fa fa-check"></i><b>5.1.8</b> Activity 6: Adding rules to code chunks</a></li>
<li class="chapter" data-level="5.1.9" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-7-formatting-the-r-markdown-file"><i class="fa fa-check"></i><b>5.1.9</b> Activity 7: Formatting the R Markdown File</a></li>
<li class="chapter" data-level="5.1.10" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#test-yourself-5"><i class="fa fa-check"></i><b>5.1.10</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#in-class-activities-2"><i class="fa fa-check"></i><b>5.2</b> In-class activities</a><ul>
<li class="chapter" data-level="5.2.1" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#correlations"><i class="fa fa-check"></i><b>5.2.1</b> Correlations</a></li>
<li class="chapter" data-level="5.2.2" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-1-set-up-5"><i class="fa fa-check"></i><b>5.2.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="5.2.3" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-2-look-at-your-data-1"><i class="fa fa-check"></i><b>5.2.3</b> Activity 2: Look at your data</a></li>
<li class="chapter" data-level="5.2.4" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-3-assumptions"><i class="fa fa-check"></i><b>5.2.4</b> Activity 3: Assumptions</a></li>
<li class="chapter" data-level="5.2.5" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-4-descriptive-statistics-1"><i class="fa fa-check"></i><b>5.2.5</b> Activity 4: Descriptive statistics</a></li>
<li class="chapter" data-level="5.2.6" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-5-correlation"><i class="fa fa-check"></i><b>5.2.6</b> Activity 5: Correlation</a></li>
<li class="chapter" data-level="5.2.7" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-6-interpreting-the-correlation"><i class="fa fa-check"></i><b>5.2.7</b> Activity 6: Interpreting the correlation</a></li>
<li class="chapter" data-level="5.2.8" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-7-write-up"><i class="fa fa-check"></i><b>5.2.8</b> Activity 7: Write-up</a></li>
<li class="chapter" data-level="5.2.9" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-8-scatterplot-matrix"><i class="fa fa-check"></i><b>5.2.9</b> Activity 8: Scatterplot matrix</a></li>
<li class="chapter" data-level="5.2.10" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-9-multiple-correlations"><i class="fa fa-check"></i><b>5.2.10</b> Activity 9: Multiple correlations</a></li>
<li class="chapter" data-level="5.2.11" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-solutions-3"><i class="fa fa-check"></i><b>5.2.11</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html"><i class="fa fa-check"></i><b>6</b> RM2 Missing Data &amp; T-Tests</a><ul>
<li class="chapter" data-level="6.1" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#pre-class-activities-2"><i class="fa fa-check"></i><b>6.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="6.1.1" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-1-set-up-6"><i class="fa fa-check"></i><b>6.1.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="6.1.2" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-2-look-at-the-data-2"><i class="fa fa-check"></i><b>6.1.2</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="6.1.3" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-3-listwise-deletion"><i class="fa fa-check"></i><b>6.1.3</b> Activity 3: Listwise deletion</a></li>
<li class="chapter" data-level="6.1.4" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#pairwise-deletion"><i class="fa fa-check"></i><b>6.1.4</b> Pairwise deletion</a></li>
<li class="chapter" data-level="6.1.5" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-3-na.rm-true"><i class="fa fa-check"></i><b>6.1.5</b> Activity 3: <code>na.rm = TRUE</code></a></li>
<li class="chapter" data-level="6.1.6" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-4-tidy-data"><i class="fa fa-check"></i><b>6.1.6</b> Activity 4: Tidy data</a></li>
<li class="chapter" data-level="6.1.7" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-5-questionnaire-data"><i class="fa fa-check"></i><b>6.1.7</b> Activity 5: Questionnaire data</a></li>
<li class="chapter" data-level="6.1.8" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-6-calculating-scale-scores"><i class="fa fa-check"></i><b>6.1.8</b> Activity 6: Calculating scale scores</a></li>
<li class="chapter" data-level="6.1.9" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-7-spread-back-to-wide-form"><i class="fa fa-check"></i><b>6.1.9</b> Activity 7: <code>spread()</code> back to wide-form</a></li>
<li class="chapter" data-level="6.1.10" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#finished-6"><i class="fa fa-check"></i><b>6.1.10</b> Finished!</a></li>
<li class="chapter" data-level="6.1.11" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-solutions-4"><i class="fa fa-check"></i><b>6.1.11</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#in-class-activities-3"><i class="fa fa-check"></i><b>6.2</b> In-class activities</a><ul>
<li class="chapter" data-level="6.2.1" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-1-set-up-7"><i class="fa fa-check"></i><b>6.2.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="6.2.2" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-2-explore-the-dataset"><i class="fa fa-check"></i><b>6.2.2</b> Activity 2: Explore the dataset</a></li>
<li class="chapter" data-level="6.2.3" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-3-ratings"><i class="fa fa-check"></i><b>6.2.3</b> Activity 3: Ratings</a></li>
<li class="chapter" data-level="6.2.4" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-4-visualisation"><i class="fa fa-check"></i><b>6.2.4</b> Activity 4: Visualisation</a></li>
<li class="chapter" data-level="6.2.5" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-5-assumptions"><i class="fa fa-check"></i><b>6.2.5</b> Activity 5: Assumptions</a></li>
<li class="chapter" data-level="6.2.6" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-6-running-the-t-test"><i class="fa fa-check"></i><b>6.2.6</b> Activity 6: Running the t-test</a></li>
<li class="chapter" data-level="6.2.7" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-8-correcting-for-multiple-comparisons"><i class="fa fa-check"></i><b>6.2.7</b> Activity 8: Correcting for multiple comparisons</a></li>
<li class="chapter" data-level="6.2.8" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-7-effect-size"><i class="fa fa-check"></i><b>6.2.8</b> Activity 7: Effect size</a></li>
<li class="chapter" data-level="6.2.9" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-8-interpreting-the-results"><i class="fa fa-check"></i><b>6.2.9</b> Activity 8: Interpreting the results</a></li>
<li class="chapter" data-level="6.2.10" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-9-write-up"><i class="fa fa-check"></i><b>6.2.10</b> Activity 9: Write-up</a></li>
<li class="chapter" data-level="6.2.11" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-10-paired-samples-t-test"><i class="fa fa-check"></i><b>6.2.11</b> Activity 10: Paired-samples t-test</a></li>
<li class="chapter" data-level="6.2.12" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-12-assumptions"><i class="fa fa-check"></i><b>6.2.12</b> Activity 12: Assumptions</a></li>
<li class="chapter" data-level="6.2.13" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-13-descriptives-and-visualisations"><i class="fa fa-check"></i><b>6.2.13</b> Activity 13: Descriptives and visualisations</a></li>
<li class="chapter" data-level="6.2.14" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-14-paired-samples-t-test"><i class="fa fa-check"></i><b>6.2.14</b> Activity 14: Paired-samples t-test</a></li>
<li class="chapter" data-level="6.2.15" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-15-write-up"><i class="fa fa-check"></i><b>6.2.15</b> Activity 15: Write-up</a></li>
<li class="chapter" data-level="6.2.16" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-solutions-5"><i class="fa fa-check"></i><b>6.2.16</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="vis.html"><a href="vis.html"><i class="fa fa-check"></i><b>7</b> RM2 Visualisation, power, and effect size</a><ul>
<li class="chapter" data-level="7.1" data-path="vis.html"><a href="vis.html#pre-class-activities-3"><i class="fa fa-check"></i><b>7.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="7.1.1" data-path="vis.html"><a href="vis.html#activity-1-set-up-8"><i class="fa fa-check"></i><b>7.1.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="7.1.2" data-path="vis.html"><a href="vis.html#activity-2-histograms"><i class="fa fa-check"></i><b>7.1.2</b> Activity 2: Histograms</a></li>
<li class="chapter" data-level="7.1.3" data-path="vis.html"><a href="vis.html#activity-3-scatterplots"><i class="fa fa-check"></i><b>7.1.3</b> Activity 3: Scatterplots</a></li>
<li class="chapter" data-level="7.1.4" data-path="vis.html"><a href="vis.html#activity-4-boxplots"><i class="fa fa-check"></i><b>7.1.4</b> Activity 4: Boxplots</a></li>
<li class="chapter" data-level="7.1.5" data-path="vis.html"><a href="vis.html#activity-5-reordering-factors"><i class="fa fa-check"></i><b>7.1.5</b> Activity 5: Reordering factors</a></li>
<li class="chapter" data-level="7.1.6" data-path="vis.html"><a href="vis.html#activity-6-bar-charts"><i class="fa fa-check"></i><b>7.1.6</b> Activity 6: Bar Charts</a></li>
<li class="chapter" data-level="7.1.7" data-path="vis.html"><a href="vis.html#activity-7-violin-plots"><i class="fa fa-check"></i><b>7.1.7</b> Activity 7: Violin plots</a></li>
<li class="chapter" data-level="7.1.8" data-path="vis.html"><a href="vis.html#viobox"><i class="fa fa-check"></i><b>7.1.8</b> Activity 8: Violin-boxplots</a></li>
<li class="chapter" data-level="7.1.9" data-path="vis.html"><a href="vis.html#activity-9-faceting"><i class="fa fa-check"></i><b>7.1.9</b> Activity 9: Faceting</a></li>
<li class="chapter" data-level="7.1.10" data-path="vis.html"><a href="vis.html#activity-10-split-violins-and-raincloud-plots"><i class="fa fa-check"></i><b>7.1.10</b> Activity 10: Split-violins and raincloud plots</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="vis.html"><a href="vis.html#in-class-activities-4"><i class="fa fa-check"></i><b>7.2</b> In-class activities</a><ul>
<li class="chapter" data-level="7.2.1" data-path="vis.html"><a href="vis.html#power-and-error"><i class="fa fa-check"></i><b>7.2.1</b> Power and Error</a></li>
<li class="chapter" data-level="7.2.2" data-path="vis.html"><a href="vis.html#effect-size"><i class="fa fa-check"></i><b>7.2.2</b> Effect Size</a></li>
<li class="chapter" data-level="7.2.3" data-path="vis.html"><a href="vis.html#activity-1-set-up-9"><i class="fa fa-check"></i><b>7.2.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="7.2.4" data-path="vis.html"><a href="vis.html#activity-2-effect-size-from-a-one-sample-t-test"><i class="fa fa-check"></i><b>7.2.4</b> Activity 2: Effect size from a one-sample t-test</a></li>
<li class="chapter" data-level="7.2.5" data-path="vis.html"><a href="vis.html#activity-3-effect-size-from-between-subjects-t-test"><i class="fa fa-check"></i><b>7.2.5</b> Activity 3: Effect size from between-subjects t-test</a></li>
<li class="chapter" data-level="7.2.6" data-path="vis.html"><a href="vis.html#activity-4-t-value-and-effect-size-for-a-between-subjects-experiment"><i class="fa fa-check"></i><b>7.2.6</b> Activity 4: t-value and effect size for a between-subjects Experiment</a></li>
<li class="chapter" data-level="7.2.7" data-path="vis.html"><a href="vis.html#activity-5-pwr.t.test"><i class="fa fa-check"></i><b>7.2.7</b> Activity 5: <code>pwr.t.test()</code></a></li>
<li class="chapter" data-level="7.2.8" data-path="vis.html"><a href="vis.html#activity-6-sample-size-for-standard-power-one-sample-t-test"><i class="fa fa-check"></i><b>7.2.8</b> Activity 6: Sample size for standard power one-sample t-test</a></li>
<li class="chapter" data-level="7.2.9" data-path="vis.html"><a href="vis.html#activity-7-effect-size-from-a-high-power-between-subjects-t-test"><i class="fa fa-check"></i><b>7.2.9</b> Activity 7: Effect size from a high power between-subjects t-test</a></li>
<li class="chapter" data-level="7.2.10" data-path="vis.html"><a href="vis.html#activity-8-sample-size-for-a-correlation"><i class="fa fa-check"></i><b>7.2.10</b> Activity 8: Sample size for a correlation</a></li>
<li class="chapter" data-level="7.2.11" data-path="vis.html"><a href="vis.html#activity-9-effect-size-for-a-correlation-analysis"><i class="fa fa-check"></i><b>7.2.11</b> Activity 9: Effect size for a correlation analysis</a></li>
<li class="chapter" data-level="7.2.12" data-path="vis.html"><a href="vis.html#activity-10-effect-size-for-chi-square"><i class="fa fa-check"></i><b>7.2.12</b> Activity 10: Effect size for chi-square</a></li>
<li class="chapter" data-level="7.2.13" data-path="vis.html"><a href="vis.html#activity-11-power-of-published-research"><i class="fa fa-check"></i><b>7.2.13</b> Activity 11: Power of published research</a></li>
<li class="chapter" data-level="7.2.14" data-path="vis.html"><a href="vis.html#activity-solutions-6"><i class="fa fa-check"></i><b>7.2.14</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="rm2-anova.html"><a href="rm2-anova.html"><i class="fa fa-check"></i><b>8</b> RM2 ANOVA</a><ul>
<li class="chapter" data-level="8.1" data-path="rm2-anova.html"><a href="rm2-anova.html#pre-class-activities-4"><i class="fa fa-check"></i><b>8.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="8.1.1" data-path="rm2-anova.html"><a href="rm2-anova.html#background-intrusive-memories"><i class="fa fa-check"></i><b>8.1.1</b> Background: Intrusive memories</a></li>
<li class="chapter" data-level="8.1.2" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-1-set-up-10"><i class="fa fa-check"></i><b>8.1.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="8.1.3" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-2-data-wrangling"><i class="fa fa-check"></i><b>8.1.3</b> Activity 2: Data wrangling</a></li>
<li class="chapter" data-level="8.1.4" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-3-numbers-and-factors"><i class="fa fa-check"></i><b>8.1.4</b> Activity 3: Numbers and factors</a></li>
<li class="chapter" data-level="8.1.5" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-4-create-summary-statistics"><i class="fa fa-check"></i><b>8.1.5</b> Activity 4: Create summary statistics</a></li>
<li class="chapter" data-level="8.1.6" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-5-visualisation"><i class="fa fa-check"></i><b>8.1.6</b> Activity 5: Visualisation</a></li>
<li class="chapter" data-level="8.1.7" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-6-one-way-anova"><i class="fa fa-check"></i><b>8.1.7</b> Activity 6: One-way ANOVA</a></li>
<li class="chapter" data-level="8.1.8" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-7-assumption-checking"><i class="fa fa-check"></i><b>8.1.8</b> Activity 7: Assumption checking</a></li>
<li class="chapter" data-level="8.1.9" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-8-post-hoc-tests"><i class="fa fa-check"></i><b>8.1.9</b> Activity 8: Post-hoc tests</a></li>
<li class="chapter" data-level="8.1.10" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-9-power-and-effect-size"><i class="fa fa-check"></i><b>8.1.10</b> Activity 9: Power and effect size</a></li>
<li class="chapter" data-level="8.1.11" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-10-write-up"><i class="fa fa-check"></i><b>8.1.11</b> Activity 10: Write-up</a></li>
<li class="chapter" data-level="8.1.12" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-solutions-7"><i class="fa fa-check"></i><b>8.1.12</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="rm2-anova.html"><a href="rm2-anova.html#in-class-activities-5"><i class="fa fa-check"></i><b>8.2</b> In-class activities</a><ul>
<li class="chapter" data-level="8.2.1" data-path="rm2-anova.html"><a href="rm2-anova.html#factorial-anova"><i class="fa fa-check"></i><b>8.2.1</b> Factorial ANOVA</a></li>
<li class="chapter" data-level="8.2.2" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-1-set-up-11"><i class="fa fa-check"></i><b>8.2.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="8.2.3" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-2-descriptive-statistics"><i class="fa fa-check"></i><b>8.2.3</b> Activity 2: Descriptive statistics</a></li>
<li class="chapter" data-level="8.2.4" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-3-violin-boxplots"><i class="fa fa-check"></i><b>8.2.4</b> Activity 3: Violin-boxplots</a></li>
<li class="chapter" data-level="8.2.5" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-4-interaction-plots"><i class="fa fa-check"></i><b>8.2.5</b> Activity 4: Interaction plots</a></li>
<li class="chapter" data-level="8.2.6" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-5-anova"><i class="fa fa-check"></i><b>8.2.6</b> Activity 5: ANOVA</a></li>
<li class="chapter" data-level="8.2.7" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-6-assumption-checking"><i class="fa fa-check"></i><b>8.2.7</b> Activity 6: Assumption checking</a></li>
<li class="chapter" data-level="8.2.8" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-7-post-hoc-tests"><i class="fa fa-check"></i><b>8.2.8</b> Activity 7: Post-hoc tests</a></li>
<li class="chapter" data-level="8.2.9" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-8-write-up"><i class="fa fa-check"></i><b>8.2.9</b> Activity 8: Write-up</a></li>
<li class="chapter" data-level="8.2.10" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-9-transforming-data"><i class="fa fa-check"></i><b>8.2.10</b> Activity 9: Transforming data</a></li>
<li class="chapter" data-level="8.2.11" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-solutions-8"><i class="fa fa-check"></i><b>8.2.11</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="rm2-regression.html"><a href="rm2-regression.html"><i class="fa fa-check"></i><b>9</b> RM2 Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="rm2-regression.html"><a href="rm2-regression.html#pre-class-activities-5"><i class="fa fa-check"></i><b>9.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="9.1.1" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-1-setup"><i class="fa fa-check"></i><b>9.1.1</b> Activity 1: Setup</a></li>
<li class="chapter" data-level="9.1.2" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-2-tidy-the-data"><i class="fa fa-check"></i><b>9.1.2</b> Activity 2: Tidy the data</a></li>
<li class="chapter" data-level="9.1.3" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-3-calculate-mean-anxiety-for-each-student"><i class="fa fa-check"></i><b>9.1.3</b> Activity 3: Calculate mean anxiety for each student</a></li>
<li class="chapter" data-level="9.1.4" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-4-join-the-datasets-together"><i class="fa fa-check"></i><b>9.1.4</b> Activity 4: Join the datasets together</a></li>
<li class="chapter" data-level="9.1.5" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-5-calculate-descriptives-for-the-variables-overall"><i class="fa fa-check"></i><b>9.1.5</b> Activity 5: Calculate descriptives for the variables overall</a></li>
<li class="chapter" data-level="9.1.6" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-6-visualisations"><i class="fa fa-check"></i><b>9.1.6</b> Activity 6: Visualisations</a></li>
<li class="chapter" data-level="9.1.7" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-7-run-the-regression"><i class="fa fa-check"></i><b>9.1.7</b> Activity 7: Run the regression</a></li>
<li class="chapter" data-level="9.1.8" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-8-assumption-checking"><i class="fa fa-check"></i><b>9.1.8</b> Activity 8: Assumption checking</a></li>
<li class="chapter" data-level="9.1.9" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-9-power-and-effect-size-1"><i class="fa fa-check"></i><b>9.1.9</b> Activity 9: Power and effect size</a></li>
<li class="chapter" data-level="9.1.10" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-10-write-up-1"><i class="fa fa-check"></i><b>9.1.10</b> Activity 10: Write-up</a></li>
<li class="chapter" data-level="9.1.11" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-solutions-9"><i class="fa fa-check"></i><b>9.1.11</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="rm2-regression.html"><a href="rm2-regression.html#in-class-activities-6"><i class="fa fa-check"></i><b>9.2</b> In-class activities</a><ul>
<li class="chapter" data-level="9.2.1" data-path="rm2-regression.html"><a href="rm2-regression.html#screen-time-and-well-being"><i class="fa fa-check"></i><b>9.2.1</b> Screen time and well-being</a></li>
<li class="chapter" data-level="9.2.2" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-1-set-up-12"><i class="fa fa-check"></i><b>9.2.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="9.2.3" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-2-look-at-the-data-3"><i class="fa fa-check"></i><b>9.2.3</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="9.2.4" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-3-compute-the-well-being-score-for-each-respondent"><i class="fa fa-check"></i><b>9.2.4</b> Activity 3: Compute the well-being score for each respondent</a></li>
<li class="chapter" data-level="9.2.5" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-4-visualise-the-relationship"><i class="fa fa-check"></i><b>9.2.5</b> Activity 4: Visualise the relationship</a></li>
<li class="chapter" data-level="9.2.6" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-5-smartphone-and-well-being-for-boys-and-girls"><i class="fa fa-check"></i><b>9.2.6</b> Activity 5: Smartphone and well-being for boys and girls</a></li>
<li class="chapter" data-level="9.2.7" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-6-mean-centering-variables"><i class="fa fa-check"></i><b>9.2.7</b> Activity 6: Mean-centering variables</a></li>
<li class="chapter" data-level="9.2.8" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-7-visualise-the-relationship"><i class="fa fa-check"></i><b>9.2.8</b> Activity 7: Visualise the relationship</a></li>
<li class="chapter" data-level="9.2.9" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-8-running-the-regression"><i class="fa fa-check"></i><b>9.2.9</b> Activity 8: Running the regression</a></li>
<li class="chapter" data-level="9.2.10" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-9-assumption-checking"><i class="fa fa-check"></i><b>9.2.10</b> Activity 9: Assumption checking</a></li>
<li class="chapter" data-level="9.2.11" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-10-power-and-effect-size"><i class="fa fa-check"></i><b>9.2.11</b> Activity 10: Power and effect size</a></li>
<li class="chapter" data-level="9.2.12" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-11-write-up-1"><i class="fa fa-check"></i><b>9.2.12</b> Activity 11: Write-up</a></li>
<li class="chapter" data-level="9.2.13" data-path="rm2-regression.html"><a href="rm2-regression.html#finished-11"><i class="fa fa-check"></i><b>9.2.13</b> Finished!</a></li>
<li class="chapter" data-level="9.2.14" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-solutions-10"><i class="fa fa-check"></i><b>9.2.14</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html"><i class="fa fa-check"></i><b>10</b> Dissertation analysis guide</a><ul>
<li class="chapter" data-level="10.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#before-r"><i class="fa fa-check"></i><b>10.1</b> Before R</a><ul>
<li class="chapter" data-level="10.1.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#study-design"><i class="fa fa-check"></i><b>10.1.1</b> Study design</a></li>
<li class="chapter" data-level="10.1.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#data-wrangling-considerations"><i class="fa fa-check"></i><b>10.1.2</b> Data wrangling considerations</a></li>
<li class="chapter" data-level="10.1.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#data-analysis-1"><i class="fa fa-check"></i><b>10.1.3</b> Data analysis</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#exploring-and-cleaning-your-data"><i class="fa fa-check"></i><b>10.2</b> Exploring and cleaning your data</a><ul>
<li class="chapter" data-level="10.2.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#summary"><i class="fa fa-check"></i><b>10.2.1</b> <code>summary()</code></a></li>
<li class="chapter" data-level="10.2.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#visualisations"><i class="fa fa-check"></i><b>10.2.2</b> Visualisations</a></li>
<li class="chapter" data-level="10.2.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#renaming-variables"><i class="fa fa-check"></i><b>10.2.3</b> Renaming variables</a></li>
<li class="chapter" data-level="10.2.4" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#converting-to-factors"><i class="fa fa-check"></i><b>10.2.4</b> Converting to factors</a></li>
<li class="chapter" data-level="10.2.5" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#dropping-irrelevant-variables"><i class="fa fa-check"></i><b>10.2.5</b> Dropping irrelevant variables</a></li>
<li class="chapter" data-level="10.2.6" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#recoding-variables"><i class="fa fa-check"></i><b>10.2.6</b> Recoding variables</a></li>
<li class="chapter" data-level="10.2.7" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#exclude-participantsdata"><i class="fa fa-check"></i><b>10.2.7</b> Exclude participants/data</a></li>
<li class="chapter" data-level="10.2.8" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#reliability"><i class="fa fa-check"></i><b>10.2.8</b> Reliability</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#transforming-data"><i class="fa fa-check"></i><b>10.3</b> Transforming data</a><ul>
<li class="chapter" data-level="10.3.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#replace-missing-values"><i class="fa fa-check"></i><b>10.3.1</b> Replace missing values</a></li>
<li class="chapter" data-level="10.3.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#convert-implausible-values"><i class="fa fa-check"></i><b>10.3.2</b> Convert implausible values</a></li>
<li class="chapter" data-level="10.3.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#calculate-z-scores"><i class="fa fa-check"></i><b>10.3.3</b> Calculate z-scores</a></li>
<li class="chapter" data-level="10.3.4" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#log-transformation"><i class="fa fa-check"></i><b>10.3.4</b> Log transformation</a></li>
<li class="chapter" data-level="10.3.5" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#square-root"><i class="fa fa-check"></i><b>10.3.5</b> Square root</a></li>
<li class="chapter" data-level="10.3.6" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#calculating-new-variables"><i class="fa fa-check"></i><b>10.3.6</b> Calculating new variables</a></li>
<li class="chapter" data-level="10.3.7" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#tidy-data-1"><i class="fa fa-check"></i><b>10.3.7</b> Tidy data</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#summarising-and-visualising-data"><i class="fa fa-check"></i><b>10.4</b> Summarising and visualising data</a><ul>
<li class="chapter" data-level="10.4.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#descriptive-statistics"><i class="fa fa-check"></i><b>10.4.1</b> Descriptive statistics</a></li>
<li class="chapter" data-level="10.4.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#data-visualisation"><i class="fa fa-check"></i><b>10.4.2</b> Data visualisation</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#inferential-statistics"><i class="fa fa-check"></i><b>10.5</b> Inferential statistics</a></li>
<li class="chapter" data-level="10.6" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#assumption-tests"><i class="fa fa-check"></i><b>10.6</b> Assumption tests</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="refsup.html"><a href="refsup.html"><i class="fa fa-check"></i><b>11</b> Supplementary Analyses</a><ul>
<li class="chapter" data-level="11.1" data-path="refsup.html"><a href="refsup.html#data-transformation"><i class="fa fa-check"></i><b>11.1</b> Data transformation</a></li>
<li class="chapter" data-level="11.2" data-path="refsup.html"><a href="refsup.html#permutation-tests"><i class="fa fa-check"></i><b>11.2</b> Permutation tests</a><ul>
<li class="chapter" data-level="11.2.1" data-path="refsup.html"><a href="refsup.html#overview-1"><i class="fa fa-check"></i><b>11.2.1</b> Overview</a></li>
<li class="chapter" data-level="11.2.2" data-path="refsup.html"><a href="refsup.html#skill-1-generating-random-numbers"><i class="fa fa-check"></i><b>11.2.2</b> Skill 1: Generating Random Numbers</a></li>
<li class="chapter" data-level="11.2.3" data-path="refsup.html"><a href="refsup.html#skill-2-permuting-values"><i class="fa fa-check"></i><b>11.2.3</b> Skill 2: Permuting Values</a></li>
<li class="chapter" data-level="11.2.4" data-path="refsup.html"><a href="refsup.html#skill-3-creating-tibbles"><i class="fa fa-check"></i><b>11.2.4</b> Skill 3: Creating Tibbles</a></li>
<li class="chapter" data-level="11.2.5" data-path="refsup.html"><a href="refsup.html#skill-4-computing-differences-in-group-means"><i class="fa fa-check"></i><b>11.2.5</b> Skill 4: Computing Differences in Group Means</a></li>
<li class="chapter" data-level="11.2.6" data-path="refsup.html"><a href="refsup.html#skill-5-creating-your-own-functions"><i class="fa fa-check"></i><b>11.2.6</b> Skill 5: Creating Your Own Functions</a></li>
<li class="chapter" data-level="11.2.7" data-path="refsup.html"><a href="refsup.html#skill-6-replicating-operations"><i class="fa fa-check"></i><b>11.2.7</b> Skill 6: Replicating Operations</a></li>
<li class="chapter" data-level="11.2.8" data-path="refsup.html"><a href="refsup.html#permutation-tests-of-hypotheses"><i class="fa fa-check"></i><b>11.2.8</b> Permutation Tests of Hypotheses</a></li>
<li class="chapter" data-level="11.2.9" data-path="refsup.html"><a href="refsup.html#Ch5InClassQueT1"><i class="fa fa-check"></i><b>11.2.9</b> Step 1: Load in Add-on Packages and Data</a></li>
<li class="chapter" data-level="11.2.10" data-path="refsup.html"><a href="refsup.html#Ch5InClassQueT2"><i class="fa fa-check"></i><b>11.2.10</b> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></a></li>
<li class="chapter" data-level="11.2.11" data-path="refsup.html"><a href="refsup.html#Ch5InClassQueT3"><i class="fa fa-check"></i><b>11.2.11</b> Step 3: Permute the Group Labels</a></li>
<li class="chapter" data-level="11.2.12" data-path="refsup.html"><a href="refsup.html#Ch5InClassQueT4"><i class="fa fa-check"></i><b>11.2.12</b> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</a></li>
<li class="chapter" data-level="11.2.13" data-path="refsup.html"><a href="refsup.html#Ch5InClassQueT5"><i class="fa fa-check"></i><b>11.2.13</b> Step 5: Compare the Observed Mean Difference to the NHD</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="refsup.html"><a href="refsup.html#non-parametric-tests"><i class="fa fa-check"></i><b>11.3</b> Non-parametric tests</a></li>
<li class="chapter" data-level="11.4" data-path="refsup.html"><a href="refsup.html#simulation"><i class="fa fa-check"></i><b>11.4</b> Simulation</a></li>
<li class="chapter" data-level="11.5" data-path="refsup.html"><a href="refsup.html#rtweet"><i class="fa fa-check"></i><b>11.5</b> rtweet</a><ul>
<li class="chapter" data-level="11.5.1" data-path="refsup.html"><a href="refsup.html#packages-1"><i class="fa fa-check"></i><b>11.5.1</b> Packages</a></li>
<li class="chapter" data-level="11.5.2" data-path="refsup.html"><a href="refsup.html#hashtag-search"><i class="fa fa-check"></i><b>11.5.2</b> Hashtag search</a></li>
<li class="chapter" data-level="11.5.3" data-path="refsup.html"><a href="refsup.html#data-wrangling"><i class="fa fa-check"></i><b>11.5.3</b> Data wrangling</a></li>
<li class="chapter" data-level="11.5.4" data-path="refsup.html"><a href="refsup.html#time-series"><i class="fa fa-check"></i><b>11.5.4</b> Time series</a></li>
<li class="chapter" data-level="11.5.5" data-path="refsup.html"><a href="refsup.html#tidy-text-and-word-frequencies"><i class="fa fa-check"></i><b>11.5.5</b> Tidy text and word frequencies</a></li>
<li class="chapter" data-level="11.5.6" data-path="refsup.html"><a href="refsup.html#bigram-analysis"><i class="fa fa-check"></i><b>11.5.6</b> Bigram analysis</a></li>
<li class="chapter" data-level="11.5.7" data-path="refsup.html"><a href="refsup.html#sentiment-analysis"><i class="fa fa-check"></i><b>11.5.7</b> Sentiment analysis</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MSc Conversion in Psychological Studies/Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="rm1-data-wrangling" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> RM1 Data Wrangling</h1>
<div id="notes-for-instructors-3" class="section level2">
<h2><span class="header-section-number">3.1</span> Notes for instructors</h2>
<p>In this lab we move on from reading data in, joining tibbles and selecting variables of interest to becoming familiar with the Wickham 6 and the functionality of tidyverse. Practice is an important part of PsyTeachR so we ask students to repeat tasks across the semester in the pre-class, in-class and portfolio assessments. This principle is carried over into the student’s independent study practices. We encourage students to do prep independently but also to use the online help forums and to attend practice sessions where they can discuss and work on R in groups with GTAs present to guide and support if needed. This is an important part of our community building and creating a safe space to practice, make mistakes and develop skills.</p>
</div>
<div id="pre-class-activities" class="section level2">
<h2><span class="header-section-number">3.2</span> Pre-class activities</h2>
<div id="data-wrangling-and-the-tidyverse" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Data wrangling and the tidyverse</h3>
<p>Data comes in lots of different formats. One of the most common formats is that of a two-dimensional table (the two dimensions being rows and columns). Usually, each row stands for a separate observation (e.g. a subject), and each column stands for a different variable (e.g. a response, category, or group). A key benefit of tabular data is that it allows you to store different types of data-numerical measurements, alphanumeric labels, categorical descriptors-all in one place.</p>
<p>It may surprise you to learn that scientists actually spend far more of time cleaning and preparing their data than they spend actually analysing it. This means completing tasks such as cleaning up bad values, changing the structure of tables, merging information stored in separate tables, reducing the data down to a subset of observations, and producing data summaries. Some have estimated that up to 80% of time spent on data analysis involves such data preparation tasks (Dasu &amp; Johnson, 2003)!</p>
<p>Many people seem to operate under the assumption that the only option for data cleaning is the painstaking and time-consuming cutting and pasting of data within a spreadsheet program like Excel. We have witnessed students and colleagues waste days, weeks, and even months manually transforming their data in Excel, cutting, copying, and pasting data. Fixing up your data by hand is not only a terrible use of your time, but it is error-prone and not reproducible. Additionally, in this age where we can easily collect massive datasets online, you will not be able to organise, clean, and prepare these by hand.</p>
<p>In short, you will not thrive as a psychologist if you do not learn some key data wrangling skills. Although every dataset presents unique challenges, there are some systematic principles you should follow that will make your analyses easier, less error-prone, more efficient, and more reproducible.</p>
<p>In this lesson you will see how data science skills will allow you to efficiently get answers to nearly any question you might want to ask about your data. By learning how to properly make your computer do the hard and boring work for you, you can focus on the bigger issues.</p>
<div id="tidyverse" class="section level4">
<h4><span class="header-section-number">3.2.1.1</span> Tidyverse</h4>
<p>Tidyverse (<a href="https://www.tidyverse.org/" class="uri">https://www.tidyverse.org/</a>) is a collection of R packages created by world-famous data scientist Hadley Wickham.</p>
<p>Tidyverse contains six core packages: <code>dplyr</code>, <code>tidyr</code>, <code>readr</code>, <code>purrr</code>, <code>ggplot2</code>, and <code>tibble</code>. Last week when you typed <code>library(tidyverse)</code> into R, you will have seen that it loads in all of these packages in one go. Within these six core packages, you should be able to find everything you need to wrangle and visualise your data.</p>
<p>In this lab, we are going to focus on the <code>dplyr</code> package, which contains six important functions:</p>
<ul>
<li><code>select()</code> Include or exclude certain variables (columns)</li>
<li><code>filter()</code> Include or exclude certain observations (rows)</li>
<li><code>mutate()</code> Create new variables (columns)</li>
<li><code>arrange()</code> Change the order of observations (rows)</li>
<li><code>group_by()</code> Organize the observations into groups</li>
<li><code>summarise()</code> Derive aggregate variables for groups of observations</li>
</ul>
<p>These six functions are known as ’single table verbs’ because they only operate on one table at a time. Although the operations of these functions may seem very simplistic, it’s amazing what you can accomplish when you string them together: Hadley Wickham has claimed that 90% of data analysis can be reduced to the operations described by these six functions.</p>
</div>
</div>
<div id="the-babynames-database" class="section level3">
<h3><span class="header-section-number">3.2.2</span> The <code>babynames</code> database</h3>
<p>To demonstrate the power of the six <code>dplyr</code> verbs, we will use them to work with the babynames data from the <code>babynames</code> package. The babynames dataset has historical information about births of babies in the U.S.</p>
</div>
<div id="activity-1-set-up-1" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Activity 1: Set-up</h3>
<p>Do the following. If you need help, consult Chapter <a href="rm1-intro-to-r.html#ref2">2.2</a> and Chapter <a href="ref3.html#ref3">1</a>.</p>
<ul>
<li>Open R Studio and set the working directory to your Chapter 3 folder. Ensure the environment is clear.<br />
</li>
<li>Open a new R Markdown document and save it in your working directory. Call the file “Chapter 3 Pre-class”.<br />
</li>
<li>If you are working on your own computer, install the package <code>babynames</code>. Remember, <strong>never install packages if you are working on a university computer</strong>. The university computers will already have this package installed.<br />
</li>
<li>Delete the default R Markdown welcome text and insert a new code chunk that loads the packages <code>tidyverse</code> and <code>babynames</code> using <code>library()</code>.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(babynames)</code></pre>
</div>
<div id="activity-2-look-at-the-data" class="section level3">
<h3><span class="header-section-number">3.2.4</span> Activity 2: Look at the data</h3>
<p>The package <code>babynames</code> contains an object of the same name that contains all the data about babynames.</p>
<ul>
<li>View a preview of this dataset by typing <code>babynames</code> in to the console. You should see the following output:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">babynames</code></pre>
<pre><code>## # A tibble: 1,924,665 x 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724
##  2  1880 F     Anna       2604 0.0267
##  3  1880 F     Emma       2003 0.0205
##  4  1880 F     Elizabeth  1939 0.0199
##  5  1880 F     Minnie     1746 0.0179
##  6  1880 F     Margaret   1578 0.0162
##  7  1880 F     Ida        1472 0.0151
##  8  1880 F     Alice      1414 0.0145
##  9  1880 F     Bertha     1320 0.0135
## 10  1880 F     Sarah      1288 0.0132
## # ... with 1,924,655 more rows</code></pre>
<p>The first line tells us that the object we are looking at is in a <code>tibble</code> with information on five variables with over 1.9 million rows. Yes, this dataset contains 1.8 <strong>million</strong> observations. Interested in analyzing these data by hand? No thanks! A tibble is basically a table of data presenting a two dimensional array of your data.</p>
<p>Each row in the table represents data about births for a given name and sex in a given year. The variables are:</p>
<table>
<thead>
<tr class="header">
<th>variable</th>
<th>type</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>year</td>
<td>double (numeric)</td>
<td>year of birth</td>
</tr>
<tr class="even">
<td>sex</td>
<td>character</td>
<td>recorded sex of baby (F = female, M = male)</td>
</tr>
<tr class="odd">
<td>name</td>
<td>character</td>
<td>forename given to baby</td>
</tr>
<tr class="even">
<td>n</td>
<td>integer</td>
<td>number of babies given that name</td>
</tr>
<tr class="odd">
<td>prop</td>
<td>double (numeric)</td>
<td>proportion of all babies of that sex</td>
</tr>
</tbody>
</table>
<p>The first row of the table tells us that in the year 1880, there were 7065 baby girls born in the U.S. who were given the name Mary, and this accounted for about 7% of all baby girls.</p>
</div>
<div id="activity-3-your-first-plot" class="section level3">
<h3><span class="header-section-number">3.2.5</span> Activity 3: Your first plot</h3>
<ul>
<li>Type the code below into a new code chunk and run it.</li>
</ul>
<p>The code might not make much sense to you right now, but don’t worry about not understanding it yet! The point is show you how much you can accomplish with very little code. The code creates a graph showing the popularity of four girl baby names - Alexandra, Beverly, Emily, and Kathleen - from 1880 to 2014. You should see Figure <a href="rm1-data-wrangling.html#fig:babynames-plot">3.1</a> appear, which shows the proportion of each name across different years - you can plug in different names if you like and see how the plot changes.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span>babynames <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Emily&quot;</span>,<span class="st">&quot;Kathleen&quot;</span>,<span class="st">&quot;Alexandra&quot;</span>,<span class="st">&quot;Beverly&quot;</span>), sex<span class="op">==</span><span class="st">&quot;F&quot;</span>)

<span class="kw">ggplot</span>(<span class="dt">data =</span> dat,<span class="kw">aes</span>(<span class="dt">x =</span> year,<span class="dt">y =</span> prop, <span class="dt">colour=</span>name))<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>()  </code></pre>
<div class="figure" style="text-align: center"><span id="fig:babynames-plot"></span>
<img src="03-rm1-2_files/figure-html/babynames-plot-1.png" alt="Proportion of four baby names from 1880 to 2014" width="100%" />
<p class="caption">
Figure 3.1: Proportion of four baby names from 1880 to 2014
</p>
</div>
</div>
<div id="activity-4-selecting-variables-of-interest" class="section level3">
<h3><span class="header-section-number">3.2.6</span> Activity 4: Selecting variables of interest</h3>
<p>There are two numeric measurements of name popularity, <code>prop</code> (the proportion of all babies with each name) is probably more useful than <code>n</code> (total number of babies with that name), because it takes into account that different numbers of babies are born in different years.</p>
<p>Just like in Chapter <a href="rm1-intro-to-r.html#ref1">2.3.8</a>, if we wanted to create a dataset that only includes certain variables, we can use the <code>select()</code> function from the <code>dplyr</code> package. Run the below code to only select the columns <code>year</code>, <code>sex</code>, <code>name</code> and <code>prop</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(<span class="dt">.data =</span> babynames, <span class="co"># the object you want to select variables from</span>
       year, sex, name, prop) <span class="co"># the variables you want to select</span></code></pre>
<pre><code>## # A tibble: 1,924,665 x 4
##     year sex   name        prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1  1880 F     Mary      0.0724
##  2  1880 F     Anna      0.0267
##  3  1880 F     Emma      0.0205
##  4  1880 F     Elizabeth 0.0199
##  5  1880 F     Minnie    0.0179
##  6  1880 F     Margaret  0.0162
##  7  1880 F     Ida       0.0151
##  8  1880 F     Alice     0.0145
##  9  1880 F     Bertha    0.0135
## 10  1880 F     Sarah     0.0132
## # ... with 1,924,655 more rows</code></pre>
<p>Alternatively, you can also tell R which variables you don’t want, in this case, rather than telling R to select <code>year</code>, <code>sex</code>, <code>name</code> and <code>prop</code>, we can simply tell it to drop the column <code>n</code> using the minus sign <code>-</code> before the variable name.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(<span class="dt">.data =</span> babynames, <span class="op">-</span>n)</code></pre>
<pre><code>## # A tibble: 1,924,665 x 4
##     year sex   name        prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1  1880 F     Mary      0.0724
##  2  1880 F     Anna      0.0267
##  3  1880 F     Emma      0.0205
##  4  1880 F     Elizabeth 0.0199
##  5  1880 F     Minnie    0.0179
##  6  1880 F     Margaret  0.0162
##  7  1880 F     Ida       0.0151
##  8  1880 F     Alice     0.0145
##  9  1880 F     Bertha    0.0135
## 10  1880 F     Sarah     0.0132
## # ... with 1,924,655 more rows</code></pre>
<p>Note that <code>select()</code> does not change the original tibble, but makes a new tibble with the specified columns. If you don’t save this new tibble to an object, it won’t be saved. If you want to keep this new dataset, create a new object. When you run this code, you will see your new tibble appear in the environment pane.</p>
<pre class="sourceCode r"><code class="sourceCode r">new_dat &lt;-<span class="st"> </span><span class="kw">select</span>(<span class="dt">.data =</span> babynames, <span class="op">-</span>n)</code></pre>
</div>
<div id="activity-5-arranging-the-data" class="section level3">
<h3><span class="header-section-number">3.2.7</span> Activity 5: Arranging the data</h3>
<p>The function <code>arrange()</code> will sort the rows in the table according to the columns you supply. Try running the following code:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">arrange</span>(<span class="dt">.data =</span> babynames, <span class="co"># the data you want to sort</span>
        name) <span class="co"># the variable you want to sort by</span></code></pre>
<pre><code>## # A tibble: 1,924,665 x 5
##     year sex   name      n       prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt;      &lt;dbl&gt;
##  1  2007 M     Aaban     5 0.00000226
##  2  2009 M     Aaban     6 0.00000283
##  3  2010 M     Aaban     9 0.00000439
##  4  2011 M     Aaban    11 0.00000542
##  5  2012 M     Aaban    11 0.00000543
##  6  2013 M     Aaban    14 0.00000694
##  7  2014 M     Aaban    16 0.00000783
##  8  2015 M     Aaban    15 0.00000736
##  9  2016 M     Aaban     9 0.00000446
## 10  2017 M     Aaban    11 0.0000056 
## # ... with 1,924,655 more rows</code></pre>
<p>The data are now sorted in ascending alphabetical order by name. The default is to sort in ascending order. If you want it descending, wrap the name of the variable in the <code>desc()</code> function. For instance, to sort by year in descending order, run the following code:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">arrange</span>(babynames,<span class="kw">desc</span>(year)) </code></pre>
<pre><code>## # A tibble: 1,924,665 x 5
##     year sex   name          n    prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;   &lt;dbl&gt;
##  1  2017 F     Emma      19738 0.0105 
##  2  2017 F     Olivia    18632 0.00994
##  3  2017 F     Ava       15902 0.00848
##  4  2017 F     Isabella  15100 0.00805
##  5  2017 F     Sophia    14831 0.00791
##  6  2017 F     Mia       13437 0.00717
##  7  2017 F     Charlotte 12893 0.00688
##  8  2017 F     Amelia    11800 0.00629
##  9  2017 F     Evelyn    10675 0.00569
## 10  2017 F     Abigail   10551 0.00563
## # ... with 1,924,655 more rows</code></pre>
<p>You can also sort by more than one column. What do you think the following code will do?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">arrange</span>(babynames, <span class="kw">desc</span>(year), <span class="kw">desc</span>(sex), <span class="kw">desc</span>(prop)) </code></pre>
</div>
<div id="activity-6-using-filter-to-select-observations" class="section level3">
<h3><span class="header-section-number">3.2.8</span> Activity 6: Using filter to select observations</h3>
<p>We have previously used <code>select()</code> to select certain variables or columns, however, frequently you will also want to select only certain observations or rows, for example, only babies born after 1999, or only babies named “Mary”. You do this using the verb <code>filter()</code>. The <code>filter()</code> function is a bit more involved than the other verbs, and requires more detailed explanation, but this is because it is also extremely powerful.</p>
<p>Here is an example of filter, can you guess what it will do?</p>
<pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">filter</span>(<span class="dt">.data =</span> babynames, year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2000</span>)</code></pre>
<p>The first part of the code tells the function to use the object <code>babynames</code>. The second argument, <code>year &gt; 2000</code>, is what is known as a <strong>Boolean expression</strong>: an expression whose evaluation results in a value of TRUE or FALSE. What <code>filter()</code> does is include any observations (rows) for which the expression evaluates to TRUE, and exclude any for which it evaluates to FALSE. So in effect, behind the scenes, <code>filter()</code> goes through the entire set of 1.8 million observations, row by row, checking the value of year for each row, keeping it if the value is greater than 2000, and rejecting it if it is less than 2000. To see how a boolean expression works, consider the code below:</p>
<pre class="sourceCode r"><code class="sourceCode r">years &lt;-<span class="st"> </span><span class="dv">1996</span><span class="op">:</span><span class="dv">2005</span>
years
years <span class="op">&gt;</span><span class="st"> </span><span class="dv">2000</span></code></pre>
<pre><code>##  [1] 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005
##  [1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE</code></pre>
<p>You can see that the expression <code>years &gt; 2000</code> returns a <strong>logical vector</strong> (a vector of TRUE and FALSE values), where each element represents whether the expression is true or false for that element. For the first five elements (1996 to 2000) it is false, and for the last five elements (2001 to 2005) it is true.</p>
<p>Here are the most commonly used Boolean expressions.</p>
<table>
<thead>
<tr class="header">
<th>Operator</th>
<th>Name</th>
<th>is TRUE if and only if</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A &lt; B</td>
<td>less than</td>
<td>A is less than B</td>
</tr>
<tr class="even">
<td>A &lt;= B</td>
<td>less than or equal</td>
<td>A is less than or equal to B</td>
</tr>
<tr class="odd">
<td>A &gt; B</td>
<td>greater than</td>
<td>A is greater than B</td>
</tr>
<tr class="even">
<td>A &gt;= B</td>
<td>greater than or equal</td>
<td>A is greater than or equal to B</td>
</tr>
<tr class="odd">
<td>A == B</td>
<td>equivalence</td>
<td>A exactly equals B</td>
</tr>
<tr class="even">
<td>A != B</td>
<td>not equal</td>
<td>A does not exactly equal B</td>
</tr>
<tr class="odd">
<td>A %in% B</td>
<td>in</td>
<td>A is an element of vector B</td>
</tr>
</tbody>
</table>
<p>If you want only those observations for a specific name (e.g., Mary), you use the equivalence operator <code>==</code>. Note that you use double equal signs, not a single equal sign.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(babynames, name <span class="op">==</span><span class="st"> &quot;Mary&quot;</span>)</code></pre>
<pre><code>## # A tibble: 268 x 5
##     year sex   name      n     prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt;    &lt;dbl&gt;
##  1  1880 F     Mary   7065 0.0724  
##  2  1880 M     Mary     27 0.000228
##  3  1881 F     Mary   6919 0.0700  
##  4  1881 M     Mary     29 0.000268
##  5  1882 F     Mary   8148 0.0704  
##  6  1882 M     Mary     30 0.000246
##  7  1883 F     Mary   8012 0.0667  
##  8  1883 M     Mary     32 0.000284
##  9  1884 F     Mary   9217 0.0670  
## 10  1884 M     Mary     36 0.000293
## # ... with 258 more rows</code></pre>
<p>If you wanted all the names except Mary, you use the ‘not equals’ operator:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(babynames, name<span class="op">!=</span><span class="st">&quot;Mary&quot;</span>) </code></pre>
<pre><code>## # A tibble: 1,924,397 x 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1880 F     Anna       2604 0.0267
##  2  1880 F     Emma       2003 0.0205
##  3  1880 F     Elizabeth  1939 0.0199
##  4  1880 F     Minnie     1746 0.0179
##  5  1880 F     Margaret   1578 0.0162
##  6  1880 F     Ida        1472 0.0151
##  7  1880 F     Alice      1414 0.0145
##  8  1880 F     Bertha     1320 0.0135
##  9  1880 F     Sarah      1288 0.0132
## 10  1880 F     Annie      1258 0.0129
## # ... with 1,924,387 more rows</code></pre>
<p>And if you wanted names from a defined set - e.g., names of British queens - you can use <code>%in%</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(babynames, name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Mary&quot;</span>,<span class="st">&quot;Elizabeth&quot;</span>,<span class="st">&quot;Victoria&quot;</span>))</code></pre>
<pre><code>## # A tibble: 772 x 5
##     year sex   name          n      prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;     &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724   
##  2  1880 F     Elizabeth  1939 0.0199   
##  3  1880 F     Victoria     93 0.000953 
##  4  1880 M     Mary         27 0.000228 
##  5  1880 M     Elizabeth     9 0.0000760
##  6  1881 F     Mary       6919 0.0700   
##  7  1881 F     Elizabeth  1852 0.0187   
##  8  1881 F     Victoria    117 0.00118  
##  9  1881 M     Mary         29 0.000268 
## 10  1882 F     Mary       8148 0.0704   
## # ... with 762 more rows</code></pre>
<p>This gives you data for the names in the vector on the right hand side of <code>%in%</code>. You can always invert an expression to get its opposite. So, for instance, if you instead wanted to get rid of all Marys, Elizabeths, and Victorias you would use the following:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(babynames, <span class="op">!</span>(name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Mary&quot;</span>,<span class="st">&quot;Elizabeth&quot;</span>,<span class="st">&quot;Victoria&quot;</span>)))</code></pre>
<pre><code>## # A tibble: 1,923,893 x 5
##     year sex   name         n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
##  1  1880 F     Anna      2604 0.0267
##  2  1880 F     Emma      2003 0.0205
##  3  1880 F     Minnie    1746 0.0179
##  4  1880 F     Margaret  1578 0.0162
##  5  1880 F     Ida       1472 0.0151
##  6  1880 F     Alice     1414 0.0145
##  7  1880 F     Bertha    1320 0.0135
##  8  1880 F     Sarah     1288 0.0132
##  9  1880 F     Annie     1258 0.0129
## 10  1880 F     Clara     1226 0.0126
## # ... with 1,923,883 more rows</code></pre>
<p>You can include as many expressions as you like as additional arguments to <code>filter()</code> and it will only pull out the rows for which all of the expressions for that row evaluate to TRUE. For instance, <code>filter(babynames, year &gt; 2000, prop &gt; .01)</code> will pull out only those observations beyond the year 2000 that represent greater than 1% of the names for a given sex; any observation where either expression is false will be excluded. This ability to string together criteria makes <code>filter()</code> a very powerful member of the Wickham Six.</p>
<p><strong>Remember that this section exists. It will contain a lot of the answers to problems you face when wrangling data!</strong></p>
</div>
<div id="activity-7-creating-new-variables" class="section level3">
<h3><span class="header-section-number">3.2.9</span> Activity 7: Creating new variables</h3>
<p>Sometimes we need to create a new variable that doesn’t exist in our dataset. For instance, we might want to figure out what decade a particular year belongs to. To create new variables, we use the function <code>mutate()</code>. Note that if you want to save this new column, you need to save it to an object. Here, you are mutating a new column and attaching it to the <code>new_dat</code> object you created in Activity 4.</p>
<pre class="sourceCode r"><code class="sourceCode r">new_dat &lt;-<span class="st"> </span><span class="kw">mutate</span>(<span class="dt">.data =</span> babynames, <span class="co"># the tibble you want to add a colum to</span>
                  <span class="dt">decade =</span> <span class="kw">floor</span>(year<span class="op">/</span><span class="dv">10</span>) <span class="op">*</span><span class="dv">10</span>) <span class="co"># new column name = what you want it to contain</span>
new_dat</code></pre>
<pre><code>## # A tibble: 1,924,665 x 6
##     year sex   name          n   prop decade
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724   1880
##  2  1880 F     Anna       2604 0.0267   1880
##  3  1880 F     Emma       2003 0.0205   1880
##  4  1880 F     Elizabeth  1939 0.0199   1880
##  5  1880 F     Minnie     1746 0.0179   1880
##  6  1880 F     Margaret   1578 0.0162   1880
##  7  1880 F     Ida        1472 0.0151   1880
##  8  1880 F     Alice      1414 0.0145   1880
##  9  1880 F     Bertha     1320 0.0135   1880
## 10  1880 F     Sarah      1288 0.0132   1880
## # ... with 1,924,655 more rows</code></pre>
<p>In this case, you are creating a new column decade which has the decade each year appears in. This is calculated using the command <code>decade = floor(year/10)*10</code>.</p>
</div>
<div id="activity-8-grouping-and-summarising" class="section level3">
<h3><span class="header-section-number">3.2.10</span> Activity 8: Grouping and summarising</h3>
<p>Most quantitative analyses will require you to summarise your data somehow, for example, by calculating the mean, median or a sum total of your data. You can perform all of these operations using the function <code>summarise()</code>.</p>
<p>First, let’s use the object <code>dat</code> that just has the data for the four girls names, Alexandra, Beverly, Emily, and Kathleen. To start off, we’re simply going to calculate the total number of babies across all years that were given one of these four names.</p>
<p>It’s useful to get in the habit of translating your code into full sentences to make it easier to figure out what’s happening. You can read the below code as “run the function summarise using the data in the object <code>dat</code> to create a new variable named <code>total</code> that is the result of adding up all the numbers in the column <code>n</code>”.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(<span class="dt">.data =</span> dat, <span class="co"># the data you want to use</span>
          <span class="dt">total =</span> <span class="kw">sum</span>(n)) <span class="co"># result name = operation</span></code></pre>
<pre><code>## # A tibble: 1 x 1
##     total
##     &lt;int&gt;
## 1 2161374</code></pre>
<p><code>summarise()</code> becomes even more powerful when combined with the final <code>dplyr</code> function, <code>group_by()</code>. Quite often, you will want to produce your summary statistics broken down by groups, for examples, the scores of participants in different conditions, or the reading time for native and non-native speakers.</p>
<p>There are two ways you can use <code>group_by()</code>. First, you can create a new, grouped object.</p>
<pre class="sourceCode r"><code class="sourceCode r">group_dat &lt;-<span class="st"> </span><span class="kw">group_by</span>(<span class="dt">.data =</span> dat, <span class="co"># the data you want to group</span>
                      name) <span class="co"># the variable you want to group by</span></code></pre>
<p>If you look at this object in the viewer, it won’t look any different to the original <code>dat</code>, however, the underlying structure has changed. Let’s run the above summarise code again, but now using the grouped data.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(<span class="dt">.data =</span> group_dat, 
          <span class="dt">total =</span> <span class="kw">sum</span>(n)) </code></pre>
<pre><code>## # A tibble: 4 x 2
##   name       total
##   &lt;chr&gt;      &lt;int&gt;
## 1 Alexandra 231364
## 2 Beverly   376914
## 3 Emily     841491
## 4 Kathleen  711605</code></pre>
<p><code>summarise()</code> has performed exactly the same operation as before - adding up the total number in the column <code>n</code> - but this time it has done is separately for each group, which in this case was the variable <code>name</code>.</p>
<p>You can request multiple summary calculations to be performed in the same function. For example, the following code calculates the mean and median number of babies given each name every year.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(group_dat,
          <span class="dt">mean_year =</span> <span class="kw">mean</span>(n),
          <span class="dt">median_year =</span> <span class="kw">median</span>(n))</code></pre>
<pre><code>## # A tibble: 4 x 3
##   name      mean_year median_year
##   &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;
## 1 Alexandra     1977.        192 
## 2 Beverly       3089.        710.
## 3 Emily         6098.       1392.
## 4 Kathleen      5157.       3098</code></pre>
<p>You can also add multiple grouping variables. For example, the following code groups <code>new_dat</code> by <code>sex</code> and <code>decade</code> and then calculates the summary statistics to give us the mean and median number of male and female babies in each decade.</p>
<pre class="sourceCode r"><code class="sourceCode r">group_new_dat &lt;-<span class="st"> </span><span class="kw">group_by</span>(new_dat, sex, decade)
<span class="kw">summarise</span>(group_new_dat,
          <span class="dt">mean_year =</span> <span class="kw">mean</span>(n),
          <span class="dt">median_year =</span> <span class="kw">median</span>(n))</code></pre>
<pre><code>## # A tibble: 28 x 4
## # Groups:   sex [2]
##    sex   decade mean_year median_year
##    &lt;chr&gt;  &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
##  1 F       1880      111.          13
##  2 F       1890      128.          13
##  3 F       1900      131.          12
##  4 F       1910      187.          12
##  5 F       1920      211.          12
##  6 F       1930      214.          12
##  7 F       1940      262.          12
##  8 F       1950      288.          13
##  9 F       1960      235.          12
## 10 F       1970      147.          11
## # ... with 18 more rows</code></pre>
</div>
<div id="activity-9-pipes" class="section level3">
<h3><span class="header-section-number">3.2.11</span> Activity 9: Pipes</h3>
<p>The final activity for this pre-lab essentially repeats what we’ve already covered but in a slightly different way. In the previous activities, you created new objects with new variables or groupings and then you called <code>summarise()</code> on those new objects in separate lines of code. As a result, you had multiple objects in your environment pane and you need to make sure that you keep track of the different names.</p>
<p>Instead, you can use <strong>pipes</strong>. Pipes are written as <code>%&gt;%</code>and they should be read as “and then”. Pipes allow you to string together ‘sentences’ of code into ‘paragraphs’ so that you don’t need to create intermediary objects. Again, it is easier to show than tell.</p>
<p>The below code does <strong>exactly</strong> the same as all the code we wrote above but it only creates one object.</p>
<pre class="sourceCode r"><code class="sourceCode r">pipe_summary &lt;-<span class="st"> </span><span class="kw">mutate</span>(babynames, <span class="dt">decade =</span> <span class="kw">floor</span>(year<span class="op">/</span><span class="dv">10</span>) <span class="op">*</span><span class="dv">10</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Emily&quot;</span>,<span class="st">&quot;Kathleen&quot;</span>,<span class="st">&quot;Alexandra&quot;</span>,<span class="st">&quot;Beverly&quot;</span>), sex<span class="op">==</span><span class="st">&quot;F&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(name, decade) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_decade =</span> <span class="kw">mean</span>(n))</code></pre>
<p>The reason that this function is called a pipe is because it ‘pipes’ the data through to the next function. When you wrote the code previously, the first argument of each function was the dataset you wanted to work on. When you use pipes it will automatically take the data from the previous line of code so you don’t need to specify it again.</p>
<div class="try">
<p>
When learning to code it can be a useful practice to read your code ‘out loud’ in full sentences to help you understand what it is doing. You can read the code above as “create a new variable called decade AND THEN only keep the names Emily, Kathleen, Alexandra and Beverly that belong to female babies AND THEN group the dataset by name and decade AND THEN calculate the mean number of babies with each name per decade.” Try doing this each time you write a new bit of code.
</p>
</div>
<p>Some people find pipes a bit tricky to understand from a conceptual point of view, however, it’s well worth learning to use them as when your code starts getting longer they are much more efficient and mean you have to write less code which is always a good thing!</p>
</div>
</div>
<div id="in-class-activities" class="section level2">
<h2><span class="header-section-number">3.3</span> In-class activities</h2>
<div id="data-wrangling-a-key-skill" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Data-wrangling: A key skill</h3>
<p>One of the key skills in an researcher’s toolbox is the ability to work with data. When you run an experiment you get lots of data in various files. For instance, it is not uncommon for an experimental software to create a new file for every participant you run and for each participant’s file to contain numerous columns and rows of data, only some of which are important. Being able to wrangle that data, manipulate it into different layouts, extract the parts you need, and summarise it, is one of the most important skills we will help you learn.</p>
<p>Over this course you will develop your skills in working with data. This lab focuses on organizing data using the <code>tidyverse</code> package that you have read about in the pre-lab activities. Over the course, you will learn the main functions for data wrangling and how to use them, and we will use a number of different datasets to give you a wide range of exposure to what Psychology is about, and to reiterate that the same skills apply across different datasets. <strong>The skills don’t change, just the data!</strong></p>
<p>There are some questions to answer as you go along to test your skills: use the example code as a guide and the solutions are at the bottom. Remember to be pro-active in your learning, work together as a community, and if you get stuck use the <strong><a href="https://www.rstudio.com/resources/cheatsheets/">cheatsheets</a></strong>. The key cheatsheet for this activity is the Data Transformation with dplyr.</p>
</div>
<div id="learning-to-wrangle-is-there-a-chastity-belt-on-perception" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Learning to wrangle: Is there a chastity belt on perception</h3>
<p>Nearly all data in research methods is stored in two-dimensional tables, either called data-frames, tables or tibbles. There are other ways of storing data that you will discover in time but mainly we will be using tibbles (if you would like more info, type <code>vignette("tibble")</code> in the console). A tibble is really just a table of data with columns and rows of information. But within that table you can get different types of data, i.e. numeric, integer, and character.</p>
<table>
<colgroup>
<col width="17%" />
<col width="82%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Type of Data</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Numeric</td>
<td align="left">Numbers including decimals</td>
</tr>
<tr class="even">
<td align="left">Integer</td>
<td align="left">Numbers without decimals</td>
</tr>
<tr class="odd">
<td align="left">Character</td>
<td align="left">Tends to contain letters or be words</td>
</tr>
<tr class="even">
<td align="left">Factor</td>
<td align="left">Nominal (categorical). Can be words or numbers (e.g., male/1, female/2)</td>
</tr>
</tbody>
</table>
<p>Today we are going to be using data from this paper: <a href="http://journals.sagepub.com/doi/abs/10.1177/0956797617730892">Is there a Chastity Belt on Perception</a>. You can read the full paper if you like, but we will summarise the paper for you. The paper asks, <strong>does your ability to perform an action influence your perception?</strong> For instance, does your ability to hit a tennis ball influence how fast you perceive the ball to be moving? Or to phrase another way, do expert tennis players perceive the ball moving slower than novice tennis players? This experiment does not use tennis players however, they used the Pong task: “a computerised game in which participants aim to block moving balls with various sizes of paddles”. A bit like a very classic retro arcade game. Participants tend to estimate the balls as moving faster when they have to block it with a smaller paddle as opposed to when they have a bigger paddle. You can read the paper to get more details if you wish but hopefully that gives enough of an idea to help you understand the wrangling we will do on the data. We have cleaned up the data a little to start with. Let’s begin!</p>
</div>
<div id="activity-1-set-up-2" class="section level3">
<h3><span class="header-section-number">3.3.3</span> Activity 1: Set-up</h3>
<p>If you need help with any of these steps, you should refer to the pre-lab activities:</p>
<ul>
<li>Download <a href="PongBlueRedBack 1-16 Codebook.csv" download>PongBlueRedBack 1-16 Codebook.csv</a> into your Chapter 3 folder.<br />
</li>
<li>Set the working directory to your Chapter 3 folder. Ensure the environment is clear.<br />
</li>
<li>Open a new R Markdown document and save it in your working directory. Call the file “Chapter 3 In-class”.<br />
</li>
<li>Delete the default R Markdown welcome text and insert a new code chunk.</li>
<li>Copy and paste the below code into this code chunk and then run the code.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;tidyverse&quot;</span>)
pong_data &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;PongBlueRedBack 1-16 Codebook.csv&quot;</span>)
<span class="kw">summary</span>(pong_data)</code></pre>
<pre><code>##   Participant     JudgedSpeed      PaddleLength   BallSpeed  
##  Min.   : 1.00   Min.   :0.0000   Min.   : 50   Min.   :2.0  
##  1st Qu.: 4.75   1st Qu.:0.0000   1st Qu.: 50   1st Qu.:3.0  
##  Median : 8.50   Median :1.0000   Median :150   Median :4.5  
##  Mean   : 8.50   Mean   :0.5471   Mean   :150   Mean   :4.5  
##  3rd Qu.:12.25   3rd Qu.:1.0000   3rd Qu.:250   3rd Qu.:6.0  
##  Max.   :16.00   Max.   :1.0000   Max.   :250   Max.   :7.0  
##   TrialNumber     BackgroundColor      HitOrMiss       BlockNumber   
##  Min.   :  1.00   Length:4608        Min.   :0.0000   Min.   : 1.00  
##  1st Qu.: 72.75   Class :character   1st Qu.:0.0000   1st Qu.: 3.75  
##  Median :144.50   Mode  :character   Median :1.0000   Median : 6.50  
##  Mean   :144.50                      Mean   :0.6866   Mean   : 6.50  
##  3rd Qu.:216.25                      3rd Qu.:1.0000   3rd Qu.: 9.25  
##  Max.   :288.00                      Max.   :1.0000   Max.   :12.00</code></pre>
</div>
<div id="activity-2-look-at-your-data" class="section level3">
<h3><span class="header-section-number">3.3.4</span> Activity 2: Look at your data</h3>
<p>Let’s have a look at the <code>pong_data</code> and see how it is organized. Type <code>pong_data</code> in your console window.</p>
<p>In the dataset you will see that each row (observation) represents one trial per participant and that there were 288 trials for each of the 16 participants. The columns (variables) we have in the dataset are as follows:</p>
<table>
<thead>
<tr class="header">
<th align="center">Variable</th>
<th align="left">Type</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Participant</td>
<td align="left">integer</td>
<td align="left">participant number</td>
</tr>
<tr class="even">
<td align="center">JudgedSpeed</td>
<td align="left">integer</td>
<td align="left">speed judgement (1=fast, 0=slow)</td>
</tr>
<tr class="odd">
<td align="center">PaddleLength</td>
<td align="left">integer</td>
<td align="left">paddle length (pixels)</td>
</tr>
<tr class="even">
<td align="center">BallSpeed</td>
<td align="left">integer</td>
<td align="left">ball speed (2 pixels/4ms)</td>
</tr>
<tr class="odd">
<td align="center">TrialNumber</td>
<td align="left">integer</td>
<td align="left">trial number</td>
</tr>
<tr class="even">
<td align="center">BackgroundColor</td>
<td align="left">character</td>
<td align="left">background display colour</td>
</tr>
<tr class="odd">
<td align="center">HitOrMiss</td>
<td align="left">integer</td>
<td align="left">hit ball=1, missed ball=0</td>
</tr>
<tr class="even">
<td align="center">BlockNumber</td>
<td align="left">integer</td>
<td align="left">block number (out of 12 blocks)</td>
</tr>
</tbody>
</table>
<p>We will use this data to master our skills of the Wickham Six verbs, taking each verb in turn. You should refer to the explanations and example code in the pre-lab activities to help you complete these. There are <strong>6 verbs to work through</strong> and after that we will briefly recap on two other functions before finishing with a quick look at pipes. Try each activity and ask your peers or your tutor if you need help.</p>
</div>
<div id="activity-3-select" class="section level3">
<h3><span class="header-section-number">3.3.5</span> Activity 3: <strong><code>select()</code></strong></h3>
<p>Either by inclusion (telling R all the variables you want to keep) or exclusion (telling R which variables you want to drop), select only the <code>Participant</code>, <code>PaddleLength</code>, <code>TrialNumber</code>, <code>BackgroundColor</code> and <code>HitOrMiss</code> columns from <code>pong_data</code> and store it in a new object named <code>select_dat</code>.</p>
</div>
<div id="activity-4-reorder-the-variables" class="section level3">
<h3><span class="header-section-number">3.3.6</span> Activity 4: Reorder the variables</h3>
<p><code>select()</code> can also be used to reorder the columns in a table as the new table will display the variables in the order that you wrote them. Use <code>select()</code> to keep only the columns <code>Participant</code>, <code>JudgedSpeed</code>, <code>BallSpeed</code>, <code>TrialNumber</code>, and <code>HitOrMiss</code> but have them display in alphabetical order, left to right. Save this table in a new object named <code>reorder_dat</code>.</p>
</div>
<div id="activity-5-arrange-f" class="section level3">
<h3><span class="header-section-number">3.3.7</span> Activity 5: <strong><code>arrange()</code></strong> F</h3>
<p>Arrange the data by two variables: <code>HitOrMiss</code> (putting hits - 1 - first), and <code>JudgedSpeed</code> (fast judgement - 1 - first). Do not store this output in a new object.</p>
</div>
<div id="activity-6-filter" class="section level3">
<h3><span class="header-section-number">3.3.8</span> Activity 6: <code>filter()</code></h3>
<p>Use <code>filter()</code> to extract all Participants that had a fast speed judgement, for speeds 2, 4, 5, and 7, but missed the ball. Store this remaining data in a new object called <code>pong_fast_miss</code></p>
<div class="solution">
<button>
Helpful Hint
</button>
<p>There are three parts to this filter so it is best to think about them individually and then combine them.</p>
<ol style="list-style-type: decimal">
<li><p>Filter all fast speed judgements (<code>JudgedSpeed</code>)</p></li>
<li><p>Filter for the speeds 2, 4, 5 and 7 (<code>BallSpeed</code>)</p></li>
<li><p>Filter for all Misses (<code>HitOrMiss</code>)</p></li>
</ol>
<p>You could do this in three filters where each one uses the output of the preceding one, or remember that filter functions can take more than one argument. Also, because the <code>JudgedSpeed</code> and <code>HitOrMiss</code> are Integer you will need <code>==</code> instead of just <code>=</code>.</p>
</div>
<p><br></p>
<div class="warning">
<p>
The filter function is very useful but if used wrongly can give you very misleading findings. This is why it is very important to always check your data after you perform an action. Let’s say you are working in comparative psychology and have run a study looking at how cats, dogs and horses perceive emotion. Let’s say the data is all stored in the tibble <code>animal_data</code> and there is a column called <code>animals</code> that tells you what type of animal your participant was. Imagine you wanted all the data from just cats:
</p>
<p>
<code>filter(animal_data, animals == “cat”)</code>
</p>
<p>
Exactly! But what if you wanted cats and dogs?
</p>
<p>
<code>filter(animal_data, animals == “cat”, animals == “dog”)</code>
</p>
<p>
Right? Wrong! This actually says “give me everything that is a cat and a dog”. But nothing is a cat and a dog, that would be weird - like a dat or a cog. In fact you want everything that is either a cat <strong>or</strong> a dog, which is
</p>
<p>
filter(animal_data, animals == “cat” | animals == “dog”)`
</p>
<p>
The vertical line is the symbol for Or. So always pay attention to what you want and most importantly to what your code produces.
</p>
</div>
</div>
</div>
<div id="activity-7-mutate" class="section level3">
<h3><span class="header-section-number">3.3.9</span> Activity 7: <code>mutate()</code></h3>
<p>In the pre-lab, you learned how the <code>mutate()</code> function lets us create a new variable in our dataset. However, it also has another useful function in that it can be combined with <code>recode()</code> to create new columns with recoded values. For example, let’s add a new column to <code>pong_data</code> in which the background colour is converted into numeric form where <code>red</code> will become 1, and <code>blue</code> will become 2.</p>
<pre class="sourceCode r"><code class="sourceCode r">pong_data &lt;-<span class="st"> </span><span class="kw">mutate</span>(pong_data, 
                    <span class="dt">BackgroundColorNumeric =</span> <span class="kw">recode</span>(BackgroundColor, 
                                                    <span class="st">&quot;red&quot;</span> =<span class="st"> </span><span class="dv">1</span>, 
                                                    <span class="st">&quot;blue&quot;</span> =<span class="st"> </span><span class="dv">2</span>))</code></pre>
<p>The code here is is a bit complicated but:</p>
<ul>
<li><code>BackgroundColorNumeric</code> is the name of your new column,</li>
<li><code>BackgroundColor</code> is the name of the old column and the one to take information from</li>
<li>and 1 and 2 are the new codings of red and blue respectively</li>
<li>character strings like “red” and “blue” are in quotation marks, numbers are not</li>
</ul>
<p>The <code>mutate()</code> function is also handy for making some calculations on or across columns in your data. For example, say you realise you made a mistake in your experiment where your participant numbers should be 1 higher for every participant, i.e. Participant 1 should actually be numbered as Participant 2, etc. You would do something like:</p>
<pre class="sourceCode r"><code class="sourceCode r">pong_data &lt;-<span class="st"> </span><span class="kw">mutate</span>(pong_data, <span class="dt">Participant =</span> Participant <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)</code></pre>
<p>Note here that you are giving the new column the same name as the old column <code>Participant</code>. What happens here is that you are <strong>overwriting the old data with the new data</strong>! So watch out, mutate can create a new column or overwrite an existing column, depending on what you tell it to do!</p>
<p>Imagine you realise there is a mistake in your dataset and that all your trial numbers are wrong. The first trial (trial number 1) was a practice so should be excluded and your experiment actually started on trial 2.</p>
<ul>
<li>Filter out all trials with the number 1 (<code>TrialNumber</code> column) from <code>pong_data</code>,</li>
<li>Then use the <code>mutate()</code> function to recount all the remaining trial numbers, starting them at one again instead of two. Overwrite <code>TrialNumber</code> in <code>pong_data</code> with this new data.</li>
</ul>
<p>You can either do this in two separate steps and create a new object, or you can uses pipes <code>%&gt;%</code> and do it it one line of code.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<p>Step 1. filter(<code>TrialNumber</code> does not equal 1) - remember to store this output in a variable?</p>
<p>Step 2. mutate(<code>TrialNumber</code> = TrialNumber minus 1)</p>
</div>
</div>
<div id="activity-8-group_by" class="section level3">
<h3><span class="header-section-number">3.3.10</span> Activity 8: <code>group_by()</code></h3>
<ul>
<li>Group the data by <code>BlockNumber</code> and by <code>BackgroundColor</code>, in that order and save it in a new object named <code>pong_data_group</code>.</li>
<li>View this new object by typing <code>pong_data_group</code>into the console.</li>
</ul>
<p>Enter the number of groups (i.e. a number) you get as a result: <input class='solveme nospaces' size='2' data-answer='["24"]'/></p>
<div class="solution">
<button>
Helpful Hint
</button>
<p>It is the same procedure as this but with different column names:</p>
<p><code>group_by(pong_data, HitOrMiss, BackgroundColor)</code></p>
<p>The number of groups should be between the product of the number of background colours (red and blue) and the number of blocks (12).</p>
</div>
<p><br></p>
<p><code>group_by()</code> is incredibly useful as once the data is organised into groups you can then apply other functions (<code>filter</code>, <code>arrange</code>, <code>mutate</code>…etc.) to the groups within your data that you are interested in, instead of to the entire dataset. For instance, a common second step after <code>group_by</code> might be to <code>summarise</code> the data…</p>
</div>
<div id="activity-9-summarising-data" class="section level3">
<h3><span class="header-section-number">3.3.11</span> Activity 9: Summarising data</h3>
<p>The <code>summarise()</code> function lets you calculate descriptive statistics for your data. For example, say you want to know the number of hits there were for different paddle lengths, or number of hits there were when the background colour was red or blue.</p>
<p>We will do this using pipes, to get you used to using them. Remember to try and read the code out loud and to pronounce <code>%&gt;%</code> as ‘and then’. Copy and paste the below code into a new code chunk and run the code.</p>
<pre class="sourceCode r"><code class="sourceCode r">pong_data_hits&lt;-<span class="st"> </span><span class="kw">group_by</span>(pong_data, BackgroundColor, PaddleLength) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># first group the data</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">total_hits =</span> <span class="kw">sum</span>(HitOrMiss)) <span class="co"># and then create a new variable called total_hits</span></code></pre>
<p><code>summarise()</code> has a range of internal functions that make life really easy, e.g. <code>mean</code>, <code>sum</code>, <code>max</code>, <code>min</code>, etc. See the <a href="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">dplyr cheatsheet</a> for more examples.</p>
<ul>
<li>View <code>pong_data_hits</code> and enter the number of hits made with the small paddle (50) and the red colour background in this box: <input class='solveme nospaces' size='3' data-answer='["517"]'/></li>
</ul>
<p><strong>Note:</strong></p>
<ul>
<li><p>The name of the column within <code>pong_data_hits</code> is <code>total_hits</code>; this is what you called it in the above code. You could have called it anything you wanted but always try to use something sensible.</p></li>
<li><p>Make sure to call your variables something you (and anyone looking at your code) will understand and recognize later (i.e. not variable1, variable2, variable3. etc.), and avoid spaces (use_underscores_never_spaces).</p></li>
</ul>
<div class="try">
<p>
After grouping data together using the <code>group_by()</code> function and then performing a task on it, e.g. <code>filter()</code>, it can be very good practice to ungroup the data before performing another function. Forgetting to ungroup the dataset won’t always affect further processing, but can really mess up other things. Again just a good reminder to always check the data you are getting out of a function a) makes sense and b) is what you expect.
</p>
</div>
</div>
<div id="two-other-useful-functions" class="section level3">
<h3><span class="header-section-number">3.3.12</span> Two other useful functions</h3>
<p>The Wickham Six verbs let you to do a lot of things with data, however there are thousands of other functions at your disposal. If you want to do something with your data that you are not sure how to do using these functions, do a Google search for an alternative function - chances are someone else has had the same problem and has a help guide. For example, two other functions to note are the <code>bind_rows()</code> function and the <code>count()</code> functions.</p>
<p>The <code>bind_rows()</code> function is useful if you want to combine two tibbles together into one larger tibble that have the same column structure. For example:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># a tibble of ball speeds 1 and 2</span>
slow_ball&lt;-<span class="st"> </span><span class="kw">filter</span>(pong_data, BallSpeed <span class="op">&lt;</span><span class="st"> </span><span class="dv">3</span>) 

<span class="co"># a tibble of ball speeds 6 and 7</span>
fast_ball &lt;-<span class="st"> </span><span class="kw">filter</span>(pong_data, BallSpeed <span class="op">&gt;=</span><span class="st"> </span><span class="dv">6</span>) 

<span class="co"># a combined tibble of extreme ball speeds</span>
extreme_balls &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(slow_ball, fast_ball) </code></pre>
<p>Finally, the <code>count()</code> function is a shortcut that can sometimes be used to count up the number of rows you have for groups in your data, without having to use the <code>group_by()</code> and <code>summarise()</code> functions. For example, in Task 6 we combined <code>group_by()</code> and <code>summarise()</code> to calculate how many hits there were based on background colour and paddle length. Alternatively we could have done:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">count</span>(pong_data, BackgroundColor, PaddleLength, HitOrMiss)</code></pre>
<p>The results are the same, just that in the <code>count()</code> version we get all the information, including misses, because we are just counting rows. In the <code>summarise()</code> method we only got hits because that was the effect of what we summed. So two different methods give similar answers - coding can be individualised and get the same result!</p>
</div>
<div id="pipes" class="section level3">
<h3><span class="header-section-number">3.3.13</span> Pipes (<strong><code>%&gt;%</code></strong>)</h3>
<p>Finally, a quick recap on pipes. Here is an example of code that doesn’t use pipes to find how many hits there were with the large paddle length and the red background.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># First we group the data accordingly, storing it in `pong_data_group`</span>
pong_data_group &lt;-<span class="st"> </span><span class="kw">group_by</span>(pong_data, BackgroundColor, PaddleLength)

<span class="co"># And then we summarise it, storing the answer in `total_hits`</span>
pong_data_hits &lt;-<span class="st"> </span><span class="kw">summarise</span>(pong_data_group, <span class="dt">total_hits =</span> <span class="kw">sum</span>(HitOrMiss))

<span class="co"># And filter just the red, small paddle hits</span>
pong_data_hits_red_small &lt;-<span class="st"> </span><span class="kw">filter</span>(pong_data_hits, BackgroundColor <span class="op">==</span><span class="st"> &quot;red&quot;</span>, PaddleLength <span class="op">==</span><span class="st"> </span><span class="dv">250</span>)</code></pre>
<p>We can make our code even more efficient, using less code, by stringing our sequence of functions together using pipes. This would look like:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Same pipeline using pipes</span>
pong_data_hits_red_small &lt;-<span class="st"> </span>pong_data <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># take pong_data and then</span>
<span class="st">  </span><span class="kw">group_by</span>(BackgroundColor, PaddleLength) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># group by BackgroundColor and PaddleLength and then</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">total_hits =</span> <span class="kw">sum</span>(HitOrMiss)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># calculate the total number of hits and then</span>
<span class="st">  </span><span class="kw">filter</span>(BackgroundColor <span class="op">==</span><span class="st"> &quot;red&quot;</span>, PaddleLength <span class="op">==</span><span class="st"> </span><span class="dv">250</span>) <span class="co"># only keep the data for the red large paddle</span></code></pre>
<p>One last point on pipes is that they can be written in a single line of code but it’s much easier to see what the pipe is doing if each function takes its own line. Every time you add a function to the pipeline, remember to add a <code>%&gt;%</code> first and <strong>note that when using separate lines for each function, the <code>%&gt;%</code> must appear at the end of the line and not the start of the next line</strong>. Compare the two examples below. The first won’t work but the second will because the second puts the pipes at the end of the line where they need to be!</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Piped version that wont work </span>
data_arrange &lt;-<span class="st"> </span>pong_data 
                <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(PaddleLength <span class="op">==</span><span class="st"> &quot;50&quot;</span>)
                <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(BallSpeed) 

<span class="co"># Piped version that will work </span>
data_arrange &lt;-<span class="st"> </span>pong_data <span class="op">%&gt;%</span>
<span class="st">                </span><span class="kw">filter</span>(PaddleLength <span class="op">==</span><span class="st"> &quot;50&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">                </span><span class="kw">arrange</span>(BallSpeed) </code></pre>
<div class="try">
<p>
Where piping becomes most useful is when we <strong>string a series of functions together</strong>, rather than using them as separate steps and having to save the data each time under a new variable name and getting ourselves all confused. In the non-piped version we have to create a new variable each time, for example, <code>data</code>, <code>data_filtered</code>, <code>data_arranged</code>, <code>data_grouped</code>, <code>data_summarised</code> just to get to the final one we actually want, which was <code>data_summarised</code>. This creates a lot of variables and tibbles in our environment and can make everything unclear and eventually slow down our computer. The piped version however uses one variable name, saving space in the environment, and is clear and easy to read. With pipes we skip unnecessary steps and avoid cluttering our environment.
</p>
</div>
<div id="finished-2" class="section level4">
<h4><span class="header-section-number">3.3.13.1</span> Finished!</h4>
<p>We have now learned a number of functions and verbs that you will need as the semester goes on. You will use them in the lab next week so be sure to go over these and try them out to make yourself more comfortable with them. If you have any questions please post them on the Moodle forum or the slack forum. <strong>Happy Wrangling!</strong></p>
</div>
</div>
<div id="activity-solutions" class="section level3 tabset tabset-fade tabset-pills">
<h3><span class="header-section-number">3.3.14</span> Activity solutions</h3>
<p>Below you will find the solutions to the above questions. Only look at them after giving the questions a good try and speaking to the tutor about any issues.</p>
<div id="activity-3" class="section level4">
<h4><span class="header-section-number">3.3.14.1</span> Activity 3</h4>
<div class="solution">
<button>
Solution Task 3
</button>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># To include variables:</span>
select_dat &lt;-<span class="st"> </span><span class="kw">select</span>(pong_data, Participant, PaddleLength, TrialNumber, BackgroundColor, HitOrMiss)

<span class="co"># To exclude variables:</span>
select_dat &lt;-<span class="kw">select</span>(pong_data, <span class="op">-</span>JudgedSpeed, <span class="op">-</span>BallSpeed, <span class="op">-</span>BlockNumber)</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-4" class="section level4">
<h4><span class="header-section-number">3.3.14.2</span> Activity 4</h4>
<div class="solution">
<button>
Solution Activity 4
</button>
<pre class="sourceCode r"><code class="sourceCode r">reorder_dat &lt;-<span class="st"> </span><span class="kw">select</span>(pong_data, BallSpeed, HitOrMiss, JudgedSpeed, Participant, TrialNumber)</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-5" class="section level4">
<h4><span class="header-section-number">3.3.14.3</span> Activity 5</h4>
<div class="solution">
<button>
Solution Task 2
</button>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">arrange</span>(pong_data, <span class="kw">desc</span>(HitOrMiss), <span class="kw">desc</span>(JudgedSpeed))</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-6" class="section level4">
<h4><span class="header-section-number">3.3.14.4</span> Activity 6</h4>
<div class="solution">
<button>
Solution Activity 6
</button>
<pre class="sourceCode r"><code class="sourceCode r">pong_fast_miss<span class="op">&lt;</span><span class="st"> </span><span class="op">-</span><span class="st"> </span><span class="kw">filter</span>(pong_data, 
                         JudgedSpeed <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, 
                         BallSpeed <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;2&quot;</span>, <span class="st">&quot;4&quot;</span>, <span class="st">&quot;5&quot;</span>, <span class="st">&quot;7&quot;</span>), 
                         HitOrMiss <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-7" class="section level4">
<h4><span class="header-section-number">3.3.14.5</span> Activity 7</h4>
<div class="solution">
<button>
Solution Activity 7 4
</button>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># this is the solution if you used two separate steps</span>

pong_data_filt &lt;-<span class="st"> </span><span class="kw">filter</span>(pong_data, TrialNumber <span class="op">&gt;=</span><span class="st"> </span><span class="dv">2</span>) 
<span class="co"># you can call this variable anything, as long as it makes sense to yourself and others</span>

pong_data &lt;-<span class="st"> </span><span class="kw">mutate</span>(pong_data_filt, <span class="dt">TrialNumber =</span> TrialNumber <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)

<span class="co"># this is the solution if you used pipes</span>

pong_data&lt;-<span class="st"> </span><span class="kw">filter</span>(pong_data, TrialNumber <span class="op">&gt;=</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TrialNumber =</span> TrialNumber <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-8" class="section level4">
<h4><span class="header-section-number">3.3.14.6</span> Activity 8</h4>
<div class="solution">
<button>
Solution Task 5
</button>
<pre class="sourceCode r"><code class="sourceCode r">pong_data_group &lt;-<span class="st"> </span><span class="kw">group_by</span>(pong_data, BlockNumber, BackgroundColor)
pong_data_group</code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
<div id="activity-9" class="section level4">
<h4><span class="header-section-number">3.3.14.7</span> Activity 9</h4>
<div class="solution">
<button>
Solution Activity 9
</button>
<pre class="sourceCode r"><code class="sourceCode r">pong_data &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;PongBlueRedBack 1-16 Codebook.csv&quot;</span>)
pong_data_group &lt;-<span class="st"> </span><span class="kw">group_by</span>(pong_data, BackgroundColor, PaddleLength)
pong_data_hits &lt;-<span class="st"> </span><span class="kw">summarise</span>(pong_data_group, <span class="dt">total_hits =</span> <span class="kw">sum</span>(HitOrMiss))
<span class="co"># the answer should give 517</span></code></pre>
</div>
<p><strong>click the tab to see the solution</strong>
<br></p>
</div>
</div>
</div>
<div id="debugging-tips-2" class="section level2">
<h2><span class="header-section-number">3.4</span> Debugging tips</h2>
<ul>
<li>Make sure you have spelt the data file name <strong>exactly</strong> as it is shown. Spaces and everything. Do not change the name of the csv file, fix your code instead. If you have a different name for your file than someone else then your code is not reproducible.</li>
<li>Remember when uploading data we use <code>read_csv()</code> which has an underscore, whereas the data file itself will have a dot in its name, <code>filename.csv</code>.</li>
<li>Finally, check that the datafile is actually in the folder you have set as your working directory.</li>
</ul>
</div>
<div id="test-yourself-2" class="section level2">
<h2><span class="header-section-number">3.5</span> Test yourself</h2>
<ol style="list-style-type: decimal">
<li>What type of data would these most likely be:</li>
</ol>
<ul>
<li><p>Male = <select class='solveme' data-answer='["Character"]'> <option></option> <option>Character</option> <option>Numeric</option> <option>Integer</option></select></p></li>
<li><p>7.15 = <select class='solveme' data-answer='["Numeric"]'> <option></option> <option>Character</option> <option>Numeric</option> <option>Integer</option></select></p></li>
<li><p>137 = <select class='solveme' data-answer='["Integer"]'> <option></option> <option>Character</option> <option>Numeric</option> <option>Integer</option></select></p></li>
</ul>
<div class="solution">
<button>
Explain these answers
</button>
<p>There is a lot of different types of data and as well as different types of levels of measurements and it can get very confusing. It’s important to try to remember which is which because you can only do certain types of analyses on certain types of data and certain types of measurements. For instance, you can’t take the average of Characters just like you can’t take the average of Categorical data. Likewise, you can do any maths on Numeric data, just like you can on Interval and Ratio data. Integer data is funny in that sometimes it is Ordinal and sometimes it is Interval, sometimes you should take the median, sometimes you should take the mean. The main point is to always know what type of data you are using and to think about what you can and cannot do with them.</p>
</div>
<p><br></p>
<ol start="2" style="list-style-type: decimal">
<li><p>Which of the Wickham Six would you use to sort columns from smallest to largest: <select class='solveme' data-answer='["arrange"]'> <option></option> <option>select</option> <option>filter</option> <option>mutate</option> <option>arrange</option> <option>group_by</option> <option>summarise</option></select></p></li>
<li><p>Which of the Wickham Six would you use to calculate the mean of a column: <select class='solveme' data-answer='["summarise"]'> <option></option> <option>select</option> <option>filter</option> <option>mutate</option> <option>arrange</option> <option>group_by</option> <option>summarise</option></select></p></li>
<li><p>Which of the Wickham Six would you use to remove certain observations - e.g. remove all males: <select class='solveme' data-answer='["filter"]'> <option></option> <option>select</option> <option>filter</option> <option>mutate</option> <option>arrange</option> <option>group_by</option> <option>summarise</option></select></p></li>
<li><p>What does this line of code say? <code>data %&gt;% filter() %&gt;% group_by() %&gt;% summarise()</code>: <select class='solveme' data-answer='["take the data and then filter it and then group it and then summarise it"]'> <option></option> <option>take the data and then group it and then filter it and then summarise it</option> <option>take the data and then filter it and then group it and then summarise it</option> <option>take the data and then summarise it and then filter it and then group it</option> <option>take the data and then group it and then summarise it and then filter it</option></select></p></li>
</ol>

</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol){
    var tol = JSON.parse(this.dataset.tol);  
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("correct");
    } else {
      cl.remove("correct");
    }  
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("correct");
    }  
  }
  
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="rm1-intro-to-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="rm1-data-wrangling-chi-square.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
