<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Supplementary Analyses | MSc Conversion in Psychological Studies/Science</title>
  <meta name="description" content="This is the materials for the one-year MSc Conversion in Psychological Studies/Science." />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Supplementary Analyses | MSc Conversion in Psychological Studies/Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the materials for the one-year MSc Conversion in Psychological Studies/Science." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Supplementary Analyses | MSc Conversion in Psychological Studies/Science" />
  
  <meta name="twitter:description" content="This is the materials for the one-year MSc Conversion in Psychological Studies/Science." />
  



<meta name="date" content="2019-07-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="dissertation-analysis-guide.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include\psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSc Conversion in Psychological Studies/Science (face-to-face)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#notes-for-instructors"><i class="fa fa-check"></i><b>0.1</b> Notes for instructors</a><ul>
<li class="chapter" data-level="0.1.1" data-path="index.html"><a href="index.html#overview-of-msc-conversion-course"><i class="fa fa-check"></i><b>0.1.1</b> Overview of MSc Conversion course</a></li>
<li class="chapter" data-level="0.1.2" data-path="index.html"><a href="index.html#course-structure"><i class="fa fa-check"></i><b>0.1.2</b> Course structure</a></li>
<li class="chapter" data-level="0.1.3" data-path="index.html"><a href="index.html#teaching-open-and-reproducible-science"><i class="fa fa-check"></i><b>0.1.3</b> Teaching open and reproducible science</a></li>
<li class="chapter" data-level="0.1.4" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>0.1.4</b> Assessment</a></li>
<li class="chapter" data-level="0.1.5" data-path="index.html"><a href="index.html#contact-details"><i class="fa fa-check"></i><b>0.1.5</b> Contact details</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#student-overview"><i class="fa fa-check"></i><b>0.2</b> Student overview</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i><b>0.3</b> How to use this book</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#data-files"><i class="fa fa-check"></i><b>0.4</b> Data files</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#intended-learning-outcomes"><i class="fa fa-check"></i><b>0.5</b> Intended Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ref3.html"><a href="ref3.html"><i class="fa fa-check"></i><b>1</b> Programming Basics</a><ul>
<li class="chapter" data-level="1.1" data-path="ref3.html"><a href="ref3.html#notes-for-instructors-1"><i class="fa fa-check"></i><b>1.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="1.2" data-path="ref3.html"><a href="ref3.html#introduction"><i class="fa fa-check"></i><b>1.2</b> Introduction</a></li>
<li class="chapter" data-level="1.3" data-path="ref3.html"><a href="ref3.html#r-and-r-studio"><i class="fa fa-check"></i><b>1.3</b> R and R Studio</a><ul>
<li class="chapter" data-level="1.3.1" data-path="ref3.html"><a href="ref3.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>1.3.1</b> Getting to know R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="ref3.html"><a href="ref3.html#functions-and-arguments"><i class="fa fa-check"></i><b>1.4</b> Functions and arguments</a><ul>
<li class="chapter" data-level="1.4.1" data-path="ref3.html"><a href="ref3.html#argument-names"><i class="fa fa-check"></i><b>1.4.1</b> Argument names</a></li>
<li class="chapter" data-level="1.4.2" data-path="ref3.html"><a href="ref3.html#tab-auto-complete"><i class="fa fa-check"></i><b>1.4.2</b> Tab auto-complete</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="ref3.html"><a href="ref3.html#packages"><i class="fa fa-check"></i><b>1.5</b> Base R and packages</a><ul>
<li class="chapter" data-level="1.5.1" data-path="ref3.html"><a href="ref3.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>1.5.1</b> Installing and loading packages</a></li>
<li class="chapter" data-level="1.5.2" data-path="ref3.html"><a href="ref3.html#package-updates"><i class="fa fa-check"></i><b>1.5.2</b> Package updates</a></li>
<li class="chapter" data-level="1.5.3" data-path="ref3.html"><a href="ref3.html#conflicts"><i class="fa fa-check"></i><b>1.5.3</b> Package conflicts</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="ref3.html"><a href="ref3.html#objects"><i class="fa fa-check"></i><b>1.6</b> Objects</a></li>
<li class="chapter" data-level="1.7" data-path="ref3.html"><a href="ref3.html#looking-after-the-environment"><i class="fa fa-check"></i><b>1.7</b> Looking after the environment</a></li>
<li class="chapter" data-level="1.8" data-path="ref3.html"><a href="ref3.html#r-sessions"><i class="fa fa-check"></i><b>1.8</b> R sessions</a></li>
<li class="chapter" data-level="1.9" data-path="ref3.html"><a href="ref3.html#help-and-additional-resources"><i class="fa fa-check"></i><b>1.9</b> Help and additional resources</a></li>
<li class="chapter" data-level="1.10" data-path="ref3.html"><a href="ref3.html#debugging-tips"><i class="fa fa-check"></i><b>1.10</b> Debugging tips</a></li>
<li class="chapter" data-level="1.11" data-path="ref3.html"><a href="ref3.html#test-yourself"><i class="fa fa-check"></i><b>1.11</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html"><i class="fa fa-check"></i><b>2</b> RM1 Intro to R</a><ul>
<li class="chapter" data-level="2.1" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#notes-for-instructors-2"><i class="fa fa-check"></i><b>2.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="2.2" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#ref2"><i class="fa fa-check"></i><b>2.2</b> Pre-class activities</a><ul>
<li class="chapter" data-level="2.2.1" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-1-programming-basics"><i class="fa fa-check"></i><b>2.2.1</b> Activity 1: Programming basics</a></li>
<li class="chapter" data-level="2.2.2" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-2-create-the-working-directory"><i class="fa fa-check"></i><b>2.2.2</b> Activity 2: Create the working directory</a></li>
<li class="chapter" data-level="2.2.3" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-3-set-the-working-directory"><i class="fa fa-check"></i><b>2.2.3</b> Activity 3: Set the working directory</a></li>
<li class="chapter" data-level="2.2.4" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#r-markdown-for-r-book-work-and-portfolio-assignments"><i class="fa fa-check"></i><b>2.2.4</b> R Markdown for R book work and portfolio assignments</a></li>
<li class="chapter" data-level="2.2.5" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-4-open-and-save-a-new-r-markdown-document"><i class="fa fa-check"></i><b>2.2.5</b> Activity 4: Open and save a new R Markdown document</a></li>
<li class="chapter" data-level="2.2.6" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-5-create-a-new-code-chunk"><i class="fa fa-check"></i><b>2.2.6</b> Activity 5: Create a new code chunk</a></li>
<li class="chapter" data-level="2.2.7" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-6-write-some-code"><i class="fa fa-check"></i><b>2.2.7</b> Activity 6: Write some code</a></li>
<li class="chapter" data-level="2.2.8" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#running-code"><i class="fa fa-check"></i><b>2.2.8</b> Running code</a></li>
<li class="chapter" data-level="2.2.9" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-7-run-your-code"><i class="fa fa-check"></i><b>2.2.9</b> Activity 7: Run your code</a></li>
<li class="chapter" data-level="2.2.10" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-8-inline-code"><i class="fa fa-check"></i><b>2.2.10</b> Activity 8: Inline code</a></li>
<li class="chapter" data-level="2.2.11" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-9-knitting-your-file"><i class="fa fa-check"></i><b>2.2.11</b> Activity 9: Knitting your file</a></li>
<li class="chapter" data-level="2.2.12" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#finished"><i class="fa fa-check"></i><b>2.2.12</b> Finished</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#lab1-inclass"><i class="fa fa-check"></i><b>2.3</b> In-class activities</a><ul>
<li class="chapter" data-level="2.3.1" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#getting-data-ready-to-work-with"><i class="fa fa-check"></i><b>2.3.1</b> Getting data ready to work with</a></li>
<li class="chapter" data-level="2.3.2" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-1-set-up"><i class="fa fa-check"></i><b>2.3.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="2.3.3" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-2-load-in-the-package"><i class="fa fa-check"></i><b>2.3.3</b> Activity 2: Load in the package</a></li>
<li class="chapter" data-level="2.3.4" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#open-data"><i class="fa fa-check"></i><b>2.3.4</b> Open data</a></li>
<li class="chapter" data-level="2.3.5" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-3-read-in-data"><i class="fa fa-check"></i><b>2.3.5</b> Activity 3: Read in data</a></li>
<li class="chapter" data-level="2.3.6" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-4-check-yo-data"><i class="fa fa-check"></i><b>2.3.6</b> Activity 4: Check yo’ data</a></li>
<li class="chapter" data-level="2.3.7" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#activity-5-join-the-files-together"><i class="fa fa-check"></i><b>2.3.7</b> Activity 5: Join the files together</a></li>
<li class="chapter" data-level="2.3.8" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#ref1"><i class="fa fa-check"></i><b>2.3.8</b> Activity 6: Pull out variables of interest</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#debugging-tips-1"><i class="fa fa-check"></i><b>2.4</b> Debugging tips</a></li>
<li class="chapter" data-level="2.5" data-path="rm1-intro-to-r.html"><a href="rm1-intro-to-r.html#test-yourself-1"><i class="fa fa-check"></i><b>2.5</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html"><i class="fa fa-check"></i><b>3</b> RM1 Data Wrangling</a><ul>
<li class="chapter" data-level="3.1" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#notes-for-instructors-3"><i class="fa fa-check"></i><b>3.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="3.2" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#pre-class-activities"><i class="fa fa-check"></i><b>3.2</b> Pre-class activities</a><ul>
<li class="chapter" data-level="3.2.1" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#data-wrangling-and-the-tidyverse"><i class="fa fa-check"></i><b>3.2.1</b> Data wrangling and the tidyverse</a></li>
<li class="chapter" data-level="3.2.2" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#the-babynames-database"><i class="fa fa-check"></i><b>3.2.2</b> The <code>babynames</code> database</a></li>
<li class="chapter" data-level="3.2.3" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-1-set-up-1"><i class="fa fa-check"></i><b>3.2.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="3.2.4" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-2-look-at-the-data"><i class="fa fa-check"></i><b>3.2.4</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="3.2.5" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-3-your-first-plot"><i class="fa fa-check"></i><b>3.2.5</b> Activity 3: Your first plot</a></li>
<li class="chapter" data-level="3.2.6" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-4-selecting-variables-of-interest"><i class="fa fa-check"></i><b>3.2.6</b> Activity 4: Selecting variables of interest</a></li>
<li class="chapter" data-level="3.2.7" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-5-arranging-the-data"><i class="fa fa-check"></i><b>3.2.7</b> Activity 5: Arranging the data</a></li>
<li class="chapter" data-level="3.2.8" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-6-using-filter-to-select-observations"><i class="fa fa-check"></i><b>3.2.8</b> Activity 6: Using filter to select observations</a></li>
<li class="chapter" data-level="3.2.9" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-7-creating-new-variables"><i class="fa fa-check"></i><b>3.2.9</b> Activity 7: Creating new variables</a></li>
<li class="chapter" data-level="3.2.10" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-8-grouping-and-summarising"><i class="fa fa-check"></i><b>3.2.10</b> Activity 8: Grouping and summarising</a></li>
<li class="chapter" data-level="3.2.11" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-9-pipes"><i class="fa fa-check"></i><b>3.2.11</b> Activity 9: Pipes</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#in-class-activities"><i class="fa fa-check"></i><b>3.3</b> In-class activities</a><ul>
<li class="chapter" data-level="3.3.1" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#data-wrangling-a-key-skill"><i class="fa fa-check"></i><b>3.3.1</b> Data-wrangling: A key skill</a></li>
<li class="chapter" data-level="3.3.2" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#learning-to-wrangle-is-there-a-chastity-belt-on-perception"><i class="fa fa-check"></i><b>3.3.2</b> Learning to wrangle: Is there a chastity belt on perception</a></li>
<li class="chapter" data-level="3.3.3" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-1-set-up-2"><i class="fa fa-check"></i><b>3.3.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="3.3.4" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-2-look-at-your-data"><i class="fa fa-check"></i><b>3.3.4</b> Activity 2: Look at your data</a></li>
<li class="chapter" data-level="3.3.5" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-3-select"><i class="fa fa-check"></i><b>3.3.5</b> Activity 3: <strong><code>select()</code></strong></a></li>
<li class="chapter" data-level="3.3.6" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-4-reorder-the-variables"><i class="fa fa-check"></i><b>3.3.6</b> Activity 4: Reorder the variables</a></li>
<li class="chapter" data-level="3.3.7" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-5-arrange-f"><i class="fa fa-check"></i><b>3.3.7</b> Activity 5: <strong><code>arrange()</code></strong> F</a></li>
<li class="chapter" data-level="3.3.8" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-6-filter"><i class="fa fa-check"></i><b>3.3.8</b> Activity 6: <code>filter()</code></a></li>
<li class="chapter" data-level="3.3.9" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-7-mutate"><i class="fa fa-check"></i><b>3.3.9</b> Activity 7: <code>mutate()</code></a></li>
<li class="chapter" data-level="3.3.10" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-8-group_by"><i class="fa fa-check"></i><b>3.3.10</b> Activity 8: <code>group_by()</code></a></li>
<li class="chapter" data-level="3.3.11" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-9-summarising-data"><i class="fa fa-check"></i><b>3.3.11</b> Activity 9: Summarising data</a></li>
<li class="chapter" data-level="3.3.12" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#two-other-useful-functions"><i class="fa fa-check"></i><b>3.3.12</b> Two other useful functions</a></li>
<li class="chapter" data-level="3.3.13" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#pipes"><i class="fa fa-check"></i><b>3.3.13</b> Pipes (<strong><code>%&gt;%</code></strong>)</a></li>
<li class="chapter" data-level="3.3.14" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#activity-solutions"><i class="fa fa-check"></i><b>3.3.14</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#debugging-tips-2"><i class="fa fa-check"></i><b>3.4</b> Debugging tips</a></li>
<li class="chapter" data-level="3.5" data-path="rm1-data-wrangling.html"><a href="rm1-data-wrangling.html#test-yourself-2"><i class="fa fa-check"></i><b>3.5</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html"><i class="fa fa-check"></i><b>4</b> RM1 Data Wrangling &amp; Chi-Square</a><ul>
<li class="chapter" data-level="4.1" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#notes-for-instructors-4"><i class="fa fa-check"></i><b>4.1</b> Notes for instructors</a></li>
<li class="chapter" data-level="4.2" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#pre-lab-activities"><i class="fa fa-check"></i><b>4.2</b> Pre-lab activities</a><ul>
<li class="chapter" data-level="4.2.1" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#data-wrangling-recap"><i class="fa fa-check"></i><b>4.2.1</b> Data wrangling recap</a></li>
<li class="chapter" data-level="4.2.2" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#tidy-data"><i class="fa fa-check"></i><b>4.2.2</b> Tidy data</a></li>
<li class="chapter" data-level="4.2.3" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#analysing-the-autism-spectrum-quotient-aq"><i class="fa fa-check"></i><b>4.2.3</b> Analysing the Autism Spectrum Quotient (AQ)</a></li>
<li class="chapter" data-level="4.2.4" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-1-set-up-3"><i class="fa fa-check"></i><b>4.2.4</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="4.2.5" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-2-load-in-the-data"><i class="fa fa-check"></i><b>4.2.5</b> Activity 2: Load in the data</a></li>
<li class="chapter" data-level="4.2.6" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-3-look-at-your-data"><i class="fa fa-check"></i><b>4.2.6</b> Activity 3: Look at your data</a></li>
<li class="chapter" data-level="4.2.7" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#gather"><i class="fa fa-check"></i><b>4.2.7</b> Activity 4: Gathering data</a></li>
<li class="chapter" data-level="4.2.8" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#join"><i class="fa fa-check"></i><b>4.2.8</b> Activity 5: Combining data</a></li>
<li class="chapter" data-level="4.2.9" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-6-combining-more-data"><i class="fa fa-check"></i><b>4.2.9</b> Activity 6: Combining more data</a></li>
<li class="chapter" data-level="4.2.10" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-7-calculating-the-aq-scores."><i class="fa fa-check"></i><b>4.2.10</b> Activity 7: Calculating the AQ scores.</a></li>
<li class="chapter" data-level="4.2.11" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-8-one-last-thing-on-pipes"><i class="fa fa-check"></i><b>4.2.11</b> Activity 8: One last thing on pipes</a></li>
<li class="chapter" data-level="4.2.12" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-solutions-1"><i class="fa fa-check"></i><b>4.2.12</b> Activity solutions</a></li>
<li class="chapter" data-level="4.2.13" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#test-yourself-3"><i class="fa fa-check"></i><b>4.2.13</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#in-class-activities-1"><i class="fa fa-check"></i><b>4.3</b> In-class activities</a><ul>
<li class="chapter" data-level="4.3.1" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#data-analysis"><i class="fa fa-check"></i><b>4.3.1</b> Data analysis</a></li>
<li class="chapter" data-level="4.3.2" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#reminders-through-association"><i class="fa fa-check"></i><b>4.3.2</b> Reminders through association</a></li>
<li class="chapter" data-level="4.3.3" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-1-set-up-4"><i class="fa fa-check"></i><b>4.3.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="4.3.4" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-2-look-at-the-data-1"><i class="fa fa-check"></i><b>4.3.4</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="4.3.5" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-3-wrangle-and-recode-the-data"><i class="fa fa-check"></i><b>4.3.5</b> Activity 3: Wrangle and recode the data</a></li>
<li class="chapter" data-level="4.3.6" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-4-descriptive-statistics"><i class="fa fa-check"></i><b>4.3.6</b> Activity 4: Descriptive statistics</a></li>
<li class="chapter" data-level="4.3.7" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#ggplot2"><i class="fa fa-check"></i><b>4.3.7</b> <code>ggplot2()</code></a></li>
<li class="chapter" data-level="4.3.8" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#bar"><i class="fa fa-check"></i><b>4.3.8</b> Activity 5: Bar plot</a></li>
<li class="chapter" data-level="4.3.9" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-6-make-the-plot-pretty"><i class="fa fa-check"></i><b>4.3.9</b> Activity 6: Make the plot pretty</a></li>
<li class="chapter" data-level="4.3.10" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-7-chi-square"><i class="fa fa-check"></i><b>4.3.10</b> Activity 7: Chi-square</a></li>
<li class="chapter" data-level="4.3.11" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-8-additional-analysis-information"><i class="fa fa-check"></i><b>4.3.11</b> Activity 8: Additional analysis information</a></li>
<li class="chapter" data-level="4.3.12" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#assumption-checks"><i class="fa fa-check"></i><b>4.3.12</b> Assumption checks</a></li>
<li class="chapter" data-level="4.3.13" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-9-check-the-expected-frequencies"><i class="fa fa-check"></i><b>4.3.13</b> Activity 9: Check the expected frequencies</a></li>
<li class="chapter" data-level="4.3.14" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#cramer"><i class="fa fa-check"></i><b>4.3.14</b> Activity 10: Effect size</a></li>
<li class="chapter" data-level="4.3.15" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-11-write-up"><i class="fa fa-check"></i><b>4.3.15</b> Activity 11: Write-up</a></li>
<li class="chapter" data-level="4.3.16" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#activity-solutions-2"><i class="fa fa-check"></i><b>4.3.16</b> Activity solutions</a></li>
<li class="chapter" data-level="4.3.17" data-path="rm1-data-wrangling-chi-square.html"><a href="rm1-data-wrangling-chi-square.html#test-yourself-4"><i class="fa fa-check"></i><b>4.3.17</b> Test yourself</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html"><i class="fa fa-check"></i><b>5</b> RM2 R Markdown &amp; Correlations</a><ul>
<li class="chapter" data-level="5.1" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#pre-class-activities-1"><i class="fa fa-check"></i><b>5.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="5.1.1" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-1-revise"><i class="fa fa-check"></i><b>5.1.1</b> Activity 1: Revise</a></li>
<li class="chapter" data-level="5.1.2" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#r-markdown"><i class="fa fa-check"></i><b>5.1.2</b> R Markdown</a></li>
<li class="chapter" data-level="5.1.3" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#advantages-of-using-r-markdown"><i class="fa fa-check"></i><b>5.1.3</b> Advantages of using R Markdown</a></li>
<li class="chapter" data-level="5.1.4" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-2-create-a-new-markdown-document"><i class="fa fa-check"></i><b>5.1.4</b> Activity 2: Create a new Markdown document</a></li>
<li class="chapter" data-level="5.1.5" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-3-setting-up-the-new-markdown-document"><i class="fa fa-check"></i><b>5.1.5</b> Activity 3: Setting up the new Markdown document</a></li>
<li class="chapter" data-level="5.1.6" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-4-new-code-chunks"><i class="fa fa-check"></i><b>5.1.6</b> Activity 4: New code chunks</a></li>
<li class="chapter" data-level="5.1.7" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-5-knit-your-code"><i class="fa fa-check"></i><b>5.1.7</b> Activity 5: Knit your code</a></li>
<li class="chapter" data-level="5.1.8" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-6-adding-rules-to-code-chunks"><i class="fa fa-check"></i><b>5.1.8</b> Activity 6: Adding rules to code chunks</a></li>
<li class="chapter" data-level="5.1.9" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-7-formatting-the-r-markdown-file"><i class="fa fa-check"></i><b>5.1.9</b> Activity 7: Formatting the R Markdown File</a></li>
<li class="chapter" data-level="5.1.10" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#test-yourself-5"><i class="fa fa-check"></i><b>5.1.10</b> Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#in-class-activities-2"><i class="fa fa-check"></i><b>5.2</b> In-class activities</a><ul>
<li class="chapter" data-level="5.2.1" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#correlations"><i class="fa fa-check"></i><b>5.2.1</b> Correlations</a></li>
<li class="chapter" data-level="5.2.2" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-1-set-up-5"><i class="fa fa-check"></i><b>5.2.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="5.2.3" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-2-look-at-your-data-1"><i class="fa fa-check"></i><b>5.2.3</b> Activity 2: Look at your data</a></li>
<li class="chapter" data-level="5.2.4" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-3-assumptions"><i class="fa fa-check"></i><b>5.2.4</b> Activity 3: Assumptions</a></li>
<li class="chapter" data-level="5.2.5" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-4-descriptive-statistics-1"><i class="fa fa-check"></i><b>5.2.5</b> Activity 4: Descriptive statistics</a></li>
<li class="chapter" data-level="5.2.6" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-5-correlation"><i class="fa fa-check"></i><b>5.2.6</b> Activity 5: Correlation</a></li>
<li class="chapter" data-level="5.2.7" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-6-interpreting-the-correlation"><i class="fa fa-check"></i><b>5.2.7</b> Activity 6: Interpreting the correlation</a></li>
<li class="chapter" data-level="5.2.8" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-7-write-up"><i class="fa fa-check"></i><b>5.2.8</b> Activity 7: Write-up</a></li>
<li class="chapter" data-level="5.2.9" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-8-scatterplot-matrix"><i class="fa fa-check"></i><b>5.2.9</b> Activity 8: Scatterplot matrix</a></li>
<li class="chapter" data-level="5.2.10" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-9-multiple-correlations"><i class="fa fa-check"></i><b>5.2.10</b> Activity 9: Multiple correlations</a></li>
<li class="chapter" data-level="5.2.11" data-path="rm2-r-markdown-correlations.html"><a href="rm2-r-markdown-correlations.html#activity-solutions-3"><i class="fa fa-check"></i><b>5.2.11</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html"><i class="fa fa-check"></i><b>6</b> RM2 Missing Data &amp; T-Tests</a><ul>
<li class="chapter" data-level="6.1" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#pre-class-activities-2"><i class="fa fa-check"></i><b>6.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="6.1.1" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-1-set-up-6"><i class="fa fa-check"></i><b>6.1.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="6.1.2" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-2-look-at-the-data-2"><i class="fa fa-check"></i><b>6.1.2</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="6.1.3" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-3-listwise-deletion"><i class="fa fa-check"></i><b>6.1.3</b> Activity 3: Listwise deletion</a></li>
<li class="chapter" data-level="6.1.4" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#pairwise-deletion"><i class="fa fa-check"></i><b>6.1.4</b> Pairwise deletion</a></li>
<li class="chapter" data-level="6.1.5" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-3-na.rm-true"><i class="fa fa-check"></i><b>6.1.5</b> Activity 3: <code>na.rm = TRUE</code></a></li>
<li class="chapter" data-level="6.1.6" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-4-tidy-data"><i class="fa fa-check"></i><b>6.1.6</b> Activity 4: Tidy data</a></li>
<li class="chapter" data-level="6.1.7" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-5-questionnaire-data"><i class="fa fa-check"></i><b>6.1.7</b> Activity 5: Questionnaire data</a></li>
<li class="chapter" data-level="6.1.8" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-6-calculating-scale-scores"><i class="fa fa-check"></i><b>6.1.8</b> Activity 6: Calculating scale scores</a></li>
<li class="chapter" data-level="6.1.9" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-7-spread-back-to-wide-form"><i class="fa fa-check"></i><b>6.1.9</b> Activity 7: <code>spread()</code> back to wide-form</a></li>
<li class="chapter" data-level="6.1.10" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#finished-6"><i class="fa fa-check"></i><b>6.1.10</b> Finished!</a></li>
<li class="chapter" data-level="6.1.11" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-solutions-4"><i class="fa fa-check"></i><b>6.1.11</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#in-class-activities-3"><i class="fa fa-check"></i><b>6.2</b> In-class activities</a><ul>
<li class="chapter" data-level="6.2.1" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-1-set-up-7"><i class="fa fa-check"></i><b>6.2.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="6.2.2" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-2-explore-the-dataset"><i class="fa fa-check"></i><b>6.2.2</b> Activity 2: Explore the dataset</a></li>
<li class="chapter" data-level="6.2.3" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-3-ratings"><i class="fa fa-check"></i><b>6.2.3</b> Activity 3: Ratings</a></li>
<li class="chapter" data-level="6.2.4" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-4-visualisation"><i class="fa fa-check"></i><b>6.2.4</b> Activity 4: Visualisation</a></li>
<li class="chapter" data-level="6.2.5" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-5-assumptions"><i class="fa fa-check"></i><b>6.2.5</b> Activity 5: Assumptions</a></li>
<li class="chapter" data-level="6.2.6" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-6-running-the-t-test"><i class="fa fa-check"></i><b>6.2.6</b> Activity 6: Running the t-test</a></li>
<li class="chapter" data-level="6.2.7" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-8-correcting-for-multiple-comparisons"><i class="fa fa-check"></i><b>6.2.7</b> Activity 8: Correcting for multiple comparisons</a></li>
<li class="chapter" data-level="6.2.8" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-7-effect-size"><i class="fa fa-check"></i><b>6.2.8</b> Activity 7: Effect size</a></li>
<li class="chapter" data-level="6.2.9" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-8-interpreting-the-results"><i class="fa fa-check"></i><b>6.2.9</b> Activity 8: Interpreting the results</a></li>
<li class="chapter" data-level="6.2.10" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-9-write-up"><i class="fa fa-check"></i><b>6.2.10</b> Activity 9: Write-up</a></li>
<li class="chapter" data-level="6.2.11" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-10-paired-samples-t-test"><i class="fa fa-check"></i><b>6.2.11</b> Activity 10: Paired-samples t-test</a></li>
<li class="chapter" data-level="6.2.12" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-12-assumptions"><i class="fa fa-check"></i><b>6.2.12</b> Activity 12: Assumptions</a></li>
<li class="chapter" data-level="6.2.13" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-13-descriptives-and-visualisations"><i class="fa fa-check"></i><b>6.2.13</b> Activity 13: Descriptives and visualisations</a></li>
<li class="chapter" data-level="6.2.14" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-14-paired-samples-t-test"><i class="fa fa-check"></i><b>6.2.14</b> Activity 14: Paired-samples t-test</a></li>
<li class="chapter" data-level="6.2.15" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-15-write-up"><i class="fa fa-check"></i><b>6.2.15</b> Activity 15: Write-up</a></li>
<li class="chapter" data-level="6.2.16" data-path="rm2-missing-data-t-tests.html"><a href="rm2-missing-data-t-tests.html#activity-solutions-5"><i class="fa fa-check"></i><b>6.2.16</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="vis.html"><a href="vis.html"><i class="fa fa-check"></i><b>7</b> RM2 Visualisation, power, and effect size</a><ul>
<li class="chapter" data-level="7.1" data-path="vis.html"><a href="vis.html#pre-lab-activities-1"><i class="fa fa-check"></i><b>7.1</b> Pre-lab activities</a><ul>
<li class="chapter" data-level="7.1.1" data-path="vis.html"><a href="vis.html#activity-1-set-up-8"><i class="fa fa-check"></i><b>7.1.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="7.1.2" data-path="vis.html"><a href="vis.html#activity-2-histograms"><i class="fa fa-check"></i><b>7.1.2</b> Activity 2: Histograms</a></li>
<li class="chapter" data-level="7.1.3" data-path="vis.html"><a href="vis.html#activity-3-scatterplots"><i class="fa fa-check"></i><b>7.1.3</b> Activity 3: Scatterplots</a></li>
<li class="chapter" data-level="7.1.4" data-path="vis.html"><a href="vis.html#activity-4-boxplots"><i class="fa fa-check"></i><b>7.1.4</b> Activity 4: Boxplots</a></li>
<li class="chapter" data-level="7.1.5" data-path="vis.html"><a href="vis.html#activity-5-reordering-factors"><i class="fa fa-check"></i><b>7.1.5</b> Activity 5: Reordering factors</a></li>
<li class="chapter" data-level="7.1.6" data-path="vis.html"><a href="vis.html#activity-6-bar-charts"><i class="fa fa-check"></i><b>7.1.6</b> Activity 6: Bar Charts</a></li>
<li class="chapter" data-level="7.1.7" data-path="vis.html"><a href="vis.html#activity-7-violin-plots"><i class="fa fa-check"></i><b>7.1.7</b> Activity 7: Violin plots</a></li>
<li class="chapter" data-level="7.1.8" data-path="vis.html"><a href="vis.html#viobox"><i class="fa fa-check"></i><b>7.1.8</b> Activity 8: Violin-boxplots</a></li>
<li class="chapter" data-level="7.1.9" data-path="vis.html"><a href="vis.html#activity-9-faceting"><i class="fa fa-check"></i><b>7.1.9</b> Activity 9: Faceting</a></li>
<li class="chapter" data-level="7.1.10" data-path="vis.html"><a href="vis.html#activity-10-split-violins-and-raincloud-plots"><i class="fa fa-check"></i><b>7.1.10</b> Activity 10: Split-violins and raincloud plots</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="vis.html"><a href="vis.html#in-class-activities-4"><i class="fa fa-check"></i><b>7.2</b> In-class activities</a><ul>
<li class="chapter" data-level="7.2.1" data-path="vis.html"><a href="vis.html#power-and-error"><i class="fa fa-check"></i><b>7.2.1</b> Power and Error</a></li>
<li class="chapter" data-level="7.2.2" data-path="vis.html"><a href="vis.html#effect-size"><i class="fa fa-check"></i><b>7.2.2</b> Effect Size</a></li>
<li class="chapter" data-level="7.2.3" data-path="vis.html"><a href="vis.html#activity-1-set-up-9"><i class="fa fa-check"></i><b>7.2.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="7.2.4" data-path="vis.html"><a href="vis.html#activity-2-effect-size-from-a-one-sample-t-test"><i class="fa fa-check"></i><b>7.2.4</b> Activity 2: Effect size from a one-sample t-test</a></li>
<li class="chapter" data-level="7.2.5" data-path="vis.html"><a href="vis.html#activity-3-effect-size-from-between-subjects-t-test"><i class="fa fa-check"></i><b>7.2.5</b> Activity 3: Effect size from between-subjects t-test</a></li>
<li class="chapter" data-level="7.2.6" data-path="vis.html"><a href="vis.html#activity-4-t-value-and-effect-size-for-a-between-subjects-experiment"><i class="fa fa-check"></i><b>7.2.6</b> Activity 4: t-value and effect size for a between-subjects Experiment</a></li>
<li class="chapter" data-level="7.2.7" data-path="vis.html"><a href="vis.html#activity-5-pwr.t.test"><i class="fa fa-check"></i><b>7.2.7</b> Activity 5: <code>pwr.t.test()</code></a></li>
<li class="chapter" data-level="7.2.8" data-path="vis.html"><a href="vis.html#activity-6-sample-size-for-standard-power-one-sample-t-test"><i class="fa fa-check"></i><b>7.2.8</b> Activity 6: Sample size for standard power one-sample t-test</a></li>
<li class="chapter" data-level="7.2.9" data-path="vis.html"><a href="vis.html#activity-7-effect-size-from-a-high-power-between-subjects-t-test"><i class="fa fa-check"></i><b>7.2.9</b> Activity 7: Effect size from a high power between-subjects t-test</a></li>
<li class="chapter" data-level="7.2.10" data-path="vis.html"><a href="vis.html#activity-8-sample-size-for-a-correlation"><i class="fa fa-check"></i><b>7.2.10</b> Activity 8: Sample size for a correlation</a></li>
<li class="chapter" data-level="7.2.11" data-path="vis.html"><a href="vis.html#activity-9-effect-size-for-a-correlation-analysis"><i class="fa fa-check"></i><b>7.2.11</b> Activity 9: Effect size for a correlation analysis</a></li>
<li class="chapter" data-level="7.2.12" data-path="vis.html"><a href="vis.html#activity-10-effect-size-for-chi-square"><i class="fa fa-check"></i><b>7.2.12</b> Activity 10: Effect size for chi-square</a></li>
<li class="chapter" data-level="7.2.13" data-path="vis.html"><a href="vis.html#activity-11-power-of-published-research"><i class="fa fa-check"></i><b>7.2.13</b> Activity 11: Power of published research</a></li>
<li class="chapter" data-level="7.2.14" data-path="vis.html"><a href="vis.html#activity-solutions-6"><i class="fa fa-check"></i><b>7.2.14</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="rm2-anova.html"><a href="rm2-anova.html"><i class="fa fa-check"></i><b>8</b> RM2 ANOVA</a><ul>
<li class="chapter" data-level="8.1" data-path="rm2-anova.html"><a href="rm2-anova.html#pre-class-activities-3"><i class="fa fa-check"></i><b>8.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="8.1.1" data-path="rm2-anova.html"><a href="rm2-anova.html#background-intrusive-memories"><i class="fa fa-check"></i><b>8.1.1</b> Background: Intrusive memories</a></li>
<li class="chapter" data-level="8.1.2" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-1-set-up-10"><i class="fa fa-check"></i><b>8.1.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="8.1.3" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-2-data-wrangling"><i class="fa fa-check"></i><b>8.1.3</b> Activity 2: Data wrangling</a></li>
<li class="chapter" data-level="8.1.4" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-3-numbers-and-factors"><i class="fa fa-check"></i><b>8.1.4</b> Activity 3: Numbers and factors</a></li>
<li class="chapter" data-level="8.1.5" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-4-create-summary-statistics"><i class="fa fa-check"></i><b>8.1.5</b> Activity 4: Create summary statistics</a></li>
<li class="chapter" data-level="8.1.6" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-5-visualisation"><i class="fa fa-check"></i><b>8.1.6</b> Activity 5: Visualisation</a></li>
<li class="chapter" data-level="8.1.7" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-6-one-way-anova"><i class="fa fa-check"></i><b>8.1.7</b> Activity 6: One-way ANOVA</a></li>
<li class="chapter" data-level="8.1.8" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-7-assumption-checking"><i class="fa fa-check"></i><b>8.1.8</b> Activity 7: Assumption checking</a></li>
<li class="chapter" data-level="8.1.9" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-8-post-hoc-tests"><i class="fa fa-check"></i><b>8.1.9</b> Activity 8: Post-hoc tests</a></li>
<li class="chapter" data-level="8.1.10" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-9-power-and-effect-size"><i class="fa fa-check"></i><b>8.1.10</b> Activity 9: Power and effect size</a></li>
<li class="chapter" data-level="8.1.11" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-10-write-up"><i class="fa fa-check"></i><b>8.1.11</b> Activity 10: Write-up</a></li>
<li class="chapter" data-level="8.1.12" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-solutions-7"><i class="fa fa-check"></i><b>8.1.12</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="rm2-anova.html"><a href="rm2-anova.html#in-class-activities-5"><i class="fa fa-check"></i><b>8.2</b> In-class activities</a><ul>
<li class="chapter" data-level="8.2.1" data-path="rm2-anova.html"><a href="rm2-anova.html#factorial-anova"><i class="fa fa-check"></i><b>8.2.1</b> Factorial ANOVA</a></li>
<li class="chapter" data-level="8.2.2" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-1-set-up-11"><i class="fa fa-check"></i><b>8.2.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="8.2.3" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-2-descriptive-statistics"><i class="fa fa-check"></i><b>8.2.3</b> Activity 2: Descriptive statistics</a></li>
<li class="chapter" data-level="8.2.4" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-3-violin-boxplots"><i class="fa fa-check"></i><b>8.2.4</b> Activity 3: Violin-boxplots</a></li>
<li class="chapter" data-level="8.2.5" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-4-interaction-plots"><i class="fa fa-check"></i><b>8.2.5</b> Activity 4: Interaction plots</a></li>
<li class="chapter" data-level="8.2.6" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-5-anova"><i class="fa fa-check"></i><b>8.2.6</b> Activity 5: ANOVA</a></li>
<li class="chapter" data-level="8.2.7" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-6-assumption-checking"><i class="fa fa-check"></i><b>8.2.7</b> Activity 6: Assumption checking</a></li>
<li class="chapter" data-level="8.2.8" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-7-post-hoc-tests"><i class="fa fa-check"></i><b>8.2.8</b> Activity 7: Post-hoc tests</a></li>
<li class="chapter" data-level="8.2.9" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-8-write-up"><i class="fa fa-check"></i><b>8.2.9</b> Activity 8: Write-up</a></li>
<li class="chapter" data-level="8.2.10" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-9-transforming-data"><i class="fa fa-check"></i><b>8.2.10</b> Activity 9: Transforming data</a></li>
<li class="chapter" data-level="8.2.11" data-path="rm2-anova.html"><a href="rm2-anova.html#activity-solutions-8"><i class="fa fa-check"></i><b>8.2.11</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="rm2-regression.html"><a href="rm2-regression.html"><i class="fa fa-check"></i><b>9</b> RM2 Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="rm2-regression.html"><a href="rm2-regression.html#pre-class-activities-4"><i class="fa fa-check"></i><b>9.1</b> Pre-class activities</a><ul>
<li class="chapter" data-level="9.1.1" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-1-setup"><i class="fa fa-check"></i><b>9.1.1</b> Activity 1: Setup</a></li>
<li class="chapter" data-level="9.1.2" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-2-tidy-the-data"><i class="fa fa-check"></i><b>9.1.2</b> Activity 2: Tidy the data</a></li>
<li class="chapter" data-level="9.1.3" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-3-calculate-mean-anxiety-for-each-student"><i class="fa fa-check"></i><b>9.1.3</b> Activity 3: Calculate mean anxiety for each student</a></li>
<li class="chapter" data-level="9.1.4" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-4-join-the-datasets-together"><i class="fa fa-check"></i><b>9.1.4</b> Activity 4: Join the datasets together</a></li>
<li class="chapter" data-level="9.1.5" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-5-calculate-descriptives-for-the-variables-overall"><i class="fa fa-check"></i><b>9.1.5</b> Activity 5: Calculate descriptives for the variables overall</a></li>
<li class="chapter" data-level="9.1.6" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-6-visualisations"><i class="fa fa-check"></i><b>9.1.6</b> Activity 6: Visualisations</a></li>
<li class="chapter" data-level="9.1.7" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-7-run-the-regression"><i class="fa fa-check"></i><b>9.1.7</b> Activity 7: Run the regression</a></li>
<li class="chapter" data-level="9.1.8" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-8-assumption-checking"><i class="fa fa-check"></i><b>9.1.8</b> Activity 8: Assumption checking</a></li>
<li class="chapter" data-level="9.1.9" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-9-power-and-effect-size-1"><i class="fa fa-check"></i><b>9.1.9</b> Activity 9: Power and effect size</a></li>
<li class="chapter" data-level="9.1.10" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-10-write-up-1"><i class="fa fa-check"></i><b>9.1.10</b> Activity 10: Write-up</a></li>
<li class="chapter" data-level="9.1.11" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-solutions-9"><i class="fa fa-check"></i><b>9.1.11</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="rm2-regression.html"><a href="rm2-regression.html#in-class-activities-6"><i class="fa fa-check"></i><b>9.2</b> In-class activities</a><ul>
<li class="chapter" data-level="9.2.1" data-path="rm2-regression.html"><a href="rm2-regression.html#screen-time-and-well-being"><i class="fa fa-check"></i><b>9.2.1</b> Screen time and well-being</a></li>
<li class="chapter" data-level="9.2.2" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-1-set-up-12"><i class="fa fa-check"></i><b>9.2.2</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="9.2.3" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-2-look-at-the-data-3"><i class="fa fa-check"></i><b>9.2.3</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="9.2.4" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-3-compute-the-well-being-score-for-each-respondent"><i class="fa fa-check"></i><b>9.2.4</b> Activity 3: Compute the well-being score for each respondent</a></li>
<li class="chapter" data-level="9.2.5" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-4-visualise-the-relationship"><i class="fa fa-check"></i><b>9.2.5</b> Activity 4: Visualise the relationship</a></li>
<li class="chapter" data-level="9.2.6" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-5-smartphone-and-well-being-for-boys-and-girls"><i class="fa fa-check"></i><b>9.2.6</b> Activity 5: Smartphone and well-being for boys and girls</a></li>
<li class="chapter" data-level="9.2.7" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-6-mean-centering-variables"><i class="fa fa-check"></i><b>9.2.7</b> Activity 6: Mean-centering variables</a></li>
<li class="chapter" data-level="9.2.8" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-7-visualise-the-relationship"><i class="fa fa-check"></i><b>9.2.8</b> Activity 7: Visualise the relationship</a></li>
<li class="chapter" data-level="9.2.9" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-8-running-the-regression"><i class="fa fa-check"></i><b>9.2.9</b> Activity 8: Running the regression</a></li>
<li class="chapter" data-level="9.2.10" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-9-assumption-checking"><i class="fa fa-check"></i><b>9.2.10</b> Activity 9: Assumption checking</a></li>
<li class="chapter" data-level="9.2.11" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-10-power-and-effect-size"><i class="fa fa-check"></i><b>9.2.11</b> Activity 10: Power and effect size</a></li>
<li class="chapter" data-level="9.2.12" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-11-write-up-1"><i class="fa fa-check"></i><b>9.2.12</b> Activity 11: Write-up</a></li>
<li class="chapter" data-level="9.2.13" data-path="rm2-regression.html"><a href="rm2-regression.html#finished-11"><i class="fa fa-check"></i><b>9.2.13</b> Finished!</a></li>
<li class="chapter" data-level="9.2.14" data-path="rm2-regression.html"><a href="rm2-regression.html#activity-solutions-10"><i class="fa fa-check"></i><b>9.2.14</b> Activity solutions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html"><i class="fa fa-check"></i><b>10</b> Dissertation analysis guide</a><ul>
<li class="chapter" data-level="10.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#before-r"><i class="fa fa-check"></i><b>10.1</b> Before R</a><ul>
<li class="chapter" data-level="10.1.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#study-design"><i class="fa fa-check"></i><b>10.1.1</b> Study design</a></li>
<li class="chapter" data-level="10.1.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#data-wrangling-considerations"><i class="fa fa-check"></i><b>10.1.2</b> Data wrangling considerations</a></li>
<li class="chapter" data-level="10.1.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#data-analysis-1"><i class="fa fa-check"></i><b>10.1.3</b> Data analysis</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#exploring-and-cleaning-your-data"><i class="fa fa-check"></i><b>10.2</b> Exploring and cleaning your data</a><ul>
<li class="chapter" data-level="10.2.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#summary"><i class="fa fa-check"></i><b>10.2.1</b> <code>summary()</code></a></li>
<li class="chapter" data-level="10.2.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#visualisations"><i class="fa fa-check"></i><b>10.2.2</b> Visualisations</a></li>
<li class="chapter" data-level="10.2.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#renaming-variables"><i class="fa fa-check"></i><b>10.2.3</b> Renaming variables</a></li>
<li class="chapter" data-level="10.2.4" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#converting-to-factors"><i class="fa fa-check"></i><b>10.2.4</b> Converting to factors</a></li>
<li class="chapter" data-level="10.2.5" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#dropping-irrelevant-variables"><i class="fa fa-check"></i><b>10.2.5</b> Dropping irrelevant variables</a></li>
<li class="chapter" data-level="10.2.6" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#recoding-variables"><i class="fa fa-check"></i><b>10.2.6</b> Recoding variables</a></li>
<li class="chapter" data-level="10.2.7" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#exclude-participantsdata"><i class="fa fa-check"></i><b>10.2.7</b> Exclude participants/data</a></li>
<li class="chapter" data-level="10.2.8" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#reliability"><i class="fa fa-check"></i><b>10.2.8</b> Reliability</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#transforming-data"><i class="fa fa-check"></i><b>10.3</b> Transforming data</a><ul>
<li class="chapter" data-level="10.3.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#replace-missing-values"><i class="fa fa-check"></i><b>10.3.1</b> Replace missing values</a></li>
<li class="chapter" data-level="10.3.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#convert-implausible-values"><i class="fa fa-check"></i><b>10.3.2</b> Convert implausible values</a></li>
<li class="chapter" data-level="10.3.3" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#calculate-z-scores"><i class="fa fa-check"></i><b>10.3.3</b> Calculate z-scores</a></li>
<li class="chapter" data-level="10.3.4" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#log-transformation"><i class="fa fa-check"></i><b>10.3.4</b> Log transformation</a></li>
<li class="chapter" data-level="10.3.5" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#square-root"><i class="fa fa-check"></i><b>10.3.5</b> Square root</a></li>
<li class="chapter" data-level="10.3.6" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#calculating-new-variables"><i class="fa fa-check"></i><b>10.3.6</b> Calculating new variables</a></li>
<li class="chapter" data-level="10.3.7" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#tidy-data-1"><i class="fa fa-check"></i><b>10.3.7</b> Tidy data</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#summarising-and-visualising-data"><i class="fa fa-check"></i><b>10.4</b> Summarising and visualising data</a><ul>
<li class="chapter" data-level="10.4.1" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#descriptive-statistics"><i class="fa fa-check"></i><b>10.4.1</b> Descriptive statistics</a></li>
<li class="chapter" data-level="10.4.2" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#data-visualisation"><i class="fa fa-check"></i><b>10.4.2</b> Data visualisation</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#inferential-statistics"><i class="fa fa-check"></i><b>10.5</b> Inferential statistics</a></li>
<li class="chapter" data-level="10.6" data-path="dissertation-analysis-guide.html"><a href="dissertation-analysis-guide.html#assumption-tests"><i class="fa fa-check"></i><b>10.6</b> Assumption tests</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="supp.html"><a href="supp.html"><i class="fa fa-check"></i><b>11</b> Supplementary Analyses</a><ul>
<li class="chapter" data-level="11.1" data-path="supp.html"><a href="supp.html#data-transformation"><i class="fa fa-check"></i><b>11.1</b> Data transformation</a></li>
<li class="chapter" data-level="11.2" data-path="supp.html"><a href="supp.html#permutation-tests"><i class="fa fa-check"></i><b>11.2</b> Permutation tests</a><ul>
<li class="chapter" data-level="11.2.1" data-path="supp.html"><a href="supp.html#overview-1"><i class="fa fa-check"></i><b>11.2.1</b> Overview</a></li>
<li class="chapter" data-level="11.2.2" data-path="supp.html"><a href="supp.html#skill-1-generating-random-numbers"><i class="fa fa-check"></i><b>11.2.2</b> Skill 1: Generating Random Numbers</a></li>
<li class="chapter" data-level="11.2.3" data-path="supp.html"><a href="supp.html#skill-2-permuting-values"><i class="fa fa-check"></i><b>11.2.3</b> Skill 2: Permuting Values</a></li>
<li class="chapter" data-level="11.2.4" data-path="supp.html"><a href="supp.html#skill-3-creating-tibbles"><i class="fa fa-check"></i><b>11.2.4</b> Skill 3: Creating Tibbles</a></li>
<li class="chapter" data-level="11.2.5" data-path="supp.html"><a href="supp.html#skill-4-computing-differences-in-group-means"><i class="fa fa-check"></i><b>11.2.5</b> Skill 4: Computing Differences in Group Means</a></li>
<li class="chapter" data-level="11.2.6" data-path="supp.html"><a href="supp.html#skill-5-creating-your-own-functions"><i class="fa fa-check"></i><b>11.2.6</b> Skill 5: Creating Your Own Functions</a></li>
<li class="chapter" data-level="11.2.7" data-path="supp.html"><a href="supp.html#skill-6-replicating-operations"><i class="fa fa-check"></i><b>11.2.7</b> Skill 6: Replicating Operations</a></li>
<li class="chapter" data-level="11.2.8" data-path="supp.html"><a href="supp.html#permutation-tests-of-hypotheses"><i class="fa fa-check"></i><b>11.2.8</b> Permutation Tests of Hypotheses</a></li>
<li class="chapter" data-level="11.2.9" data-path="supp.html"><a href="supp.html#Ch5InClassQueT1"><i class="fa fa-check"></i><b>11.2.9</b> Step 1: Load in Add-on Packages and Data</a></li>
<li class="chapter" data-level="11.2.10" data-path="supp.html"><a href="supp.html#Ch5InClassQueT2"><i class="fa fa-check"></i><b>11.2.10</b> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></a></li>
<li class="chapter" data-level="11.2.11" data-path="supp.html"><a href="supp.html#Ch5InClassQueT3"><i class="fa fa-check"></i><b>11.2.11</b> Step 3: Permute the Group Labels</a></li>
<li class="chapter" data-level="11.2.12" data-path="supp.html"><a href="supp.html#Ch5InClassQueT4"><i class="fa fa-check"></i><b>11.2.12</b> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</a></li>
<li class="chapter" data-level="11.2.13" data-path="supp.html"><a href="supp.html#Ch5InClassQueT5"><i class="fa fa-check"></i><b>11.2.13</b> Step 5: Compare the Observed Mean Difference to the NHD</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="supp.html"><a href="supp.html#non-parametric-tests"><i class="fa fa-check"></i><b>11.3</b> Non-parametric tests</a></li>
<li class="chapter" data-level="11.4" data-path="supp.html"><a href="supp.html#simulation"><i class="fa fa-check"></i><b>11.4</b> Simulation</a></li>
<li class="chapter" data-level="11.5" data-path="supp.html"><a href="supp.html#rtweet"><i class="fa fa-check"></i><b>11.5</b> rtweet</a><ul>
<li class="chapter" data-level="11.5.1" data-path="supp.html"><a href="supp.html#packages-1"><i class="fa fa-check"></i><b>11.5.1</b> Packages</a></li>
<li class="chapter" data-level="11.5.2" data-path="supp.html"><a href="supp.html#hashtag-search"><i class="fa fa-check"></i><b>11.5.2</b> Hashtag search</a></li>
<li class="chapter" data-level="11.5.3" data-path="supp.html"><a href="supp.html#data-wrangling"><i class="fa fa-check"></i><b>11.5.3</b> Data wrangling</a></li>
<li class="chapter" data-level="11.5.4" data-path="supp.html"><a href="supp.html#time-series"><i class="fa fa-check"></i><b>11.5.4</b> Time series</a></li>
<li class="chapter" data-level="11.5.5" data-path="supp.html"><a href="supp.html#tidy-text-and-word-frequencies"><i class="fa fa-check"></i><b>11.5.5</b> Tidy text and word frequencies</a></li>
<li class="chapter" data-level="11.5.6" data-path="supp.html"><a href="supp.html#bigram-analysis"><i class="fa fa-check"></i><b>11.5.6</b> Bigram analysis</a></li>
<li class="chapter" data-level="11.5.7" data-path="supp.html"><a href="supp.html#sentiment-analysis"><i class="fa fa-check"></i><b>11.5.7</b> Sentiment analysis</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MSc Conversion in Psychological Studies/Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="supp" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> Supplementary Analyses</h1>
<p><strong>WARNING</strong> This chapter is still under construction.</p>
<p><img src="http://www.reactiongifs.com/wp-content/uploads/2013/07/see.gif" /></p>
<p>This chapter will contain a number of supplementary analyses. These are beyond the core content of the MSc Conversion course. Some of them are taken from the undergraduate course where there is more time for statistics, and some of them are just for fun. You may find some of the function useful for your dissertation or if you want to stretch yourself with the mini-project so it’s worth having a browse.WW</p>
<div id="data-transformation" class="section level2">
<h2><span class="header-section-number">11.1</span> Data transformation</h2>
<p>This section has been adapted from materials made available by <a href="http://abacus.bates.edu/~ganderso/biology/bio270/homework_files/Data_Transformation.pdf">Greg Anderson at Bates College</a>.</p>
<p>The following brief overview of Data Transformation is compiled from Howell (pp. 318-324,
2007) and Tabachnick and Fidell (pp. 86-89, 2007). See the references at the end of this handout for a more complete discussion of data transformation. Most people find it difficult to accept the idea of transforming data. Tukey (1977) probably had the right idea when he called data transformation calculations “reexpressions” rather than “transformations.” A researcher is merely reexpressing what the data have to say in other terms. However, it is important to recognize that conclusions that you draw on transformed data do not always transfer neatly to the original measurements. Grissom (2000) reports that the means of transformed variables can occasionally reverse the difference of means of the original variables. While this is disturbing, and it is important to think about the meaning of what you are doing, but it is not, in itself, a reason to rule out the use of transformations as a viable option.</p>
<p>If you are willing to accept that is it permissible to transform one set of measures into another, then many possibilities become available for modifying the data to fit more closely the underlying assumptions of statistical tests. An added benefit about most of the transformations is that when we transform the data to meet one assumption, we often come closer to meeting other assumptions as well. For example, a square-root transformation may help equate group variances, and because it compresses the upper end of a distribution more than it compresses the lower end, it may also have the effect of making positively skewed distributions more nearly normal in shape. If you decide to transform, it is important to check that the variable is normally or nearly normally distributed after transformation. That is, make sure it worked.</p>
<p>When it comes to reporting our data… although it is legitimate and proper to run a statistical test, such as the one-way analysis of variance, on the transformed values, we often report means in the unit of the untransformed scale. This is especially true when the original units are intrinsically meaningful. Howell (2007) urges researchers to look at both the converted (transformed) and unconverted (original) means and make sure that they are telling the same basic story. Do not convert standard deviations – you will do serious injustice if you try that. And be sure to indicate to your readers what you have done. It is not uncommon to see both the converted and unconverted values reported. Tabachnick and Fidell (2007) point out that, although data transformations are recommended as a remedy for outliers and for failures of normality, linearity, and homoscedasticity, they are not universally recommended. The reason is that an analysis is interpreted from the variables that are in it, and transformed variables are sometimes harder to interpret.</p>
<p>You should not get the impression that data transformations should be applied routinely to all your data. As a rule of thumb, “If it’s not broken, don’t fix it.” If your data are reasonably distributed (i.e., are more or less symmetrical and have few, if any, outliers) and if your variances are reasonably homogeneous, there is probably nothing to be gained by applying a transformation. If you have markedly skewed data or heterogeneous variances, however, some form of data transformation may be useful. Furthermore, it is perfectly legitimate to shop around for a transformation that makes the necessary changes to the variance and shape. The only thing you should not do it to try out every transformation, looking for one that gives you a significant result. You are trying to optimize the data, not the resulting F.</p>
<p>As suggested by Tabachnick and Fidell (2007) and Howell (2007), the following guidelines
should be used when transforming data.</p>
<table>
<thead>
<tr class="header">
<th align="left">Problem</th>
<th align="left">Transformation</th>
<th align="left">R function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Moderately positive skewness</td>
<td align="left">Square-root</td>
<td align="left"><code>sqrt(var)</code></td>
</tr>
<tr class="even">
<td align="left">Substantially positive skewness</td>
<td align="left">Logarithmic (Log 10)</td>
<td align="left"><code>log10(var)</code></td>
</tr>
<tr class="odd">
<td align="left">Substantially positive skewness (with zero values)</td>
<td align="left">Logarithmic (Log 10)</td>
<td align="left"><code>log10(var + C)</code></td>
</tr>
<tr class="even">
<td align="left">Moderately negative skewness</td>
<td align="left">Square-Root</td>
<td align="left"><code>sqrt(var + K)</code></td>
</tr>
<tr class="odd">
<td align="left">Substantially negative skewness</td>
<td align="left">Logarithmic (Log 10)</td>
<td align="left"><code>log10(K - var)</code></td>
</tr>
</tbody>
</table>
<p><code>C</code> = a constant added to each score so that the smallest score is 1.<br />
<code>K</code> = a constant from which each score is subtracted so that the smallest score is 1; usually equal to the largest score + 1.</p>
<p><strong>References</strong></p>
<p>Howell, D. C. (2007). Statistical methods for psychology (6th ed.). Belmont, CA: Thomson
Wadsworth.<br />
Grissom, R. J. (2000). Heterogeneity of variance in clinical data. <em>Journal of Consulting and Clinical Psychology, 68</em>, 155-165.<br />
Tabachnick, B. G., &amp; Fidell, L. S. (2007). <em>Using multivariate statistics (5th ed.)</em>. Boston: Allyn and Bacon.<br />
Tukey, J. W. (1977). <em>Exploratory data analysis</em>. Reading, MA: Addison-Wesley.</p>
<p>Also see:</p>
<p>Hoaglin, D. C., Mosteller, F., &amp; Tukey, J. W. (1983). <em>Understanding robust and exploratory data analysis</em>. New York: Wiley.</p>
</div>
<div id="permutation-tests" class="section level2">
<h2><span class="header-section-number">11.2</span> Permutation tests</h2>
<p>This section has been adapated from the Level 2 class on permutation tests written by Dr. Phil McAleer. The original <a href="https://psyteachr.github.io/ug2-practical/permutation-tests-a-skill-set.html">can be viewed here</a>.</p>
<div id="overview-1" class="section level3">
<h3><span class="header-section-number">11.2.1</span> Overview</h3>
<p>In this week’s lab you will perform your first hypothesis test using a procedure known as a <strong>permutation test</strong>. We will help you learn how to do this through building and running data simulation procedures. In order to complete this lab you will require the following skills which we will teach you today:</p>
<ul>
<li>Skill 1: Generating random numbers with <code>base::rnorm()</code></li>
<li>Skill 2: Permuting values with <code>base::sample()</code><br />
</li>
<li>Skill 3: Creating a “tibble” (a type of data table) using <code>tibble::tibble()</code></li>
<li>Skill 4: Computing and extracting a difference in group means using <code>dplyr::pull()</code> and <code>purrr::pluck()</code></li>
<li>Skill 5: Creating your own custom functions using <code>base::function()</code></li>
<li>Skill 6: Repeating operations using <code>base::replicate()</code></li>
</ul>
<p>To many, a lot of statistics must seem a bit like blind faith as it deals with estimating quantities we haven’t observed (or can’t observe), e.g. the mean of a whole population. As such we have to know if we can trust our procedures for making estimations and inferences because we rarely get a chance to compare the estimated values to the true values to see if they match up. One way to test a procedure, and in turn learn about statistics, is through data simulation. In simulations <strong>we create</strong> a population and then draw samples and run tests on the data, i.e. on this <strong>known</strong> population. By running lots of simulations we can test our procedures and make sure they are acting as we expect them to. This approach is known as a <strong>Monte Carlo simulation</strong>, named after the city famous for the many games of chance that are played there.</p>
<div class="info">
<p>
You can go read up on the Monte Carlo approach if you like. It can however get quite indepth, as having a brief glance at the wikipedia entry on it highlights. The main thing to keep in mind is that the method involves creating a population and continually taking samples from that population in order to make an inference. This is what we will show you in the lab. Data simulation and “creating” your own datasets, to see how tests work, is a great way to understand statistics. When doing this lab, keep in mind how easy it really is to find a significant result if even randomly created data can give a significant result. This may help dispell any notion that there is something inherently important about a significant result, in itself.
</p>
</div>
<p>We will now take each skill in turn. Be sure to try them all out. It looks a lot of reading but it is mainly just showing you the output of the functions so you can see you are doing it correctly. The key thing is to try them yourselves and don’t be scared to change things to see what might happen if you do it slightly differently. We will also ask a couple of questions along the way to make sure you understand the skills.</p>
</div>
<div id="skill-1-generating-random-numbers" class="section level3">
<h3><span class="header-section-number">11.2.2</span> Skill 1: Generating Random Numbers</h3>
<p>The <code>base::rnorm()</code> function generates values from a normal distribution and takes the following arguments:</p>
<ul>
<li><code>n</code>: the number of observations to generate</li>
<li><code>mean</code>: the mean of the distribution (default 0)</li>
<li><code>sd</code> : the standard deviation of the distribution (default 1)</li>
</ul>
<p>To generate 10 or even 50 random numbers from a standard normal distribution (M = 0, SD = 1), you would use <code>rnorm(10)</code> or <code>rnorm(50)</code> respectively.</p>
<ul>
<li>Type <code>rnorm(50)</code> into your console and see what happens. Use the below example for <code>rnorm(10)</code> to help you.<br />
</li>
<li>Try increasing <code>n</code> to 1000.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dv">10</span>)</code></pre>
<pre><code>##  [1]  0.62903686 -1.42110970 -1.07123653  0.85090829 -0.82086529
##  [6]  0.79386597  2.31086420 -0.38396039 -0.02777105  0.06351214</code></pre>
<p><br>
<span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>If you enter <code>rnorm(50)</code> again you will get different numbers. Why? <select class='solveme' data-answer='["The numbers are random"]'> <option></option> <option>I have made a mistake</option> <option>The numbers are random</option> <option>R has made a mistake</option> <option>Phil has made a mistake</option></select></p>
<p>If you want to change the mean or sd, you would need to pass additional arguments to the function as shown below.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">mean =</span> <span class="dv">1</span>, <span class="dt">sd =</span> <span class="fl">.5</span>)</code></pre>
<ul>
<li>Try changing the mean and sd values a couple of times and see what happens. You get different numbers again that will be around the mean you set! Set a mean of 10, then a mean of 100, to test this.</li>
</ul>
<p>Finally, for this Skill, you can concatenate (i.e. link) numbers together into a single vector using the <code>c()</code> function from base R. For instance, say you wanted to create a vector with two sets of 50 random numbers from two separate samples: one set of 50 with a mean of 75 and the other with a mean of 90, you would use:</p>
<pre class="sourceCode r"><code class="sourceCode r">random_numbers &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">50</span>, <span class="dv">75</span>),
                    <span class="kw">rnorm</span>(<span class="dv">50</span>, <span class="dv">90</span>))</code></pre>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>In the above example code, what is the standard deviation of the two samples you have created? <select class='solveme' data-answer='["1"]'> <option></option> <option>50</option> <option>75</option> <option>90</option> <option>1</option></select></p>
<div class="solution">
<button>
Explain This - I don’t get this answer!
</button>
<div class="info">
<p>
What is the <strong>default</strong> sd of the function?
</p>
<p>
Both populations would have an sd of 1, because that is the default, although you could easily change that. Try it out!
</p>
</div>
</div>
<p><br>
It is always good to check that your new vector has the right number of data points in it - i.e. the total of the two samples; a sanity check if you will. The new vector <code>random_numbers</code> should have 100 elements. You could verify this using the <code>length()</code> function:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(random_numbers)</code></pre>
<pre><code>## [1] 100</code></pre>
<p><br></p>
</div>
<div id="skill-2-permuting-values" class="section level3">
<h3><span class="header-section-number">11.2.3</span> Skill 2: Permuting Values</h3>
<p>Another thing that is useful to be able to do is to generate <strong>permutations</strong> of values.</p>
<div class="solution">
<button>
Portfolio Point - What are Permutations?
</button>
<div class="info">
<p>
A <strong>permutation</strong> is just a different ordering of the same values. For example, the numbers 1, 2, 3 can be permuted into the following 6 sequences:
</p>
<ul>
<li>
1, 2, 3
</li>
<li>
1, 3, 2
</li>
<li>
2, 1, 3
</li>
<li>
2, 3, 1
</li>
<li>
3, 1, 2
</li>
<li>
3, 2, 1
</li>
</ul>
<p>
The more values you have, the more permutations of the order you have. The number of permutations can be calculated by, for example, <code>3<em>2</em>1</code>, where 3 is the number of values you have. Or through code: <code>factorial(3) = 6</code>. This assumes that each value is used once in the sequence and that each value never changes, i.e. 1234 cannot suddenly become 1235.
</p>
</div>
</div>
<p>We can create random permutations of a vector using the <code>sample()</code> function. Let’s use one of R’s built in vectors: <code>letters</code>.</p>
<ul>
<li>Type <code>letters</code> into the console, as below, and press RETURN/ENTER. You will see it contains all the lowercase letters of the English alphabet. Now, I bet you are wondering what <code>LETTERS</code> does, right?</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">letters</code></pre>
<pre><code>##  [1] &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot; &quot;f&quot; &quot;g&quot; &quot;h&quot; &quot;i&quot; &quot;j&quot; &quot;k&quot; &quot;l&quot; &quot;m&quot; &quot;n&quot; &quot;o&quot; &quot;p&quot; &quot;q&quot;
## [18] &quot;r&quot; &quot;s&quot; &quot;t&quot; &quot;u&quot; &quot;v&quot; &quot;w&quot; &quot;x&quot; &quot;y&quot; &quot;z&quot;</code></pre>
<p>We can combine <code>base::sample()</code> with <code>letters</code> to put the letters into a random order:</p>
<ul>
<li>Run the below line. Run it again. And again. What do you notice? And why is our output different from yours? (The answer is below)</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sample</span>(letters)</code></pre>
<pre><code>##  [1] &quot;m&quot; &quot;v&quot; &quot;u&quot; &quot;j&quot; &quot;e&quot; &quot;i&quot; &quot;l&quot; &quot;r&quot; &quot;o&quot; &quot;y&quot; &quot;s&quot; &quot;b&quot; &quot;z&quot; &quot;k&quot; &quot;c&quot; &quot;g&quot; &quot;q&quot;
## [18] &quot;d&quot; &quot;h&quot; &quot;x&quot; &quot;w&quot; &quot;n&quot; &quot;a&quot; &quot;f&quot; &quot;p&quot; &quot;t&quot;</code></pre>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>If <code>month.name</code> contains the names of the twelve months of the year, how many possible permutations are there of <code>sample(month.name)</code>? <select class='solveme' data-answer='["479001600"]'> <option></option> <option>1</option> <option>12</option> <option>144</option> <option>479001600</option></select></p>
<div class="solution">
<button>
Portfolio Point - Different samples with sample()
</button>
<div class="info">
<p>
Each time you run <code>sample(letters)</code> it will give you another random permutation of the sequence. That is what <code>sample()</code> does - creates a random permutation of the values you give it. Try repeating this command many times in the console. Because there are so many possible sequences, it is very unlikely that you will ever see the same sequence twice!
</p>
<p>
An interesting thing about <code>sample()</code> is that <code>sample(c(1,2,3,4))</code> is the same as <code>sample(4)</code>. And to recap, there would be 24 different permutations based on <code>factorial(4)</code>, meaning that each time you type <code>sample(4)</code> you are getting one of those 24 different orders. So what would factorial(12) be?
</p>
<p>
Top Tip: Remember that you can scroll up through your command history in the console using the up arrow on your keyboard; this way, you don’t ever have to retype a command you’ve already entered.
</p>
</div>
</div>
<p><br></p>
</div>
<div id="skill-3-creating-tibbles" class="section level3">
<h3><span class="header-section-number">11.2.4</span> Skill 3: Creating Tibbles</h3>
<p>Tables are important because most of the data we want to analyze comes in a table, i.e. tabular form. There are different ways to get tabular data into R for analysis. One common way is to load existing data in from a data file (for example, using <code>readr::read_csv()</code> which you have seen before). But other times you might want to just type in data directly. You can do this using the <code>tibble::tibble()</code> function. Being able to create a tibble is a useful data analysis skill because sometimes you will want to create some data on the fly just to try certain codes or functions.</p>
<div id="entering-data-into-a-tibble" class="section level4">
<h4><span class="header-section-number">11.2.4.1</span> Entering Data into a Tibble</h4>
<p>The <code>tibble()</code> function takes named arguments - this means that the name you give each argument within the tibble function, e.g. <code>Y = rnorm(10)</code> will be the name of the column that appears in the table, i.e. <code>Y</code>. It’s best to see how it works through an example.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tibble</span>(<span class="dt">Y =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>))</code></pre>
<pre><code>## # A tibble: 10 x 1
##           Y
##       &lt;dbl&gt;
##  1  0.189  
##  2  1.08   
##  3 -0.813  
##  4 -0.863  
##  5 -0.960  
##  6 -0.00148
##  7 -0.626  
##  8 -1.02   
##  9  1.65   
## 10 -1.18</code></pre>
<p>The above command creates a new table with one column named <code>Y</code>, and the values in that column are the result of a call to <code>rnorm(10)</code>: 10 randomly sampled values from a standard normal distribution (mean = 0, sd = 1) - See Skill 1.</p>
<p>If however we wanted to sample from two different populations for <code>Y</code>, we could combine two calls to <code>rnorm()</code> within the <code>c()</code> function. Again this was in Skill 1, here we are now just storing it in a tibble. See below:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tibble</span>(<span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span> <span class="dv">-10</span>), 
             <span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span>  <span class="dv">20</span>)))</code></pre>
<pre><code>## # A tibble: 10 x 1
##         Y
##     &lt;dbl&gt;
##  1 -12.7 
##  2 -10.7 
##  3  -9.34
##  4  -8.82
##  5  -9.62
##  6  20.0 
##  7  21.6 
##  8  20.9 
##  9  21.4 
## 10  20.3</code></pre>
<p>Now we have sampled a total of 10 observations - the first 5 come from a group with a mean of -10, and the second 5 come from a group with a mean of 20. Try changing the values in the above example to get an idea of how this works. Maybe even add a third group!</p>
<p>But, of course, it would be good to know which population each data point refers to and so we should add some group names. We can do this with some additional trickery using the <code>rep()</code> function.</p>
</div>
<div id="repeating-values-to-save-typing" class="section level4">
<h4><span class="header-section-number">11.2.4.2</span> Repeating Values to Save Typing</h4>
<p>Before finalising our table let’s learn a little about the base R function, <code>rep()</code>. This is most useful for automatically repeating values in order to save typing. For instance, if we wanted 20 letter “A”s in a row, we would type:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rep</span>(<span class="st">&quot;A&quot;</span>, <span class="dv">20</span>)</code></pre>
<pre><code>##  [1] &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot;
## [18] &quot;A&quot; &quot;A&quot; &quot;A&quot;</code></pre>
<p>The first argument to <code>rep()</code> is the vector containing the information you want repeated, <strong>A</strong>, and the second argument, <code>times</code>, is the number of times to repeat it; in this case <strong>20</strong>.</p>
<p>If you wanted to add more information, e.g. if the first argument has more than one element, say “A” and “B”, it will repeat the entire vector that number of times; A B, A B, A B, … . Note that we enclose “A” and “B” in the <code>c()</code> function so that it is seen as a single argument.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="dv">20</span>)</code></pre>
<pre><code>##  [1] &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot;
## [18] &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot;
## [35] &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot; &quot;A&quot; &quot;B&quot;</code></pre>
<p>But sometimes we want a specific number of As followed by a specific number of Bs; A A A B B B. If the <code>times</code> argument has the same number of elements as the vector given for the first argument, it will repeat each element of the first vector as many times as given by the corresponding element in the <code>times</code> vector. In other words, for example, <code>times = c(2, 4)</code> for vector <code>c("A", "B")</code> will give you 2 As followed by 4 Bs.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>))</code></pre>
<pre><code>## [1] &quot;A&quot; &quot;A&quot; &quot;B&quot; &quot;B&quot; &quot;B&quot; &quot;B&quot;</code></pre>
<p>The best way to learn about this function is to play around with it in the console and see what happens. From the dropdown menus, the correct output of the following function would be:</p>
<ol style="list-style-type: decimal">
<li><p><code>rep(c("A", "B", "C"),(2, 3, 1))</code> - <select class='solveme' data-answer='["A A B B B C"]'> <option></option> <option>A A A B B C</option> <option>A A B B B C</option> <option>A A B B C C</option> <option>A B C A B C</option></select></p></li>
<li><p><code>rep(1:5, 5:1)</code> - <select class='solveme' data-answer='["1 1 1 1 1 2 2 2 2 3 3 3 4 4 5"]'> <option></option> <option>1 2 3 4 5 1 2 3 4 5 1 2 3 4 5</option> <option>5 5 5 5 5 4 4 4 4 3 3 3 2 2 1</option> <option>1 1 1 1 1 2 2 2 2 3 3 3 4 4 5</option> <option>1 1 1 1 1 1 1 1 5 5 5 5 5 5 5</option></select></p></li>
</ol>
</div>
<div id="bringing-it-together-in-a-tibble" class="section level4">
<h4><span class="header-section-number">11.2.4.3</span> Bringing it Together in a Tibble</h4>
<p>Now we know <code>rep()</code>, we can complete our table of simulated data by combining what we’ve learned about generating random numbers and repeating values. We want our table to look like this:</p>
<pre><code>## # A tibble: 10 x 2
##    group      Y
##    &lt;chr&gt;  &lt;dbl&gt;
##  1 A     -10.4 
##  2 A      -9.93
##  3 A     -10.0 
##  4 A      -9.09
##  5 A     -10.5 
##  6 B      20.4 
##  7 B      20.7 
##  8 B      19.8 
##  9 B      19.9 
## 10 B      19.9</code></pre>
<p>You now know how to create this table. Have a look at the code below and make sure you understand it. We have one column called <code>group</code> where we create <strong>A</strong>s and <strong>B</strong>s through <code>rep()</code>, and one column called <strong>Y</strong>, our data, all in our <code>tibble()</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">5</span>)),
       <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span> <span class="dv">-10</span>), <span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span>  <span class="dv">20</span>)))</code></pre>
<p>Be sure to play around with the code chunk to get used to it. Try adding a third group or even a third column? Perhaps you want to give every participant a random age with a mean of 18, and a sd of 1; or even a participant number.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Try <code>row_number()</code> to create participant numbers.
</p>
</div>
</div>
<p><br>
Don’t forget, if you wanted to store your tibble, you would just assign it to a name, such as <code>my_data</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r">my_data &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">ID =</span> <span class="kw">row_number</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>), 
                    <span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">5</span>)),
                    <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span> <span class="dv">-10</span>), <span class="kw">rnorm</span>(<span class="dv">5</span>, <span class="dt">mean =</span>  <span class="dv">20</span>)),
                    <span class="dt">Age =</span> <span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">18</span>, <span class="dv">1</span>))</code></pre>
<p><br>
<span style="font-size: 18px; font-weight: bold; color: var(--blue);">Skill 3 out of 6 Complete!</span></p>
</div>
</div>
<div id="skill-4-computing-differences-in-group-means" class="section level3">
<h3><span class="header-section-number">11.2.5</span> Skill 4: Computing Differences in Group Means</h3>
<p>You have already learned how to calculate group means using <code>group_by()</code> and <code>summarise()</code>. For example, you might want to calculate sample means for a randomly generated dataset like so:</p>
<pre class="sourceCode r"><code class="sourceCode r">my_data &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">20</span>)),
                  <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">20</span>,  <span class="dv">20</span>, <span class="dv">5</span>), <span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dv">-20</span>, <span class="dv">5</span>)))

my_data_means &lt;-<span class="st"> </span>my_data <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">m =</span> <span class="kw">mean</span>(Y))

my_data_means</code></pre>
<pre><code>## # A tibble: 2 x 2
##   group     m
##   &lt;chr&gt; &lt;dbl&gt;
## 1 A      23.3
## 2 B     -21.1</code></pre>
<p>Sometimes what we want though is to calculate <strong>the differences between means</strong> rather than just the means; so we’d like to subtract the second group mean -21.1 from the first group mean of 23.3, to get a single value, the difference: 44.4.</p>
<p>We can do this using the <code>dplyr::pull()</code> and <code>purrr::pluck()</code> functions. <code>pull()</code> will extract a single column from a dataframe and turn it into a vector. <code>pluck()</code> then allows you to pull out an element (i.e. a value or values) from within that vector.</p>
<pre class="sourceCode r"><code class="sourceCode r">vec &lt;-<span class="st"> </span>my_data_means <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">pull</span>(m)

vec</code></pre>
<pre><code>## [1]  23.25585 -21.10182</code></pre>
<p>We have now created <code>vec</code> which is a vector containing only the group means; the rest of the information in the table has been discarded. Now that we have <code>vec</code>, we can calculate the mean difference as below, where <code>vec</code> is our vector of the two means and <code>[1]</code> and <code>[2]</code> refer to the two means:</p>
<pre class="sourceCode r"><code class="sourceCode r">vec[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>vec[<span class="dv">2</span>]</code></pre>
<pre><code>## [1] 44.35767</code></pre>
<p>But <code>pluck()</code> is also useful, and can be written as so:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pluck</span>(vec, <span class="dv">1</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pluck</span>(vec, <span class="dv">2</span>)</code></pre>
<pre><code>## [1] 44.35767</code></pre>
<p>It can also be incorporated into a pipeline as below where we still <code>pull()</code> the means column, <code>m</code>, and then <code>pluck()</code> each value in turn and subtract them from each other.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">## whole thing in a pipeline</span>
my_data_means <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(m) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pluck</span>(<span class="dv">1</span>) <span class="op">-</span>
<span class="st">  </span>my_data_means <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(m) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pluck</span>(<span class="dv">2</span>)</code></pre>
<pre><code>## [1] 44.35767</code></pre>
<p>However, there is an alternative way to extract the difference between means which may make more intuitive sense. You already know how to calculate a difference between values in the same row of a table using <code>dplyr::mutate()</code>, e.g. <code>mutate(new_column = column1 minus column2)</code>. So if you can get the observations in <code>my_data_means</code> into the same row, different columns, you could then use <code>mutate()</code> to calculate the difference. Previously you learned <code>gather()</code> to bring columns together. Well the opposite of gather is the <code>tidyr::spread()</code> function to split columns apart - as below.</p>
<pre class="sourceCode r"><code class="sourceCode r">my_data_means <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(group, m)</code></pre>
<pre><code>## # A tibble: 1 x 2
##       A     B
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  23.3 -21.1</code></pre>
<p>The spread function (<code>?spread</code>) splits the data in column <code>m</code> by the information, i.e. labels, in column <code>group</code> and puts the data into separate columns. A call to <code>spread()</code> followed by a <code>mutate()</code> can be used to calculate the difference in means - see below:</p>
<pre class="sourceCode r"><code class="sourceCode r">my_data_means <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(group, m) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> A <span class="op">-</span><span class="st"> </span>B) </code></pre>
<pre><code>## # A tibble: 1 x 3
##       A     B  diff
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  23.3 -21.1  44.4</code></pre>
<ul>
<li>What is the name of the column containing the differences between the means of A and B? <select class='solveme' data-answer='["diff"]'> <option></option> <option>means</option> <option>group</option> <option>m</option> <option>diff</option></select></li>
</ul>
<p>Finally, if you then wanted to just get <code>diff</code> and throw away everything else in the table:</p>
<pre class="sourceCode r"><code class="sourceCode r">my_data_means <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(group, m) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> A <span class="op">-</span><span class="st"> </span>B) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">pull</span>(diff)</code></pre>
<pre><code>## [1] 44.35767</code></pre>
<div class="solution">
<button>
Portfolio Point - Reading pipes and verbalising tasks
</button>
<div class="info">
<p>
Keep in mind that a very useful technique for establishing what you want to do to a dataframe is to verbalise what you need, or to write it down in words, or to say it out loud. Take this last code chunk. What we wanted to do was to <code>spread()</code> the data in <code>m</code> into the groups A and B. Then we wanted to <code>mutate()</code> a new column that is the difference, <code>diff</code>, of A minus B. And finally we wanted to <code>pull()</code> out the value in <code>diff</code>.
</p>
<p>
Often step 1 of writing code or understanding code is knowing what it is you want to do in the first place. After that you just need the correct functions. Fortunately for us a lot of the <code>tidyverse</code> names its functions based on what they specifically do!
</p>
</div>
</div>
<p><br></p>
</div>
<div id="skill-5-creating-your-own-functions" class="section level3">
<h3><span class="header-section-number">11.2.6</span> Skill 5: Creating Your Own Functions</h3>
<p>In Skills 1 to 4, we have looked at creating and sampling data, storing it in a tibble, and extracting information from that tibble. Now say we wanted to do this over and over again. For instance, we might want to generate 100 random datasets just like the one in Skill 4. It would be a pain to have to type out the <code>tibble()</code> function 100 times or even to copy and paste it 100 times. We’d likely make an error somewhere and it would be hard to read. To help us, we can create a custom function that performs the action you want; in our case, creating a tibble of random data.</p>
<p>Remember, a function is just a procedure that takes an input and gives you the same output each time - like a toaster! A function has the following format:</p>
<pre class="sourceCode r"><code class="sourceCode r">name_of_function &lt;-<span class="st"> </span><span class="cf">function</span>(arg1, arg2, arg3) {
  <span class="co">## body of function goes between these curly brackets; i.e. what the function does for you.</span>
  <span class="co">## Note that the last value calculated will be returned if you call the function.</span>
}</code></pre>
<p>First you define your own function name (e.g. <code>name_of_function</code>) and define the names of the arguments it will take (<code>arg1</code>, <code>arg2</code>, …) - an argument is the information that you feed into your function, e.g. data. Finally, you state the calculations or actions of the function in the body of the function (the portion that appears between the curly braces).</p>
<p>One of the most basic possible functions is one that takes no arguments and just prints a message. Here is an example:</p>
<pre class="sourceCode r"><code class="sourceCode r">hello &lt;-<span class="st"> </span><span class="cf">function</span>() {
  <span class="kw">print</span>(<span class="st">&quot;Hello World!&quot;</span>)
}</code></pre>
<p>So this function is called <code>hello</code>. It can be run by typing <code>hello()</code> in your console and it will give the output of <code>Hello World!</code> every single time you run it; it has no other actions or information. Test this in the console now by typing:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hello</span>()</code></pre>
<pre><code>## [1] &quot;Hello World!&quot;</code></pre>
<p>Awesome right? Ok, so not very exciting. Let’s make it better by adding an argument, <code>name</code>, and have it say Hello to <code>name</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">hello &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;World!&quot;</span>) {
  <span class="kw">paste</span>(<span class="st">&quot;Hello&quot;</span>, name)
}</code></pre>
<p>This new function is again called <code>hello()</code> and replaces the one you previously created. This time however you are supplying what is called a default argument, `name = “World!”, but it still has the same action as the previous function of putting “Hello” and “World!” together. So if you run it you get “Hello World!”. Try it yourself!</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hello</span>()</code></pre>
<pre><code>## [1] &quot;Hello World!&quot;</code></pre>
<p>The difference this time however is that because you have added an argument to the input, you can change the information you give the argument and therefore change the output of the function. More flexible. More exciting.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>Test your understanding by answering these questions:</p>
<ul>
<li><p>Typing <code>hello("Phil")</code> in the console with this new function will give: <select class='solveme' data-answer='["Hello Phil"]'> <option></option> <option>Hello Heather</option> <option>Hello Phil</option> <option>Hello Niamh</option> <option>Hello Kevin</option></select></p></li>
<li><p>Typing the argument as <code>"is it me you are looking for"</code> will give: <select class='solveme' data-answer='["Hello is it me you are looking for"]'> <option></option> <option>Hello is it me you are looking for</option> <option>I just called to say Hello</option> <option>You had me at Hello</option> <option>Hello seems to be the hardest word</option></select></p></li>
<li><p>What argument would you type to get “Hello Dolly!” as the output: <select class='solveme' data-answer='["Dolly!"]'> <option></option> <option>Dolly</option> <option>Molly</option> <option>Holly</option> <option>Dolly!</option></select></p></li>
</ul>
<p>Most of the time however we want to create a function that computes a value or constructs a table. For instance, let’s create a function that returns randomly generated data from two samples, as we learned in the previous skills - see below. All we are doing is taking the tibble we created in Skill 4 and putting it in the body (between the curly brackets) of the function.</p>
<pre class="sourceCode r"><code class="sourceCode r">gen_data &lt;-<span class="st"> </span><span class="cf">function</span>() {
  <span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">20</span>)),
                  <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">20</span>,  <span class="dv">20</span>, <span class="dv">5</span>), <span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dv">-20</span>, <span class="dv">5</span>)))
}</code></pre>
<p>This function is called <code>gen_data()</code> and when we run it we get a randomly generated table of two groups, each with 20 people, one with M = 20, SD = 5, the other with M = -20, sd = 5. Try running this <code>gen_data()</code> function in the console a few times; remember that as the data is random, the numbers will be different each time you run it.</p>
<p>But say we want to modify the function to allow us to get a table with smaller or larger numbers of observations per group. We can add an argument <code>n</code> and modify the code as follows. Create this function and run it a couple of times through <code>gen_data()</code>. The way to think about this is that every place that <code>n</code> appears in the body of the function (between the curly brackets) it will have the value of whatever you gave it in the arguments, i.e. in this case, 20.</p>
<pre class="sourceCode r"><code class="sourceCode r">gen_data &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">n =</span> <span class="dv">20</span>) {
  <span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(n, n)),
                  <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(n,  <span class="dv">20</span>, <span class="dv">5</span>), <span class="kw">rnorm</span>(n, <span class="dv">-20</span>, <span class="dv">5</span>)))
}</code></pre>
<ul>
<li><p>How many total participants would there be if you ran <code>gen_data(2)</code>? <select class='solveme' data-answer='["4"]'> <option></option> <option>2</option> <option>4</option> <option>20</option> <option>40</option></select></p></li>
<li><p>What would you type to get 100 participants per group? <select class='solveme' data-answer='["gen_data(100)"]'> <option></option> <option>gen_data(50)</option> <option>gen_data(10)</option> <option>gen_dota(100)</option> <option>gen_data(100)</option></select></p></li>
</ul>
<p><strong>Challenge Question:</strong></p>
<p>Keeping in mind that functions can take numerous arguments, and that each group in your function have separate means, can you modify the function <code>gen_data</code> to allow the user to change the means for the two calls to <code>rnorm</code>? Have a try before revealing the solution below.</p>
<div class="solution">
<button>
Solution To Challenge Question
</button>
<pre class="sourceCode r"><code class="sourceCode r">gen_data &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">m1 =</span> <span class="dv">20</span>, <span class="dt">m2 =</span> <span class="dv">-20</span>) {
  <span class="kw">tibble</span>(<span class="dt">group =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>), <span class="kw">c</span>(n, n)),
                  <span class="dt">Y =</span> <span class="kw">c</span>(<span class="kw">rnorm</span>(n,  m1, <span class="dv">5</span>), <span class="kw">rnorm</span>(n, m2, <span class="dv">5</span>)))
}

<span class="co"># m1 is the mean of group A, </span>
<span class="co"># m2 is mean of group B and would look like:</span>

<span class="co"># The function would be called by: gen_data(20, 20, -20)</span>
<span class="co"># Giving 20 participants in each group, </span>
<span class="co"># The first group having a mean of 20, </span>
<span class="co"># The second group having a mean of -20. </span>

<span class="co"># Likewise, a call of: gen_data(4, 10, 5)</span>
<span class="co"># Would give two groups of 4, </span>
<span class="co"># The first having a mean of 10, </span>
<span class="co"># The second having a mean of 5.</span></code></pre>
</div>
<div class="solution">
<button>
Portfolio Point - Two important facts about functions
</button>
<div class="info">
<p>
Here are two important things to understand about functions.
</p>
<ol style="list-style-type: decimal">
<li>
<p>
<strong>Functions obey lexical scoping.</strong> What does this mean? It’s like what they say about Las Vegas: what happens in the function, stays in the function. Any variables created inside of a function will be discarded after the function executes and will not be accessible to the outside calling process. So if you have a line, say a variable <code>my_var &lt;- 17</code> inside of a function, and try to print <code>my_var</code> from outside of the function, you will get an error: <code>object ‘my_var’ not found</code>. Although the function can ‘read’ variables from the environment that are not passed to it through an argument, it cannot change them. So you can only write a function to return a value, not change a value.
</p>
</li>
<li>
<p>
<strong>Functions return the last value that was computed.</strong> You can compute many things inside of a function but only the last thing that was computed will be returned as part of the calling process. If you want to return <code>my_var</code>, which you computed earlier but not as the final computation, you can do so explicitly using <code>return(my_var)</code> at the end of the function (before the second curly bracket).
</p>
</li>
</ol>
</div>
</div>
<p><br></p>
</div>
<div id="skill-6-replicating-operations" class="section level3">
<h3><span class="header-section-number">11.2.7</span> Skill 6: Replicating Operations</h3>
<p>The last skill you will need for the upcoming lab is knowing how to repeat an action (or expression) multiple times. You saw this in Lab 4 so we will only briefly recap here. Here, we use the base function <code>replicate()</code>. For instance, say you wanted to calculate the mean from <code>rnorm(100)</code> ten times, you could write it like this:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">## bad way</span>
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()
<span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</code></pre>
<p>But it’s far easier and more readable to wrap the expression in <code>replicate()</code> function where the first argument is the number of times you want to repeat the expression stated as the second argument, i.e. <code>replicate(times, expression)</code>. Here below we replicate the mean of 100 randomly generated numbers from the normal distribution, and we do this 10 times:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">replicate</span>(<span class="dv">10</span>, <span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>())</code></pre>
<p>Also you’ll probably want to store the results in a variable, for example, <code>ten_samples</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r">ten_samples &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">10</span>, <span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>())
ten_samples</code></pre>
<pre><code>##  [1]  0.08109598 -0.13962217 -0.01384128  0.05973910 -0.07897518
##  [6]  0.17048644 -0.06122999  0.05235143  0.07043759  0.03129970</code></pre>
<p>Each element (value) of the vector within <code>ten_samples</code> is the result of a single call to <code>rnorm(100) %&gt;% mean()</code>.</p>
<ul>
<li>Assuming that your <code>hello()</code> function from Skill 5 still exists, and it takes the argument <code>name = Goodbye</code>, what would happen in the console if you wrote, <code>replicate(1000, hello("Goodbye"))</code>? <select class='solveme' data-answer='["Hello Goodbye would appear a thousand times"]'> <option></option> <option>Hello World would appear a thousand times</option> <option>hello Goodbye would appear a thousand times</option> <option>Hello Goodbye would appear a thousand times</option></select> - Try it and see if it works!</li>
</ul>
<div class="solution">
<button>
Solution To Quickfire Question
</button>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># the function would be:</span>
hello &lt;-<span class="st"> </span><span class="cf">function</span>(<span class="dt">name =</span> <span class="st">&quot;World!&quot;</span>){
  <span class="kw">paste</span>(<span class="st">&quot;Hello&quot;</span>, name)
}

<span class="co"># and would be called by:</span>
<span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">hello</span>(<span class="st">&quot;Goodbye&quot;</span>))</code></pre>
</div>
<p><br></p>
<div id="finished-12" class="section level4">
<h4><span class="header-section-number">11.2.7.1</span> Finished!</h4>
<p>To recap, we have shown you the following six skills:</p>
<ul>
<li>Skill 1: Generating random numbers with <code>base::rnorm()</code></li>
<li>Skill 2: Permuting values with <code>base::sample()</code><br />
</li>
<li>Skill 3: Creating a “tibble” (a type of data table) using <code>tibble::tibble()</code></li>
<li>Skill 4: Computing and extracting a difference in group means using <code>dplyr::pull()</code> and <code>purrr::pluck()</code></li>
<li>Skill 5: Creating your own custom functions using <code>base::function()</code></li>
<li>Skill 6: Repeating operations using <code>base::replicate()</code></li>
</ul>
<p>You will need these skills in the coming lab to help you perform a real <strong>permutation test</strong>. Through these skills and the permutation test you will learn about null hypothesis significance testing.</p>
</div>
</div>
<div id="permutation-tests-of-hypotheses" class="section level3">
<h3><span class="header-section-number">11.2.8</span> Permutation Tests of Hypotheses</h3>
<p>A common statistical question when comparing two groups might be, “<strong>Is there a real difference between the group means?</strong>” From this we can establish two contrasting hypotheses:</p>
<ol style="list-style-type: decimal">
<li>The <strong>null hypothesis</strong> which states that the group means <strong>are equivalent</strong> and is written as: <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>
<ul>
<li>where <span class="math inline">\(\mu_1\)</span> is the population mean of group 1</li>
<li>and <span class="math inline">\(\mu_2\)</span> is the population mean of group 2<br />
</li>
</ul></li>
<li>Or the <strong>alternative hypothesis</strong> which states the groups means <strong>are not equivalent</strong> and is written as: <span class="math inline">\(H_1: \mu_1 \ne \mu_2\)</span>.</li>
</ol>
<p>Using the techniques you read about earlier and in previous labs, today you will learn how to test the null hypothesis of no difference between two independent groups. We will first do this using a <strong>permutation test</strong> before looking at other tests in later labs.</p>
<p>A permutation test is a basic inferential procedure that involves a reshuffling of group labels or values to create new possible outcomes of the data you collected to see how your original mean difference compares to all possible outcomes. The test can in fact be applied in many situations, this is just one, and it provides a good starting place for understanding hypothesis testing. The steps for the exercise below, and really the logic of a permutation test for two independent groups, are:</p>
<ol style="list-style-type: decimal">
<li>Calculate the real difference <span class="math inline">\(D_{orig}\)</span> between the means of two groups (e.g. Mean of A minus Mean of B).</li>
<li>Randomly shuffle the group labels (i.e. which group each participant belonged to - A or B) and re-calculate the difference, <span class="math inline">\(D&#39;\)</span>.</li>
<li>Repeat step 2 <span class="math inline">\(N_{r}\)</span> times, where <span class="math inline">\(N_r\)</span> is a large number (typically greater than 1000), storing each <span class="math inline">\(D_i&#39;\)</span> value to form a null hypothesis distribution.</li>
<li>Locate the difference you observed in step 1 (the real difference) on the null hypothesis distribution of all possible differences.</li>
<li>Decide whether the original difference is sufficiently extreme to reject the null hypothesis of no difference (<span class="math inline">\(H_0\)</span>).</li>
</ol>
<p>This logic works because if the null hypothesis is true (there is no difference between the groups) then the labeling of the observations/participants into groups is arbitrary, and we can rearrange the labels in order to estimate the likelihood of our original difference under the <span class="math inline">\(H_0\)</span>. In other words if you know the original value of the difference between two groups (or the true difference) falls in the middle of your permuted distribution then there is no significant difference between the two groups. If however the original difference falls in the tail of the permuted distribution then there might be a significant difference depending on how far into the tail it falls.</p>
<p>Let’s get started!</p>
</div>
<div id="Ch5InClassQueT1" class="section level3">
<h3><span class="header-section-number">11.2.9</span> Step 1: Load in Add-on Packages and Data</h3>
<p>1.1. Open a new script and call the <code>tidyverse</code> into your library.</p>
<p>1.2. Now type the statement <code>set.seed(1011)</code> at the top of your script after your library call and run it. (This ‘seeds’ the random number generator so that you will get the same results as everyone else. The number 1011 is a bit random but if everyone uses it then we all get the same outcome. Different seeds give different outcomes)</p>
<p>1.3. <a href="perm_data.csv" download>Download the data file here.</a> and read the data in <code>perm_data.csv</code> into a variable called <code>dat</code>.</p>
<p>1.4. Let’s give every participant a participant number as well by adding a new column to <code>dat</code>. Something like this would work: <code>mutate(subj_id = row_number())</code></p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
<p>
Something to do with <code>library()</code>
</p>
</li>
<li>
<p>
<code>set.seed(1011)</code>
</p>
</li>
<li>
<p>
Something to do with <code>read_csv()</code>
</p>
</li>
<li>
<p>
pipe <code>%&gt;%</code> on the mutate line shown
</p>
</li>
</ol>
</div>
</div>
<div class="solution">
<button>
Portfolio Point - Different uses of row_number
</button>
<div class="info">
<p>
You will see that in the example here to put a row number for each of the participants we do not have to state the number of participants we have. In the Preclass however we did. What is the difference? Well, in the Preclass we were making a tibble and trying to create a column in that tibble using <code>row_numbers</code>. If you want to do that you have to state the number of rows, e.g. <code>1:20</code>. However, in this example in the lab today the tibble already exists, we are just adding to it. If that is the case then you can just mutate on a column of row numbers without stating the number of participants. In summary:
</p>
<ul>
<li>
When creating the tibble, state the number of participants in <code>row_numbers()</code>.
</li>
<li>
If tibble already exists, just mutate on <code>row_numbers()</code>. No need for specific numbers.
</li>
</ul>
</div>
</div>
<p>Have a look at the resulting tibble, <code>dat</code>.</p>
<ul>
<li>The column <code>Y</code> is your dependent variable (DV)</li>
<li>The column <code>group</code> is your independent variable (IV).</li>
<li>The columns <code>subj_id</code> is the participant number.</li>
</ul>
</div>
<div id="Ch5InClassQueT2" class="section level3">
<h3><span class="header-section-number">11.2.10</span> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></h3>
<p>We now need to write a pipeline of five functions that calculates the mean difference between the groups in <code>dat</code>, Group A minus Group B. Broken down into steps this would be:</p>
<p>2.1.1. Use a pipe of two <code>dplyr</code> one-table verbs (e.g. Lab 2) to create a tibble where each row contains the mean of one of the groups. Name the column storing the means as <code>m</code>.</p>
<p>2.1.2. Continue the pipe to <code>spread()</code> your data from long to wide format, based on the columns <code>group</code> and <code>m</code>.</p>
<p>2.1.3. Now add a pipe that <strong>creates</strong> a new column in this wide dataset called <code>diff</code> which is the value of group A’s mean minus group B’s mean.</p>
<p>2.1.4. Pull out the value in <code>diff</code> (the mean of group A minus the mean of group B) to finish the pipe.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
<code>dat %&gt;%</code>
</p>
<p>
<code>group_by(?) %&gt;%</code>
</p>
<p>
<code>summarise(m = ?) %&gt;%</code>
</p>
<p>
<code>spread(group, m) %&gt;%</code>
</p>
<p>
<code>mutate(diff = ? - ?) %&gt;%</code>
</p>
<p>
<code>pull(?)</code>
</p>
</div>
</div>
<ul>
<li>Check that your value for <code>d_orig</code> is correct, without using the solution, by typing your <code>d_orig</code> value to two decimal places in the box. Include the sign, e.g. -1.23. The box will go green if you are correct. <input class='solveme nospaces' size='10' data-answer='["-7.39"]'/></li>
</ul>
<p>The above steps have created a pipeline of five functions to get one value. Nice! We now need to turn this into a function because we are going to be permuting the data set (specifically the grouping labels) and re-calculating the difference many, many times.</p>
<p>2.2. Wrap your pipeline in a function called <code>calc_diff</code> but swap <code>dat</code> for <code>x</code>. This function will take a single argument named <code>x</code>, where <code>x</code> is the tibble that you want to calculate group means from. As in the previous step, the function will return a single value which is the difference between the group means. The start will look like this below:</p>
<pre class="sourceCode r"><code class="sourceCode r">calc_diff &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  x <span class="op">%&gt;%</span>.....
}</code></pre>
<div class="solution">
<button>
Helpful Hint
</button>
<pre class="sourceCode r"><code class="sourceCode r">calc_diff &lt;-<span class="st"> </span><span class="cf">function</span>(x) {
  x <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">group_by</span>(group) <span class="op">%&gt;%</span>
<span class="st">    </span>the_rest_of_your_pipe...
}</code></pre>
</div>
<p>2.3. Now call your new function where <code>x</code> = <code>dat</code> as the argument and store the result in a new variable called <code>d_orig</code>. Make sure that your function returns the same value as you got above and that your function returns a single value rather than a tibble. You can test this: <code>is.tibble(d_orig)</code> should give you <code>FALSE</code> and <code>is.numeric(d_orig)</code> should give you <code>TRUE</code>.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<pre class="sourceCode r"><code class="sourceCode r">d_orig &lt;-<span class="st"> </span><span class="kw">function_name</span>(<span class="dt">x =</span> data_name) 
<span class="co"># or</span>
d_orig &lt;-<span class="st"> </span><span class="kw">function_name</span>(data_name)

<span class="co"># Then type the following in the Console and look at answer:</span>

<span class="kw">is.tibble</span>(d_orig)
<span class="co"># True (is a tibble) or False (is not a tibble)</span>

<span class="kw">is.numeric</span>(d_orig)
<span class="co"># True (is numeric) or False (is not numeric; it is a character or integer instead.)</span></code></pre>
</div>
<p>So we now have the original difference between the groups stored in <code>d_orig</code>. Next we need to create a distribution of all possible differences to see where our original difference lies in this distribution. But first we need to shuffle the <code>group</code> letters (A or B) in our dataset and find the difference…a few hundred times!</p>
</div>
<div id="Ch5InClassQueT3" class="section level3">
<h3><span class="header-section-number">11.2.11</span> Step 3: Permute the Group Labels</h3>
<p>3.1. Create a new function called <code>permute()</code> that takes as input a dataset <code>x</code> and returns the same dataset transformed such that the group labels (the values in the column <code>group</code>) are shuffled: started below for you. This will require using the <code>sample()</code> function within a <code>mutate()</code>. You have used <code>mutate()</code> twice already today and you saw how to <code>sample()</code> <strong>letters</strong> in the PreClass.</p>
<pre class="sourceCode r"><code class="sourceCode r">permute &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  x <span class="op">%&gt;%</span>.....
}</code></pre>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Might be easier to think of these steps in reverse.
</p>
<ol style="list-style-type: decimal">
<li>
<p>
Start with a <code>mutate()</code> function that rewrites the column <code>group</code> every time you run it, e.g. <code>dat %&gt;% mutate(variable = sample(variable))</code>
</p>
</li>
<li>
<p>
Now put that into your <code>permute()</code> function making the necessary adjustments to the code so it starts <code>x %&gt;%…</code>. Again <code>x</code> should be in the function and not <code>dat</code>. ")
</p>
</li>
</ol>
</div>
</div>
<p>3.2. Try out your new <code>permute()</code> function by calling it on <code>dat</code> (i.e. <code>x = dat</code>) a few times. You should see the group labels in the <code>group</code> column changing randomly. The most common mistake is that people mutate a new column by mispelling <code>group</code>. You want to overwrite/change the information in the <code>group</code> column not make a new one, so be careful with the spelling.</p>
<p>Now would be an excellent time to spend five minutes as a group recapping what you are doing.</p>
<ul>
<li>You have the original difference between groups.</li>
<li>You have a function that calculates and stores this difference.</li>
<li>You have a function that reshuffles the labels of the group.</li>
</ul>
<p>Do you understand why? If not, go back to the principles of the permutation test at the start of the lab then read on…</p>
</div>
<div id="Ch5InClassQueT4" class="section level3">
<h3><span class="header-section-number">11.2.12</span> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</h3>
<p>Now that we have the original difference and our two functions, one to shuffle group labels and one to calculate the difference between two groups, we need to actually create the distribution of possible differences and see where the original difference lies in it.</p>
<p>4.1.1. Write a <strong>a single pipeline</strong> that takes <code>dat</code> as the input, permutes the group labels with a call to your function <code>permute()</code>, and then calculates the difference in means between these new groups with a call to your function <code>calc_diff()</code>.</p>
<p>4.1.2. Run this line manually a few times and watch the resulting value change as the labels get permuted.</p>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Think about verbalising your pipelines. In a single pipeline:
</p>
<ol style="list-style-type: decimal">
<li>
I want to permute the data into two new groups.
</li>
<li>
Then I want to calculate the difference between these two new groups.
</li>
</ol>
<p>
The functions you have created do these steps. You just have to put them in order and pipe the data through it.
</p>
</div>
</div>
<p>4.2. Now take your pipeline of functions and repeat it 1000 times using the <code>replicate()</code> function. Store the output in a variable called <code>nhd</code>. <code>nhd</code> will contain 1000 values where each value is the mean difference of each of the 1000 random permutations of the data. (<strong>Warning:</strong> This will probably take a while to run, perhaps 10 seconds.)</p>
<div class="solution">
<button>
Helpful Hint
</button>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># replace expression with the pipeline you created in 4.1</span>
nhd &lt;-<span class="st"> </span><span class="kw">replicate</span>(times, expression)</code></pre>
</div>
<p>You now have 1000 possible values of the difference between the permuted groups A and B - your permuted distribution.</p>
<p>4.3 Let’s visualise this distribution through a frequency histogram of the values in <code>nhd</code>. This shows us the likelihood of various mean differences under <span class="math inline">\(H_0\)</span>. One thing to note however is that <code>nhd</code> is not a <code>tibble</code> and <code>ggplot</code> needs it to be a <code>tibble</code>. You need to convert it. You might start by do something like:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> <span class="kw">tibble</span>(<span class="dt">x =</span> <span class="ot">NULL</span>), <span class="kw">aes</span>(x)) <span class="op">+</span><span class="st"> </span><span class="ot">NULL</span></code></pre>
<div class="solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Remember that <code>ggplot</code> works as: <code>ggplot(data, aes(x)) + geom…</code>. Here you need to convert <code>nhd</code> into a tibble and put that in as your data. Look at the example above and keep in mind that, in this case, the first NULL could be replaced with the data in <code>nhd</code>.
</p>
</div>
</div>
<ul>
<li>Looking at the histogram, visually locate where your original value would sit on this distribution. Would it be extreme, in the tail, or does it look rather common, in the middle? <select class='solveme' data-answer='["is in the tail so looks extreme"]'> <option></option> <option>is in the middle so looks common</option> <option>is in the tail so looks extreme</option></select></li>
</ul>
<p>Before moving on stop to think about what this means - that the difference between the two original groups is rather uncommon in this permuted distribution, i.e. is in the tails! Again, if unsure, go back to the principles of NHST or discuss it with your tutor!</p>
</div>
<div id="Ch5InClassQueT5" class="section level3">
<h3><span class="header-section-number">11.2.13</span> Step 5: Compare the Observed Mean Difference to the NHD</h3>
<p>If the null hypothesis is false, and there is a real difference between the groups, then the difference in means we observed for the original data (<code>d_orig</code>) should be somewhere in either tail of the null-hypothesis distribution we just estimated; it should be an “extreme” value. How can we test this beyond a visual inspection?</p>
<p>First we have to decide on a false positive (Type I error) rate which is the rate at which we will falsely reject <span class="math inline">\(H_0\)</span> when it is true. This rate is referred to by the Greek letter <span class="math inline">\(\alpha\)</span> (“alpha”). Let’s just use the conventional level used in Psychology: <span class="math inline">\(\alpha = .05\)</span>.</p>
<p>So the question we must ask is, if the null hypothesis was true, what would be the probability of getting a difference in means as extreme as the one we observed in the original data? We will label this probability <code>p</code>.</p>
<p>Take a few moments to see if you can figure out how you might compute <code>p</code> from the data before we show you how. We will then show you the process in the next few, final, steps.</p>
<p>5.1. Replace the NULLS in the code below to create a logical vector which states TRUE for all values of <code>nhd</code> greater than or equal to <code>d_orig</code> regardless of sign. <strong>Note:</strong> A logical vector is one that returns TRUE when the expression is true and FALSE when the expression is false.</p>
<pre class="sourceCode r"><code class="sourceCode r">lvec &lt;-<span class="st"> </span><span class="kw">abs</span>(<span class="ot">NULL</span>) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">abs</span>(<span class="ot">NULL</span>)</code></pre>
<div class="solution">
<button>
Portfolio Point - abs and the case of one or two tails
</button>
<div class="info">
<p>
In the code above, the function <code>abs()</code> says to ignore the sign and use the absolute value. For instance, if <code>d_orig = -7</code>, then <code>abs(d_orig) = 7</code>. Why do we do this here? Can you think why you want to know how extreme your value is in this distribution regardless of whether the value is positive or negative?
</p>
<p>
The answer relates to whether you are testing in one or two tails of your distribution; the positive side, the negative side, or both. You will have heard in your lectures of one or two-tailed tests. Most people would say to run two-tailed tests. This means looking at the negative and positive tails of the distribution to see if our original value is extreme, and the simplest way to do this is to ignore the sign of the values and treat both sides equally. If you wanted to only test one-tail, say that your value is extreme to the negative side of the tail, then you would not use the <code>abs()</code> and set the expression to make sure you only find values less than your original value. To test only on the positive side of the distribution, make sure you only get values higher than the original. But for now we will mostly look at two-tailed tests.
</p>
</div>
</div>
<p>5.2. Replace the NULL in the code below to <code>sum()</code> the <code>lvec</code> vector to get the total number of values equal to or greater than our original difference, <code>d_orig</code>. Fortunately R is fine with summing TRUEs and FALSEs so you do not have to convert the data at all.</p>
<pre class="sourceCode r"><code class="sourceCode r">n_exceeding_orig &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
<p>5.3. Replace the NULL in the code below to calculate the probability of finding a value of <code>d_orig</code> in our <code>nhd</code> distribution by dividing <code>n_exceeding_orig</code>, the number of values greater than or equal to your original value, by the <code>length()</code> of your whole distribution <code>nhd</code>. <strong>Note: the length of <code>nhd</code> is the same as the number of replications we ran. Using code reduces the chance of human error</strong></p>
<pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="ot">NULL</span></code></pre>
<p>5.4. Finally, complete the sentence below determining if the original value was extreme or not in regards to the distribution. Use inline coding, shown in Lab 1, to replace the <code>XXX</code>s. For example, when formatted without the space before the first r, <code>r length(nhd)</code> would present as 1000.</p>
<p><strong>" The difference between Group A and Group B (M = <code>XXX</code>) was found to be have a probability of p = <code>XXX</code>. This means that the original mean difference was …… and the null hypothesis is ….." </strong></p>
<div id="finished-13" class="section level4">
<h4><span class="header-section-number">11.2.13.1</span> Finished!</h4>
<p>Well done in completing this lab. Let’s recap before finishing. We had two groups, A and B, that we had tested in an experiment. We calculated the mean difference between A and B and wanted to know if this was a significant difference. To test this we created a distribution of all possible differences between A and B using the premise of permutation tests and then found the probability of our original value in that permuted distribution. The more extreme the value in a distribution the more likely that the difference is significant. And that is exactly what we found; an <span class="math inline">\(\alpha &lt; .05\)</span>. Next time we will look at using functions and inferential tests to perform this analysis but by understanding the above you now know how probability is determined.</p>
</div>
</div>
</div>
<div id="non-parametric-tests" class="section level2">
<h2><span class="header-section-number">11.3</span> Non-parametric tests</h2>
</div>
<div id="simulation" class="section level2">
<h2><span class="header-section-number">11.4</span> Simulation</h2>
</div>
<div id="rtweet" class="section level2">
<h2><span class="header-section-number">11.5</span> rtweet</h2>
<div id="packages-1" class="section level3">
<h3><span class="header-section-number">11.5.1</span> Packages</h3>
<p>In order to run these analyses you will need <code>tidyverse</code> for data wrangling,<code>rtweet</code> for getting the twitter data, <code>tidytext</code> for working with text, <code>knitr</code> for tidy tables, and <code>igraph</code> and <code>ggraph</code> for making pretty network plots.</p>
<p>In order to get data from Twitter you will need to have a twitter account and gain access to Twitter’s API. There are instructions <a href="https://rtweet.info/">for doing so here</a>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(knitr)
<span class="kw">library</span>(tidytext)
<span class="kw">library</span>(rtweet)
<span class="kw">library</span>(igraph)
<span class="kw">library</span>(ggraph)</code></pre>
</div>
<div id="hashtag-search" class="section level3">
<h3><span class="header-section-number">11.5.2</span> Hashtag search</h3>
<p>We can use rtweet to search for all tweets containing particular words or hashtags. It will return the last 18,000 tweets and only from the last 6-9 days. Be careful, there is a 15 minute time-out which means you can only retrieve 18,000 tweets every 15 minutes (there are various limits on what Twitter allows you to do with the data).</p>
<p>First, let’s search for all tweets that contain #GoT and #ForTheThrone.</p>
<p>There are various arguments to the <code>search_tweets</code> function, you can specify how many tweets you want to retrive with <code>n</code>, whether retweets should be included in the search results with <code>include_rts</code> and you can also specify the language of the user’s account with <code>lang</code>. Note that this doesn’t tell you what language the tweets are written in, only that the account language is set to e.g., English, so it’s not perfect. For additional options, see the help documentation.</p>
<pre class="sourceCode r"><code class="sourceCode r">tweets &lt;-<span class="st"> </span><span class="kw">search_tweets</span>(<span class="dt">q =</span> <span class="st">&quot;#GoT OR #ForTheThrone&quot;</span>, <span class="dt">n =</span> <span class="dv">18000</span>, <span class="dt">include_rts =</span> <span class="ot">FALSE</span>, <span class="dt">lang =</span> <span class="st">&quot;en&quot;</span>)</code></pre>
</div>
<div id="data-wrangling" class="section level3">
<h3><span class="header-section-number">11.5.3</span> Data wrangling</h3>
<p>The output of <code>search_tweets()</code> is a list which makes it difficult to share. We need to do a little bit of tidying to turn it into a tibble, and additionally there’s a lot of data and we don’t need it all. I’m also going to add a tweet counter which will help when we move between wide and long-form. <code>rtweet</code> provides a huge amount of data, more than we’re going to use in this example so have a look through to see what you have access to - there are some great examples of how this data can be used <a href="https://mkearney.github.io/nicar_tworkshop/">here</a> and <a href="https://rud.is/books/21-recipes/index.html">here</a> .</p>
<p>In the following code, I have added an identifier column <code>tweet_number</code> and then selected <code>text</code> (the actual text of the tweets), <code>created_at</code> (the timestamp of the tweet), <code>source</code> (iphone/android etc), <code>followers_count</code> (how many followers the accounts the tweets came from have), and <code>country</code> (like <code>lang</code>, the is the country specified on the account, not necessarily the country the tweeter is in).</p>
<pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span>tweets <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">tweet_number =</span> <span class="kw">row_number</span>())<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(tweet_number, text, created_at, source, followers_count, country)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">as_tibble</span>()</code></pre>
<p>You can <a href="all_data.zip" download>download this file here</a> so that you can reproduce my exact analyses (or you can use your own, but the results will look a bit different).</p>
<p>The first thing we need to do is tidy up the text by getting rid of punctuation, numbers, and links that aren’t of any interest to us. We can also remove the hashtags because we don’t want those to be included in any analysis. This code uses <strong>regular expressions</strong> which quite frankly make very little sense to me, I have copied and pasted this code from the Tidy Text book.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;[^</span><span class="ch">\x01</span><span class="st">-</span><span class="ch">\x7F</span><span class="st">]&quot;</span>, <span class="st">&quot;&quot;</span>),
         <span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;#GoT&quot;</span>, <span class="st">&quot;&quot;</span>),
         <span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;#ForTheThrone&quot;</span>, <span class="st">&quot;&quot;</span>),
         <span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;</span><span class="ch">\\</span><span class="st">.|[[:digit:]]+&quot;</span>, <span class="st">&quot;&quot;</span>),
         <span class="dt">text =</span> <span class="kw">str_replace_all</span>(text, <span class="st">&quot;https|amp|t.co&quot;</span>, <span class="st">&quot;&quot;</span>))</code></pre>
</div>
<div id="time-series" class="section level3">
<h3><span class="header-section-number">11.5.4</span> Time series</h3>
<p>We can plot when the tweets were sent. This is somewhat uninteresting because it’s no longer airing, but it’s worth highlighting this as a feature. If you were watching live, you could use this to see the spikes in tweets when people are watching each episode live (different timezones will muddle this a little, you could filter by <code>country</code> perhaps).</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ts_plot</span>(tweets, <span class="dt">by =</span> <span class="st">&quot;1 hours&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-22"></span>
<img src="11-supplementary_files/figure-html/unnamed-chunk-22-1.png" alt="Time series plot by hour" width="100%" />
<p class="caption">
Figure 11.1: Time series plot by hour
</p>
</div>
<p>You can change the time interval with the <code>by</code> argument and you can also change the time zone. <code>ts_plot</code> creates a <code>ggplot</code> object so you can also add the usual ggplot layers to customise apperance.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ts_plot</span>(tweets, <span class="dt">by =</span> <span class="st">&quot;10 mins&quot;</span>, <span class="dt">tz =</span> <span class="st">&quot;GMT&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_minimal</span>()<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Number of tweets&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-23"></span>
<img src="11-supplementary_files/figure-html/unnamed-chunk-23-1.png" alt="Time series plot by 10 minute intervals" width="100%" />
<p class="caption">
Figure 11.2: Time series plot by 10 minute intervals
</p>
</div>
</div>
<div id="tidy-text-and-word-frequencies" class="section level3">
<h3><span class="header-section-number">11.5.5</span> Tidy text and word frequencies</h3>
<p>First, we can produce frequency plots for words used in all tweets to see which words are used most often in #GoT and #ForTheThrone tweets. To do this, we have to create a tidy dataset, just like we do when working with numerical data. We’re going to use the <code>unnest_tokens</code> function from <code>tidytext</code> which will separate each word on to a new line, something similar to like using <code>gather</code> (or <code>pivot_longer</code> as it will soon be known). Helpfully, this function will also convert all of our words to lower case which makes them a bit easier to work with.</p>
<p>The second part of the code removes all the stop words. Stop words are words that are commonly used but are of not real interest, for example function words like “the”, “a”, “it”. You can make your own list but <code>tidytext</code> helpfully comes with several databases. Look at the help documentation if you want to know more about these or change the defaults.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create tidy text</span>
dat_token &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st">  </span>
<span class="st">  </span><span class="kw">unnest_tokens</span>(word, text) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">anti_join</span>(stop_words, <span class="dt">by =</span> <span class="st">&quot;word&quot;</span>)</code></pre>
<p>We can plot the 20 most frequent words used in all the tweets.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_token<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">na.omit</span>()<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(word, <span class="dt">sort =</span> <span class="ot">TRUE</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">head</span>(<span class="dv">20</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">word =</span> <span class="kw">reorder</span>(word, n))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> word, <span class="dt">y =</span> n))<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>()<span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-25"></span>
<img src="11-supplementary_files/figure-html/unnamed-chunk-25-1.png" alt="Most frequent words" width="100%" />
<p class="caption">
Figure 11.3: Most frequent words
</p>
</div>
<p>There’s quite a few words here that aren’t that helpful to us so it might be best to get rid of them (essentially we’re building our own list of stop words).</p>
<pre class="sourceCode r"><code class="sourceCode r">custom_stop &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;gameofthrones&quot;</span>, <span class="st">&quot;hbo&quot;</span>, <span class="st">&quot;season&quot;</span>, <span class="st">&quot;game&quot;</span>, <span class="st">&quot;thrones&quot;</span>, <span class="st">&quot;lol&quot;</span>, <span class="st">&quot;tco&quot;</span>, <span class="st">&quot;https&quot;</span>, <span class="st">&quot;watch&quot;</span>, <span class="st">&quot;watching&quot;</span>, <span class="st">&quot;im&quot;</span>, <span class="st">&quot;amp&quot;</span>)

dat_token &lt;-<span class="st"> </span>dat_token <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span>word <span class="op">%in%</span><span class="st"> </span>custom_stop)</code></pre>
<p>Now we can try plotting the words again and make them pretty.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_token<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">na.omit</span>()<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(word, <span class="dt">sort =</span> <span class="ot">TRUE</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">head</span>(<span class="dv">20</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">word =</span> <span class="kw">reorder</span>(word, n))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> word, <span class="dt">y =</span> n, <span class="dt">fill =</span> word))<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">show.legend =</span> <span class="ot">FALSE</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_viridis</span>(<span class="dt">discrete =</span> <span class="ot">TRUE</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-27"></span>
<img src="11-supplementary_files/figure-html/unnamed-chunk-27-1.png" alt="Most frequent words (edited)" width="100%" />
<p class="caption">
Figure 11.4: Most frequent words (edited)
</p>
</div>
<p>To be honest, this isn’t that interesting because it’s so general, it might be more interesting to see how often each of the main characters are being mentioned.</p>
<p>One problem is that people on the internet are terrible at spelling and we need to have the exact spellings which means that for Daenerys, Jon, and Jaime, the chances that people will have spelled their names wrong is quite high (as my level 2 students who watched me live code the first version of this will attest) so first we’re going to correct those.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_token2 &lt;-<span class="st"> </span>dat_token <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">word =</span> <span class="kw">recode</span>(word, <span class="st">&quot;khaleesi&quot;</span> =<span class="st"> &quot;daenerys&quot;</span>,
                       <span class="st">&quot;dany&quot;</span> =<span class="st"> &quot;daenerys&quot;</span>,
                       <span class="st">&quot;jamie&quot;</span> =<span class="st"> &quot;jaime&quot;</span>,
                       <span class="st">&quot;john&quot;</span> =<span class="st"> &quot;jon&quot;</span>))

characters &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;jon&quot;</span>, <span class="st">&quot;daenerys&quot;</span>, <span class="st">&quot;bran&quot;</span>, <span class="st">&quot;arya&quot;</span>, <span class="st">&quot;sansa&quot;</span>, <span class="st">&quot;tyrion&quot;</span>, <span class="st">&quot;cersei&quot;</span>, <span class="st">&quot;jaime&quot;</span>)</code></pre>
<p>Now we can plot a count of how many times each name has been mentioned.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_token2 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(word <span class="op">%in%</span><span class="st"> </span>characters)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(word, <span class="dt">sort =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">word =</span> <span class="kw">reorder</span>(word, n))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> word, <span class="dt">y =</span> n, <span class="dt">fill =</span> word)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">show.legend =</span> <span class="ot">FALSE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Number of mentions&quot;</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">name =</span> <span class="st">&quot;Character&quot;</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_viridis</span>(<span class="dt">discrete =</span> <span class="ot">TRUE</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-29"></span>
<img src="11-supplementary_files/figure-html/unnamed-chunk-29-1.png" alt="Frequecy of mentions for each character" width="100%" />
<p class="caption">
Figure 11.5: Frequecy of mentions for each character
</p>
</div>
</div>
<div id="bigram-analysis" class="section level3">
<h3><span class="header-section-number">11.5.6</span> Bigram analysis</h3>
<p>Rather than looking at individual words we can look at what words tend to co-occur. We want to use the data set where we’ve corrected the spelling so this is going to require us to transform from long to wide and then back to long because the night is dark and full of terror. DID YOU SEE WHAT I DID THERE.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_bigram &lt;-<span class="st"> </span>dat_token2 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(tweet_number) <span class="op">%&gt;%</span><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">text =</span> <span class="kw">str_c</span>(word, <span class="dt">collapse =</span> <span class="st">&quot; &quot;</span>))<span class="op">%&gt;%</span><span class="st"> </span><span class="co"># this puts it back into wide-form</span>
<span class="st">  </span><span class="kw">unnest_tokens</span>(bigram, text, <span class="dt">token =</span> <span class="st">&quot;ngrams&quot;</span>, <span class="dt">n =</span> <span class="dv">2</span>, <span class="dt">collapse =</span> <span class="ot">FALSE</span>)<span class="op">%&gt;%</span><span class="st"> </span><span class="co"># and then this turns it into bigrams in a tidy format</span>
<span class="st">  </span><span class="kw">na.omit</span>()

dat_bigram <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(bigram, <span class="dt">sort =</span> <span class="ot">TRUE</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">head</span>(<span class="dv">10</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>)</code></pre>
<table>
<thead>
<tr class="header">
<th align="center">bigram</th>
<th align="center">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">freefolk gt</td>
<td align="center">165</td>
</tr>
<tr class="even">
<td align="center">togive freefolk</td>
<td align="center">164</td>
</tr>
<tr class="odd">
<td align="center">se tvtime</td>
<td align="center">103</td>
</tr>
<tr class="even">
<td align="center">watched episode</td>
<td align="center">88</td>
</tr>
<tr class="odd">
<td align="center">episode se</td>
<td align="center">86</td>
</tr>
<tr class="even">
<td align="center">ice fire</td>
<td align="center">85</td>
</tr>
<tr class="odd">
<td align="center">song ice</td>
<td align="center">81</td>
</tr>
<tr class="even">
<td align="center">jonsnow daenerys</td>
<td align="center">73</td>
</tr>
<tr class="odd">
<td align="center">bracelets fef</td>
<td align="center">71</td>
</tr>
<tr class="even">
<td align="center">connected matter</td>
<td align="center">71</td>
</tr>
</tbody>
</table>
<p>Again there’s a bit of nonsense here and it’s a bit uninteresting but it’s worth highlighting this is something you can do. Now that we’ve got our bigrams we can plot these to see the connections between the different words. First, we’re going to use <code>separate</code> to put the two words into different columns, then we’ll count them up and plot them. If you want more information about this see the <a href="https://www.tidytextmining.com/ngrams.html">tidytext book online</a> as I am entirely cribbing this from that book. The plot requires the packages <code>igraph</code> and <code>ggraph</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">bigrams_separated &lt;-<span class="st"> </span>dat_bigram <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">separate</span>(bigram, <span class="kw">c</span>(<span class="st">&quot;word1&quot;</span>, <span class="st">&quot;word2&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)

<span class="co"># new bigram counts:</span>
bigram_counts &lt;-<span class="st"> </span>bigrams_separated <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">count</span>(word1, word2, <span class="dt">sort =</span> <span class="ot">TRUE</span>)

bigram_counts

<span class="co"># filter for only relatively common combinations (more than 20 occurances)</span>
bigram_graph &lt;-<span class="st"> </span>bigram_counts <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(n <span class="op">&gt;</span><span class="st"> </span><span class="dv">20</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">graph_from_data_frame</span>()

<span class="co"># make a pretty network plot</span>

<span class="kw">ggraph</span>(bigram_graph, <span class="dt">layout =</span> <span class="st">&quot;fr&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_edge_link</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_node_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_node_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> name), <span class="dt">vjust =</span> <span class="dv">1</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">theme_void</span>()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-31"></span>
<img src="11-supplementary_files/figure-html/unnamed-chunk-31-1.png" alt="Network graph of bigrams" width="100%" />
<p class="caption">
Figure 11.6: Network graph of bigrams
</p>
</div>
<pre><code>## # A tibble: 30,134 x 3
##    word1     word2        n
##    &lt;chr&gt;     &lt;chr&gt;    &lt;int&gt;
##  1 freefolk  gt         165
##  2 togive    freefolk   164
##  3 se        tvtime     103
##  4 watched   episode     88
##  5 episode   se          86
##  6 ice       fire        85
##  7 song      ice         81
##  8 jonsnow   daenerys    73
##  9 bracelets fef         71
## 10 connected matter      71
## # ... with 30,124 more rows</code></pre>
<p>I am still figuring out how to customise the aesthetics of <code>ggraph</code>.</p>
</div>
<div id="sentiment-analysis" class="section level3">
<h3><span class="header-section-number">11.5.7</span> Sentiment analysis</h3>
<p>Sentiment analyses look at whether the expressed opinion in a bit of text is positive, negative, or neutral, using information from databases about the valance of different words. We can perform a sentiment analysis on the tweets that contain each character’s name to see whether e.g., Jon is mentioned in tweets that are largely positive or if Jaime is mentioned in tweets that are largely negative.</p>
<p>To do this, we first need to do a bit of wrangling. We’re going to transform it back to wide-form, then we’re going to add in in a column that says whether each character was mentioned in the tweet, then we’re going to transform it back to long-form.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_mentions &lt;-<span class="st"> </span>dat_token2 <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(tweet_number) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">text =</span> <span class="kw">str_c</span>(word, <span class="dt">collapse =</span> <span class="st">&quot; &quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">jon =</span> <span class="kw">case_when</span>(<span class="kw">str_detect</span>(text, <span class="st">&quot;.jon&quot;</span>) <span class="op">~</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">FALSE</span>),
         <span class="dt">daenerys =</span> <span class="kw">case_when</span>(<span class="kw">str_detect</span>(text, <span class="st">&quot;.daenerys&quot;</span>) <span class="op">~</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">FALSE</span>),
         <span class="dt">bran =</span> <span class="kw">case_when</span>(<span class="kw">str_detect</span>(text, <span class="st">&quot;.bran&quot;</span>) <span class="op">~</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">FALSE</span>),
         <span class="dt">arya =</span> <span class="kw">case_when</span>(<span class="kw">str_detect</span>(text, <span class="st">&quot;.arya&quot;</span>) <span class="op">~</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">FALSE</span>),
         <span class="dt">sansa =</span> <span class="kw">case_when</span>(<span class="kw">str_detect</span>(text, <span class="st">&quot;.sansa&quot;</span>) <span class="op">~</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">FALSE</span>),
         <span class="dt">tyrion =</span> <span class="kw">case_when</span>(<span class="kw">str_detect</span>(text, <span class="st">&quot;.tyrion&quot;</span>) <span class="op">~</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">FALSE</span>),
         <span class="dt">cersei =</span> <span class="kw">case_when</span>(<span class="kw">str_detect</span>(text, <span class="st">&quot;.cersei&quot;</span>) <span class="op">~</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">FALSE</span>),
         <span class="dt">jaime =</span> <span class="kw">case_when</span>(<span class="kw">str_detect</span>(text, <span class="st">&quot;.jaime&quot;</span>) <span class="op">~</span><span class="st"> </span><span class="ot">TRUE</span>, <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">FALSE</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">unnest_tokens</span>(word, text) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">anti_join</span>(stop_words, <span class="dt">by =</span> <span class="st">&quot;word&quot;</span>)</code></pre>
<p>Once we’ve done this, we can then run a sentiment analysis on the tweets for each character. I still haven’t quite cracked iteration so this code is a bit repetitive, if you can give me the better way of doing this that’s less prone to copy and paste errors, please do.</p>
<pre class="sourceCode r"><code class="sourceCode r">jon &lt;-<span class="st"> </span>dat_mentions <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(jon)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(<span class="dt">index =</span> tweet_number, sentiment) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive <span class="op">-</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">character =</span> <span class="st">&quot;jon&quot;</span>)

daenerys &lt;-<span class="st"> </span>dat_mentions <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(daenerys <span class="op">==</span><span class="st"> &quot;TRUE&quot;</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(<span class="dt">index =</span> tweet_number, sentiment) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive <span class="op">-</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">character =</span> <span class="st">&quot;daenerys&quot;</span>)


bran &lt;-<span class="st"> </span>dat_mentions <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(bran <span class="op">==</span><span class="st"> &quot;TRUE&quot;</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(<span class="dt">index =</span> tweet_number, sentiment) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive <span class="op">-</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">character =</span> <span class="st">&quot;bran&quot;</span>)

arya &lt;-<span class="st"> </span>dat_mentions <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(arya <span class="op">==</span><span class="st"> &quot;TRUE&quot;</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(<span class="dt">index =</span> tweet_number, sentiment) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive <span class="op">-</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">character =</span> <span class="st">&quot;arya&quot;</span>)

sansa &lt;-<span class="st"> </span>dat_mentions <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(sansa <span class="op">==</span><span class="st"> &quot;TRUE&quot;</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(<span class="dt">index =</span> tweet_number, sentiment) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive <span class="op">-</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">character =</span> <span class="st">&quot;sansa&quot;</span>)

tyrion &lt;-<span class="st"> </span>dat_mentions <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(tyrion <span class="op">==</span><span class="st"> &quot;TRUE&quot;</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(<span class="dt">index =</span> tweet_number, sentiment) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive <span class="op">-</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">character =</span> <span class="st">&quot;tyrion&quot;</span>)

cersei &lt;-<span class="st"> </span>dat_mentions <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(cersei <span class="op">==</span><span class="st"> &quot;TRUE&quot;</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(<span class="dt">index =</span> tweet_number, sentiment) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive <span class="op">-</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">character =</span> <span class="st">&quot;cersei&quot;</span>)

jaime &lt;-<span class="st"> </span>dat_mentions <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(jaime <span class="op">==</span><span class="st"> &quot;TRUE&quot;</span>)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">inner_join</span>(<span class="kw">get_sentiments</span>(<span class="st">&quot;bing&quot;</span>))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(<span class="dt">index =</span> tweet_number, sentiment) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(sentiment, n, <span class="dt">fill =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sentiment =</span> positive <span class="op">-</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">character =</span> <span class="st">&quot;jaime&quot;</span>)


dat_sentiment &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(jon,daenerys,bran,arya,sansa,tyrion,cersei,jaime) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(character) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">positive =</span> <span class="kw">sum</span>(positive),
            <span class="dt">negative =</span> <span class="kw">sum</span>(negative),
            <span class="dt">overall =</span> <span class="kw">sum</span>(sentiment))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">gather</span>(positive<span class="op">:</span>overall, <span class="dt">key =</span> type, <span class="dt">value =</span> score)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">type =</span> <span class="kw">factor</span>(type, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;positive&quot;</span>, <span class="st">&quot;negative&quot;</span>, <span class="st">&quot;overall&quot;</span>)))</code></pre>
<p>Now that we’ve done all that we can display a table of positive, negative and overall sentiment scores. Bear in mind that not all words have an associated sentiment score, particularly if they’re a non-standard usage of English (as an aside, this makes RuPaul’s Drag Race very difficult to analyse because tidytext will think a sickening death drop is a bad thing).</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_sentiment <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(type, score)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(overall))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>)</code></pre>
<table>
<thead>
<tr class="header">
<th align="center">character</th>
<th align="center">positive</th>
<th align="center">negative</th>
<th align="center">overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">jaime</td>
<td align="center">16</td>
<td align="center">29</td>
<td align="center">-13</td>
</tr>
<tr class="even">
<td align="center">tyrion</td>
<td align="center">15</td>
<td align="center">30</td>
<td align="center">-15</td>
</tr>
<tr class="odd">
<td align="center">sansa</td>
<td align="center">26</td>
<td align="center">44</td>
<td align="center">-18</td>
</tr>
<tr class="even">
<td align="center">cersei</td>
<td align="center">28</td>
<td align="center">55</td>
<td align="center">-27</td>
</tr>
<tr class="odd">
<td align="center">arya</td>
<td align="center">26</td>
<td align="center">58</td>
<td align="center">-32</td>
</tr>
<tr class="even">
<td align="center">bran</td>
<td align="center">32</td>
<td align="center">66</td>
<td align="center">-34</td>
</tr>
<tr class="odd">
<td align="center">daenerys</td>
<td align="center">62</td>
<td align="center">155</td>
<td align="center">-93</td>
</tr>
<tr class="even">
<td align="center">jon</td>
<td align="center">90</td>
<td align="center">185</td>
<td align="center">-95</td>
</tr>
</tbody>
</table>
<p>Because there’s diferent numbers of tweets for each character, it might be more helpful to convert it to percentages to make it easier to compare.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_sentiment <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(type, score)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(character)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total =</span> positive <span class="op">+</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">positive_percent =</span> positive<span class="op">/</span>total<span class="op">*</span><span class="dv">100</span>,
         <span class="dt">negative_percent =</span> negative<span class="op">/</span>total<span class="op">*</span><span class="dv">100</span>,
         <span class="dt">sentiment =</span> positive_percent <span class="op">-</span><span class="st"> </span>negative_percent)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(character, positive_percent, negative_percent, sentiment)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(sentiment))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>)</code></pre>
<table>
<thead>
<tr class="header">
<th align="center">character</th>
<th align="center">positive_percent</th>
<th align="center">negative_percent</th>
<th align="center">sentiment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">sansa</td>
<td align="center">37.14286</td>
<td align="center">62.85714</td>
<td align="center">-25.71429</td>
</tr>
<tr class="even">
<td align="center">jaime</td>
<td align="center">35.55556</td>
<td align="center">64.44444</td>
<td align="center">-28.88889</td>
</tr>
<tr class="odd">
<td align="center">cersei</td>
<td align="center">33.73494</td>
<td align="center">66.26506</td>
<td align="center">-32.53012</td>
</tr>
<tr class="even">
<td align="center">tyrion</td>
<td align="center">33.33333</td>
<td align="center">66.66667</td>
<td align="center">-33.33333</td>
</tr>
<tr class="odd">
<td align="center">jon</td>
<td align="center">32.72727</td>
<td align="center">67.27273</td>
<td align="center">-34.54545</td>
</tr>
<tr class="even">
<td align="center">bran</td>
<td align="center">32.65306</td>
<td align="center">67.34694</td>
<td align="center">-34.69388</td>
</tr>
<tr class="odd">
<td align="center">arya</td>
<td align="center">30.95238</td>
<td align="center">69.04762</td>
<td align="center">-38.09524</td>
</tr>
<tr class="even">
<td align="center">daenerys</td>
<td align="center">28.57143</td>
<td align="center">71.42857</td>
<td align="center">-42.85714</td>
</tr>
</tbody>
</table>
<p>They’re all quite negative because there’s no pleasing some people but there’s some face validity to the analysis given the order of the rankings. If you’d been watching this live you could have repeated this each episode to see how the reactions to the characters changes.</p>
<p>Let’s make that into a graph cause graphs are great.</p>
<pre class="sourceCode r"><code class="sourceCode r">dat_sentiment <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">spread</span>(type, score)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(character)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total =</span> positive <span class="op">+</span><span class="st"> </span>negative)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">positive_percent =</span> positive<span class="op">/</span>total<span class="op">*</span><span class="dv">100</span>,
         <span class="dt">negative_percent =</span> negative<span class="op">/</span>total<span class="op">*</span><span class="dv">100</span>,
         <span class="dt">sentiment =</span> positive_percent <span class="op">-</span><span class="st"> </span>negative_percent)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(character, positive_percent, negative_percent, sentiment)<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(sentiment))<span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(character,sentiment), <span class="dt">y =</span> sentiment)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">show.legend =</span> <span class="ot">FALSE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name =</span> <span class="st">&quot;Overall sentiment (percent)&quot;</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">name =</span> <span class="st">&quot;Character&quot;</span>)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-36"></span>
<img src="11-supplementary_files/figure-html/unnamed-chunk-36-1.png" alt="Sentiment scores for each character" width="100%" />
<p class="caption">
Figure 11.7: Sentiment scores for each character
</p>
</div>
<p><code>rtweet</code> is such a cool package and I’ve found that the limits of what you can do with it are much more about one’s imagination. There’s much more you could do with this package but when I first ran these analyses I found that tracking RuPaul’s Drag Race was a fun way to learn a new package as it did give an insight into the fan reactions of one of my favourite shows. I also use this package to look at swearing on Twitter (replace the hashtags with swear words). The best way to learn what <code>rtweet</code> and <code>tidytext</code> can do for you is to find a topic you care about and explore the options it gives you. If you have any feedback on this tutorial you can find me on twitter: <span class="citation">(<span class="citeproc-not-found" data-reference-id="emilynordmann"><strong>???</strong></span>)</span>(<a href="https://twitter.com/emilynordmann" class="uri">https://twitter.com/emilynordmann</a>).</p>

</div>
</div>
</div>



</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol){
    var tol = JSON.parse(this.dataset.tol);  
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("correct");
    } else {
      cl.remove("correct");
    }  
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("correct");
    }  
  }
  
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="dissertation-analysis-guide.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
